### ISSUE TITLE
ModuleId missing from relationship target output

### ISSUE THREAD

**Issue by Geoffrey-Lutz** [IHTSDO/snowstorm#102]
The REST call /browse/{branch}/concepts/{conceptId} does not return the moduleId for the relationship target.   Snowowl returns the target moduleId but Snowstorm does not.  Can the target moduleId be returned. in the  REST call above.

Thank you,
Geof

**Comment by kaicode** [comment]
Yes, we will add this for you. We hadn't included it because we didn't have a use case but I can see that it would be useful. We are already loading the relationship target concept to collect the definition status so it's just a case of copying the module across too - no performance impact.
