### ISSUE TITLE
Bulk subsumes/member-of operation in native API

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snowstorm#106]
I would like to be able to test if a set of concepts are subsumed by another concept all in one request to allow better performance and convenience. Allowing an ECL search in conjunction with conceptId list filtering would meet this requirement.
This idea came from the Snomed International Education Team.

**Comment by danka74** [comment]
Is it conceptA subsumes any in the set or all in the set?
Testing could be done by "<<conceptA AND (concept1 OR ... OR conceptN)" either being non-empty or having set cardinality = N. For example

**Comment by kaicode** [comment]
That's what I suggested to the Ed Team, it works, but separate params is simpler 😃
