### ISSUE TITLE
[Feature request] Upload subsets (not in RF2)

### ISSUE THREAD

**Issue by rush3r** [IHTSDO/snowstorm#110]
Hi,

I was trying to setup snowstorm with the latest US SNOMED release along with the Core problem list subset but realized the subset is not part of the RF2 release. 
I had to manually do the changes in the RF2 files to be able to upload it sucessfully.
It would be great if one could upload the subset directly without the need for these manual changes.

Thank you,
Pedro Louro

**Comment by kaicode** [comment]
FHIR ValueSets can now be created using the FHIR API.
