### ISSUE TITLE
No expansion for extensions and stored ValueSets

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#112]
Dear SNOMED,

I have PUT a ValueSet with compose to snowstorm 4.8.0 containing SE extension:
```
...compose: {
include: [
{
system: "http://snomed.info/sct/45991000052106",
filter: [
{
property: "concept",
op: "=",
value: "^53361000052102"
}
]
}
]
},
```

Implicit ValueSet expansion works well:
http://localhost:8080/fhir/ValueSet/$expand?url=http://snomed.info/sct/45991000052106?fhir_vs=ecl/%5E53361000052102&includeDesignations=true&count=10&designation=sv&designation=en&_format=json
gives the expected result, but expand on the stored ValueSet gives 0 members and this error in the log:
```
The reference set has members according to the proprietary API. 
2020-04-16 17:03:50.118 ERROR 32658 --- [nio-8080-exec-6] o.s.snowstorm.fhir.services.FHIRHelper   : No code system with default module 45991000052106/null. Using MAIN.
```

**Comment by pgwilliams** [comment]
Thanks Daniel, I'll get on that one.

**Comment by danka74** [comment]
Here's the whole ValueSet:
```
{
  "resourceType": "ValueSet",
  "status": "active",
  "name": "ReasonForEncounterValueSet",
  "id": "reason-for-encounter",
  "title": "Reason For Encounter Value Set",
  "description": "Codes describing the patient's reason for a request for care, taken from SNOMED-CT.",
  "version": "0.1.0",
  "url": "http://socialstyrelsen.se/fhir/reasonForEncounter/ValueSet/reason-for-encounter",
  "compose": {
    "include": [
      {
        "system": "http://snomed.info/sct/45991000052106/version/20200531",
        "filter": [
          {
            "property": "concept",
            "op": "=",
            "value": "^64691000052109"
          }
        ]
      }
    ]
  }
}

```

```

**Comment by danka74** [comment]
There was en error ("concept" instead of "constraint") in the ValueSet above, but even with the correct VaueSet it gives the exact same error.

**Comment by pgwilliams** [comment]
OK I think I've fixed that in the develop branch in https://github.com/IHTSDO/snowstorm/commit/58c3a952fbd221ea3409b51cd34ae8fd6792b830  Thanks for the full VS json there @danka74 , I used it (somewhat modified) for my unit test.

Leaving the issue open until we've published the release.

**Comment by danka74** [comment]
Thanks! I can confirm it works.
