### ISSUE TITLE
$expand term filtering and non-english languages

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#113]
Currently, the filter parameter only filters on english descriptions, e.g.:
http://localhost:8080/fhir/ValueSet/$expand?url=http://snomed.info/sct/45991000052106?fhir_vs=ecl/%5E500121000057102&filter=blood&displayLanguage=sv&count=10&_format=json
gives 7 hits while:
http://localhost:8080/fhir/ValueSet/$expand?url=http://snomed.info/sct/45991000052106?fhir_vs=ecl/%5E500121000057102&filter=blod&displayLanguage=sv&count=10&_format=json
gives 0 hits.
"blod" is Swedish for "blood" and appears in the beginning of a word of at least 3 of the concepts returned by the former query.
In contrast, the native API returns these 3 concepts:
http://nixv1te.sos.local:8080/MAIN%2FSNOMEDCT-SE/concepts?activeFilter=true&ecl=%5E500121000057102&offset=0&limit=10&term=blod
/Daniel

**Comment by pgwilliams** [comment]
Yes, this was fixed in https://github.com/IHTSDO/snowstorm/commit/430097edb1e23dbdef20f54e667d8d4938e701b7 so you should already have that @danka74 if you're pulling the develop branch

Testing evidence here: https://ibb.co/JxRtvMB
