### ISSUE TITLE
Dockerhub latest != last succesful build

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#117]
Hi all,

I was looking for the latest snowstorm image on docker hub, and noticed that the image tagged with latest is not the latest build. https://hub.docker.com/r/snomedinternational/snowstorm/tags
Is this deliberate, or maybe a small flaw in your workflow?

Best regards,
Sander

**Comment by rorydavidson** [comment]
Hi @mertenssander ,
It’s a mistake/human flaw in our manual workflow (on my part)! Updating this now.
Thanks.
