### ISSUE TITLE
fhir requests

### ISSUE THREAD

**Issue by steve1973** [IHTSDO/snowstorm#119]
Hi there

I've imported the International Edition and UK Clinical Extension and can access both as expected when using the API directly, e.g. `https://server/browser/MAIN/SNOMEDCT-UKC/descriptions?term=covid&groupByConcept=false&searchMode=STANDARD&offset=0&limit=50`, but can only access the MAIN branch when making fhir requests, e.g. `https://server/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&count=10&offset=1&filter=covid&_format=json`. How do I access the MAIN/SNOMEDCT-UKC branch when making a fhir request?

Many thanks

Steve

**Comment by steve1973** [comment]
I've found that if I add the UK reference set concept id to the request then I get something back, is this the correct way? e.g. `https://server/fhir/ValueSet/$expand?url=http://snomed.info/sct/999000021000000109?fhir_vs&filter=covid&count=10&_format=json`

**Comment by steve1973** [comment]
Likewise, `https://server/fhir/CodeSystem/$lookup?system=http://snomed.info/sct&version=http://snomed.info/sct/999000021000000109&code=1240751000000100&_format=json`

**Comment by pgwilliams** [comment]
Hi Steve, yes that's exactly it.  You're specifying the module that you expect that concept to exist in.   The looking between the module SCTID and the CodeSystemVersion as Snowstorm understands it is done in this application.properties file:  https://github.com/IHTSDO/snowstorm/blob/master/src/main/resources/application.properties#L179

There is code behind the CodeSystem $validate-code operation that doesn't need you to specify a module and will search the latest version of all known CodeSystem instances.   I hope to add that to the $lookup operation in the near future.

With the latest cut of the code you shouldn't need that _format parameter any more, we'll use json by default.

If that's working are you happy for me to close this ticket?   Best Wishes, Peter

**Comment by steve1973** [comment]
Hi Peter

Thanks for responding so quickly and for the information. Happy for you to close the ticket.

Kind regards

Steve

**Comment by steve1973** [comment]
Apologies, just one more thing. We have imported the Drug Extension and I've created a code system call SNOMEDCT-DMD. I presume if I add an entry to the application.properties file I can then use the corresponding ID to make fhir requests?

**Comment by pgwilliams** [comment]
Totally :-)

Or if not, get back to us and we'll figure out why not.   Most likely cause would be your application.properties file not being picked up properly.   The log files should indicate which branch is being used.
