### ISSUE TITLE
Refset import??

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#120]
Hi all,

Anyone with any advice on importing refsets? I have a test branch containing an extension. I would like to import refsets from the refset-tool onto this branch. I have discussed this before, but then with the focus of automated imports. Now another issue. The refset tool only creates the .txt-files. importing these seems to not work. But importing the full RF2-release files of i.e. the odontogram works fine.

Need I package the files from the refset tool into a RF2 zip-file? Or is there a way of just importing the individual refset .txt-file?

Regards,
Jørn Andre Jørgensen

**Comment by rorydavidson** [comment]
Hi @Tannjorn ,
At the moment, to import reference sets into the terminology server, you will need to put the refset txt files into a correctly packaged RF2 zip file.
We expect to develop this for Snowstorm at some point in the future, although there is no timeline on this for the moment. As always, we would welcome any contributions to the repository to build this in.
Thanks.

**Comment by kaicode** [comment]
Just create a zip file containing the refsets you want to import plus a blank concept, description and relationship file including the header line. No directory structure is required. It could be simpler, but not much!

Example of zip file contents from a unit test here: https://github.com/IHTSDO/snowstorm/tree/master/src/test/resources/import-tests/refset-snapshot-import

Cheers

**Comment by charley-earlytracks** [comment]
Hello here,

As I relate to this issue:
Is there now a documented way to import refsets?

Thanks,
Charley

**Comment by kaicode** [comment]
There is no newer documented way to import refsets. RF2 works well. Are there any new requirements in this area?
