### ISSUE TITLE
Get an intersection of refset members and a result of ECL expression

### ISSUE THREAD

**Issue by pavlushkin** [IHTSDO/snowstorm#124]
Hello, could you help me with a question?

How can I get a list of concepts that are simultaneously
- included in a specific reference set and 
- included in a result of provided ECL query

There are two queries that work fine if executed separately, but I can't combine it to get their intersection.
- {{url}}/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=refset/450970008
- {{url}}//fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%3C10850741000119108

Thanks!

**Comment by pavlushkin** [comment]
I found the solution. It could be handled by ECL syntax only.

For example, this ECL query returns all refset members that are disorders:
```
^450970008 |General Practice / Family Practice reference set (foundation metadata concept)| 
AND << 64572001 |Disease (disorder)|
```

**Comment by pgwilliams** [comment]
That's it exactly!
