### ISSUE TITLE
Allow customizing number of shards

### ISSUE THREAD

**Issue by nhnicwaller** [IHTSDO/snowstorm#13]
Snowstorm should allow configuring the number of shards per Elasticsearch index, rather than [hardcoding](https://github.com/IHTSDO/snowstorm/blob/4520e6b22ac48ed324d19f01e6ab0c163ad821e0/src/main/java/org/snomed/snowstorm/core/data/domain/Relationship.java#L18) the number at `8`.

I believe that I would get better performance and a smaller memory footprint if my single-instance Elasticsearch was configured with a smaller number of shards. However, I cannot easily test or validate this assumption because snowstorm does not make this value configurable. (Yes, I could test this if I built snowstorm from source rather than using the release jar.)

I tried assigning a custom index template which specifies `index.number_of_shards` and `index.number_of_replicas`, but the hardcoded values in snowstorm take precedence over the index template.

> When using the create index API, the settings/mappings defined as part of the create index call will take precedence over any matching settings/mappings defined in the template. - [elastic.co](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html)

**Comment by kaicode** [comment]
I agree, this would be a good feature.

**Comment by nhnicwaller** [comment]
It seems impossible to make the number of shards user-configurable as long as this project is using [Spring Data for Elasticsearch (SDE)](https://spring.io/projects/spring-data-elasticsearch).

The SimpleElasticsearchPersistentEntity class which assigns the number of shards has only one code path, and that is to [read the hardcoded integer](https://github.com/spring-projects/spring-data-elasticsearch/blob/f89c3a0e20226c2fd8ac72fdd1467b4ac56fe348/src/main/java/org/springframework/data/elasticsearch/core/mapping/SimpleElasticsearchPersistentEntity.java#L83) directly out of the `@Document` annotation. 

I looked in the [JIRA tracker for Spring Data Elasticsearch](https://jira.spring.io/projects/DATAES/issues/DATAES-387?filter=allopenissues) and found zero prior requests of anybody wanting to make it possible for `shards` to be set with a variable. And I further looked at the [Spring Data Elasticsearch Support](https://groups.google.com/forum/#!forum/spring-data-elasticsearch-devs) Google Group and found no evidence of people wanting shards to be set with a variable. So this seems to be somewhat of an edge case.

Because it doesn't seem possible to make this change without also significant architectural changes, I suggest closing this issue as _will not fix_.

**Comment by kaicode** [comment]
Thanks for digging into this Nic. I have actually already forked Spring Data Elasticsearch in order to implement the Elasticsearch REST protocol but it's sensible not to diverge further than we need to. Will mark this as won't fix for now. Cheers!

**Comment by kaicode** [comment]
This is fixed in the develop branch and will be included in version 3.x of Snowstorm. The new default is 1 shard per index. 
SNOMED International will be using between 3 and 6 shards for our production cluster.

**Comment by kaicode** [comment]
This is fixed in release [3.0.3](https://github.com/IHTSDO/snowstorm/releases/tag/3.0.3).
See [elasticsearch.index.shards](https://github.com/IHTSDO/snowstorm/blob/3.0.3/src/main/resources/application.properties#L51) in application.properties.
