### ISSUE TITLE
Language support in FHIR API

### ISSUE THREAD

**Issue by goranoe** [IHTSDO/snowstorm#14]
As far as I can see the FHIR API does not support any other languages than the language imported in the MAIN branch. I am running Snowstorm with the international release in the MAIN branch and the Swedish edition in MAIN/SNOMEDCT-SE. I've tested the FHIR lookup-operations on CodeSystem and it always uses the MAIN branch, so I am not able to get the Swedish translations through FHIR . The regular REST-API works using the Accept-Language http-header, so I have verified that the Swedish release has been imported correctly.

**Comment by rorydavidson** [comment]
Both the FHIR coverage and implementation are experimental on snowstorm at the moment and I'd not recommend using it yet. This is on our roadmap in the first half of next year, although we always welcome any contributions to improve this in the meantime.

**Comment by goranoe** [comment]
Thanks for the quick response! I will look at it and try to contribute.

**Comment by kaicode** [comment]
Included in release 2.2.0.
