### ISSUE TITLE
fhir/CodeSystem/$subsumes does not know how to handle GET operation

### ISSUE THREAD

**Issue by danwa223** [IHTSDO/snowstorm#141]
Hello IHTSDO!

I am running Snowstorm 4.8.0 on localhost, with the intention to exhaustively test some endpoints to evaluate performance. I am running a SNAPSHOT import of the 2020-03-09 release files of SNOMED CT, following your own documentation on how to upload them.

I have been following your fhir endpoint documentation, both on [github](https://github.com/IHTSDO/snowstorm/blob/master/docs/fhir-requests.http) and on [postman](https://documenter.getpostman.com/view/462462/S1TVXJ3k?version=latest#9f732d6b-0bae-43c3-9849-875f42782c9a). Things have been going well and I am able to successfully query a plethora of endpoints, including CodeSystem/$lookup, ConceptMap/$translate and ValueSet/$validate-code, in addition to several SNOMED CT API endpoints.

Specifically, I am trying to do the exact same thing as your own API call:

`https://snowstorm-fhir.snomedtools.org/fhir/CodeSystem/$subsumes?system=http://snomed.info/sct&version=http://snomed.info/sct/900000000000207008/version/20200131&codeA=307355007&codeB=118940003`, which by the way also works without the version param (since it assumes latest version, in accordance with HL7s FHIR documentation).

I tried to do the same thing with my localhost implementation, like so:

`http://localhost:8080/fhir/CodeSystem/$subsumes?system=http://snomed.info/sct&codeA=307355007&codeB=118940003`, but this only throws an InvalidRequestException, with the log `Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[CodeSystem/$subsumes] with parameters [[codeB, codeA, system]]`. Naturally, I tried adding a version param, but got the same error message back, except with parameters `[[codeB, codeA, system, version]]`.

Any suggestions on what I may be doing wrong? I've been trying for many hours to find any syntax errors or likewise on my end. Any input or clarification as to why it is throwing this exception would be greatly appreciated.

Thank you for your time. Best wishes,
Daniel

**Comment by rorydavidson** [comment]
Hi @danwa223 ... we've just released 4.12.1, https://github.com/IHTSDO/snowstorm/releases/tag/4.12.1, and in the interim releases, there were a lot of fixes on the FHIR API. I'd recommend updating to that version to see if that now works?

**Comment by danwa223** [comment]
Hello @rorydavidson,

Now I feel silly. Of course I should have updated, I've been running this release since late april.

Updating to 4.12.1 did indeed fix the issue, I can query as I intended to. This can be closed, and thank you for the swift response.

**Comment by rorydavidson** [comment]
Glad to hear it, and no worries, there are no silly questions!
