### ISSUE TITLE
TraceabilityLogServiceTest.createDeleteConcept:67 NullPointer

### ISSUE THREAD

**Issue by julioalpa** [IHTSDO/snowstorm#148]
Hi there, 

I follow the instructions to install snowstorm using maven but i receive this error:

- Errors: 
[ERROR]   TraceabilityLogServiceTest.createDeleteConcept:67 NullPointer

Can anybody help me?

Thanks, BR

**Comment by rorydavidson** [comment]
Hi @julioalpa, 
could you please clarify which version of Java you are using?
Thanks

**Comment by julioalpa** [comment]
I was try with versions 8 and 11, same result

**Comment by julioalpa** [comment]
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_265, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: es_AR, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"

**Comment by julioalpa** [comment]
Maybe this helps

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project snowstorm: There are test failures.

**Comment by rorydavidson** [comment]
Have you tried to compile without the tests to see if that is successful (using `-Dmaven.test.skip=true`)?

**Comment by julioalpa** [comment]
Great, that works! 

Thanks @rorydavidson

**Comment by rorydavidson** [comment]
Glad to hear it
