### ISSUE TITLE
import SnomedCT_LOINCRF2

### ISSUE THREAD

**Issue by MahboobehJannesari** [IHTSDO/snowstorm#154]
Hi
I want to import SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z, what steps should I do?
I just imported  snapshot of SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.

do I import such as an extension or edition? is there any problem with versions?

Another question is:  where can I find a list of refsets of snomed ct to download?
for example I want to know '' Escherichia coli" presents in which refsets, find these refsets and add to snowstorm.

Could you please help me ?

**Comment by rorydavidson** [comment]
Hi @MahboobehJannesari,

you can load it as an extension as documented here <https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md#loading-extensions> but there a few things to be aware of with the LOINC expression map. It is based on an older version of SNOMED CT (July 2017 release) and is map from SNOMED CT expressions to LOINC. We have not tested this and cannot confirm if it will work as expected.

To your second question, to get a list of reference sets you can simply search using the SNOMED CT constraint language for all types of simple reference set (<< 446609009 |Simple type reference set (foundation metadata concept)| in the concepts endpoints, http://localhost:8080/swagger-ui.html#!/Concepts/findConceptsUsingGET (in the ecl parameter field)

For access any information about reference sets a concept may be part of, you can use the reference set end point http://localhost:8080/swagger-ui.html#!/Refset_Members/findRefsetMembersUsingGET

Hope this helps.

**Comment by danka74** [comment]
Dear @MahboobehJannesari ,

The SNOMED-LOINC expression reference set contains SNOMED CT compositional grammar expressions (a.k.a. post-coordinated expressions) and currently there is no way to import the expressions into snowstorm and classify them.
You can translate the expressions into OWL and load them into e.g. Protege. 

Cheers,
Daniel

**Comment by MahboobehJannesari** [comment]
Hi,

I upload SNOME_LOINC as an Extension on top of snomed ct_international_20200731 , but outputs are as before. it does not work.
Could you (@danka74) please explain me how  can I translate the expressions into OWL?

Best
Mahboubeh

**Comment by danka74** [comment]
@MahboobehJannesari ,

I don't think it is possible in snowstorm. I know there is some work on post-coordination in snowstorm but I don't think there is anything working now, @kaicode will know. I assume there will be some technical challenges since SNOMED International may not add concept ids to the expressions per the agreement.
Translating the expressions to OWL is possible, I built a tool to do that, but it was ages ago and I have not kept it updated as I no longer need to use it. Please have a look here if you can find anything useful: https://github.com/danka74/SnomedCTParser
Translation to OWL will still not make them much more importable into snowstorm though.

/Daniel

**Comment by danka74** [comment]
@MahboobehJannesari ,

also, the overlap between LOINC and SNOMED CT (for LOINC terms) is zero, at least approximately, and depending on interpretation. There are no (exactly zero-dot-zero!) matches between expressions in the LOINC-SNOMED expression reference set and SNOMED CT pre-coordinated concepts. There is a LOINC parts to SNOMED mapping though which you might be able to make use of.

**Comment by MahboobehJannesari** [comment]
Thanks for your comments.
How can I use this  LOINC parts in snowstorm?

**Comment by danka74** [comment]
@MahboobehJannesari ,
I haven't tried it myself, but you can download the release package from MLDS (where you get SNOMED CT) https://mlds.ihtsdotools.org/#/ihtsdoReleases/ihtsdoRelease/67305
I'm guessing that you already did that!
I believe that this is the refset id: 705112009 |LOINC Part map reference set| (found it by googleing!)
Then you can use the REST calls @rorydavidson described above to search for refset members, or use the FHIR API ConceptMap $translate operator.
E.g. this should work if you have the LOINC Parts map reference set installed (finds the mapping for 259295006 | Calcium electrolyte (substance) |): http://localhost:8080/MAIN/members?referenceSet=705112009&referencedComponentId=259295006&offset=0&limit=50

/Daniel

**Comment by MahboobehJannesari** [comment]
Ok, it works.
but becuase I just have a term  such as "Calcium electrolyte".
first I should search and find conceptId (STCID) and then use it as  referencedComponentId? right?

**Comment by danka74** [comment]
Yes, that's correct. You can also use it backwards with the mapTarget parameter, but you'll need the LOINC part code I guess.

**Comment by MahboobehJannesari** [comment]
No, for example for asthma I use http://localhost:8080/MAIN/concepts?term=asthma and extract STCID by python script,
Is there any way to get referenceComponentId?

**Comment by danka74** [comment]
referencedComponentId is just a SNOMED component id (SCTID), the id of the component (in the case of the LOINC parts map, a concept id) that is referenced in the refset row. Here's an explanation of how referencedComponentId works: https://confluence.ihtsdotools.org/display/DOCRELFMT/5.2.1+Simple+Reference+Set
Here's a description of how a map reference set works: https://confluence.ihtsdotools.org/display/DOCRELFMT/5.2.9+Simple+Map+Reference+Set
Sorry if you are fully familiar with this already.

**Comment by MahboobehJannesari** [comment]
based on this page:
https://loinc.org/news/draft-loinc-snomed-ct-mappings-and-expression-associations-now-available/
I can extract LOINC term and LOINC part using  LOINC Term to SNOMED Expression Reference set and LOINC Part to SNOMED Reference Set.

To find a LOINC term for a specific term such as Calcium electrolyte I use 705110001 (https://confluence.ihtsdotools.org/display/DOCLOINC/4.2.2+LOINC+Term+to+Expression+Reference+Set) as refset Id, but I dont know what I use as 
referencedComponentId, it does not work like LOINC part.
If I use 705114005, I got 21889 items such as 


"items": [
    {
      "internalId": "PQADtXQBaBVT6RhrDWyH",
      "path": "MAIN/SNOMEDCT-LOINCRF2",
      "start": 1600764709710,
      "active": true,
      "effectiveTimeI": 20170731,
      "released": true,
      "releaseHash": "true|715515008|contentOriginId|705117003|correlationId|447557004|definitionStatusId|900000000000073002|expression|363787002:246093002=720113009,370134009=123029007,246501002=702675006,704327008=122592007,370132008=117363000,704319004=50863008,704318007=705057003|mapTarget|48023-6",
      "releasedEffectiveTime": 20170731,
      "memberId": "80012784-4762-42ca-9a6b-ca3675842266",
      "moduleId": "715515008",
      "refsetId": "705110001",
      "referencedComponentId": "705114005",
      "additionalFields": {
        "contentOriginId": "705117003",
        "expression": "363787002:246093002=720113009,370134009=123029007,246501002=702675006,704327008=122592007,370132008=117363000,704319004=50863008,704318007=705057003",
        "definitionStatusId": "900000000000073002",
        "correlationId": "447557004",
        "mapTarget": "48023-6"
      },
      "effectiveTime": "20170731"
    },
    {
      "internalId": "QAADtXQBaBVT6RhrDWyH",
      "path": "MAIN/SNOMEDCT-LOINCRF2",
      "start": 1600764709710,
      "active": true,
      "effectiveTimeI": 20170731,
      "released": true,
      "releaseHash": "true|715515008|contentOriginId|705117003|correlationId|447557004|definitionStatusId|900000000000073002|expression|363787002:704323007=123027009,704321009=718500008,704327008=122575003,704322002=64033007,704318007=118544000,370132008=30766002,704324001=706939009|mapTarget|51406-7",
      "releasedEffectiveTime": 20170731,
      "memberId": "8002323d-3ddf-4a3c-b1dd-a6eb0770ba35",
      "moduleId": "715515008",
      "refsetId": "705110001",
      "referencedComponentId": "705114005",
      "additionalFields": {
        "contentOriginId": "705117003",
        "expression": "363787002:704323007=123027009,704321009=718500008,704327008=122575003,704322002=64033007,704318007=118544000,370132008=30766002,704324001=706939009",
        "definitionStatusId": "900000000000073002",
        "correlationId": "447557004",
        "mapTarget": "51406-7"
      },
      "effectiveTime": "20170731"
    },


I mixed by referenceComponentId, I dont know which item for which term and how can I find a LOINC term and mapTarget for 
a term?
which key is unique id for a term in snomed ct?

**Comment by danka74** [comment]
Someone else might know more but I believe that mapping from 705114005 | LOINC Code System (qualifier value) | to each expression was a "hack" to allow using the SNOMED reference set specifications while avoiding breaking the agreement to not have SNOMED CT id:s for LOINC terms.

In SNOMED CT there are no concepts directly and exactly corresponding to the LOINC terms, so there are no referencedComponentIds in the international edition! Jim Campbell of Nebraska though has imported the SNOMED-LOINC expressions into their extension, so talking to him might be a good idea.

**Comment by rorydavidson** [comment]
Closing thread as it's been answered.
