### ISSUE TITLE
Error Launching ElasticSearch 7.70 and Snowstorm (Branch 'MAIN' does not exist)

### ISSUE THREAD

**Issue by ozairbajwa80** [IHTSDO/snowstorm#157]
Hi, 
I am setting up my environment with ElasticSearch 7.7.0 and Snowstorm by following this link:
https://github.com/IHTSDO/snowstorm
I performed the following steps:
Installed and ran the ElasticSearch version (7.7.0).
Downloaded the SNOMED CT R2 release files
Downloaded the Snowstorm Application jar. 
After running ElasticSearch I ran the Snowstorm jar, however it failed to start and load the SNOMED CT Content. I tried using REST and the command line. From the REST I was not able to bring up the server at http://localhost:8080.
From the command line I ran the following command:
java -Xms2g -Xmx4g -jar snowstorm-4.13.0.jar --delete-indices --import=C:\SNOMED\SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip

I am getting the same error on both routes. It is complaining that the "MAIN" branch does not exist.

The error logs are attached:

Any help will be greatly appreciated.

Thanks,
Ozair
[SNOMED_Terminology_ErrorLogs.txt](https://github.com/IHTSDO/snowstorm/files/5258087/SNOMED_Terminology_ErrorLogs.txt)

**Comment by rorydavidson** [comment]
Hi @ozairbajwa80, this is our fault, sorry! 
Please can you download the most recent release, https://github.com/IHTSDO/snowstorm/releases, which works with ElastiSearch 7.7. The one you are using (v4.13) only works with older versions of elasticsearch.

**Comment by ozairbajwa80** [comment]
Thanks a lot @rorydavidson. I was able to resolve the issue by downloading the latest release of Snowstorm.
