### ISSUE TITLE
Adding concepts to the MRCM-refset

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#159]
Does anyone have experience with adding rules to the MRCM at branch/extension-level?

My use-case is to create a test-branch for adding administrable dose form to the medicinal product hierarchy. This is to be done purely on a test-server, and experiences will pave the way for a possible expansion in our national release. My thought was to simply create the necessary refsets in our own extension, but I have no tool supporting the generation of the GUID-id's.

Therefore I thought I might use the add refset member function to add the attribute to the domain, and the range to the attribute. But the post-template appears to be for the simple-refset. Does anyone have a schema for this kind of post? Or does SnowStorm even support it?

I see there is a project for a MRCM editor, but as far as I can tell it hasn't reached a deliverable app.

Regards,
Jørn

**Comment by kaicode** [comment]
Hi @Tannjorn,

The International authoring team are using the [MRCM Maintenance tool](https://github.com/IHTSDO/mrcmmt-ui) in production to author MRCM rules with Snowstorm as the API.
<img width="1342" alt="Screenshot 2020-09-23 at 20 20 19" src="https://user-images.githubusercontent.com/2010517/94059582-8daf5f80-fdda-11ea-8220-b2b9ea6e9710.png">

MRCM Domain Attribute members and MRCM Attribute Range members can be created via the **POST /{branch}/members** API endpoint.
Here is an example request body for creating a domain attribute:
```
{
	"refsetId": "723561005",
	"active": true,
	"moduleId": "900000000000012004",
	"referencedComponentId": "246246002",
	"additionalFields": {
		"domainId": "373873005",
		"grouped": "1",
		"attributeCardinality": "0..*",
		"attributeInGroupCardinality": "0..1",
		"ruleStrengthId": "723597001",
		"contentTypeId": "723596005",
		"rangeConstraint": "*"
	}
}
```
And an attribute range:
```
{
	"refsetId": "723562003",
	"active": true,
	"moduleId": "900000000000012004",
	"referencedComponentId": "246246002",
	"additionalFields": {
		"domainId": null,
		"rangeConstraint": "*",
		"ruleStrengthId": "723597001",
		"contentTypeId": "723596005"
	}
}
```
I hope that helps.
Kai

**Comment by kaicode** [comment]
Closing as question has been answered.
