### ISSUE TITLE
Incorrect total concept count in /{branch}/concepts

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#161]
Hi all,

The concepts endpoint does not always return the correct amount of total concepts.

https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN%2FSNOMEDCT-NL/concepts?returnIdOnly=true
Returns a 'total' value of 10k concepts. My local build of 5.0.2 does the same thing.

Also; the searchAfter value is missing in some of the cases. The above URI does return it, but https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN%2FSNOMEDCT-NL/concepts does not.

Any idea what causes this?

Best regards,
Sander

**Comment by kaicode** [comment]
Thanks for spotting this @mertenssander. This issue looks specific to the /{branch}/concepts endpoint when the new returnIdOnly option is used. The count is correct without that option. We will get this fixed and check the total counts on all other endpoints.
Kai

**Comment by kaicode** [comment]
This is fixed in the master branch, I'll leave this ticket open until we publish a release in the next few days.

**Comment by kaicode** [comment]
Fixed in [5.0.6](https://github.com/IHTSDO/snowstorm/releases/tag/5.0.6).
