### ISSUE TITLE
Snowstorm start error - Elasticsearch exception "FORBIDDEN/12/index read-only"

### ISSUE THREAD

**Issue by rsvasan** [IHTSDO/snowstorm#163]
Hi,
I am deploying snowstorm (v4.13.0) on top of Elasticsearch (v6.8.12). Elasticsearch is running in the background, when I start snowstorm it gives me the following error (pls. see the attachment). I would appreciate any help in resolving this. My system environment is Ubuntu 20.04.
Thanks much
Srini
[sstorm_start_error.log](https://github.com/IHTSDO/snowstorm/files/5287560/sstorm_start_error.log)

**Comment by kaicode** [comment]
Hi @rsvasan,
We see the error `FORBIDDEN/12/index read-only / allow delete` when Elasticsearch has put itself into a read only state. The Elasticsearch logs should have more information but this commonly happens when the disk partition that Elasticsearch is using has low disk space. See issue #67.

**Comment by rsvasan** [comment]
Thanks Kai, indeed that was the issue. I could deploy it successfully on a larger partition.
Srini
