### ISSUE TITLE
Elasticsearch losing index?

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#164]
Hi all,

I have recently upgraded my local snowstorm instance to 5.0.2, and have not been able to keep it running for more than a couple of days in a row. Today it went down after just one day, and I have decided I require assistance.

My instance is running on a CentOS server in docker, using your prebuilt images.

The relevant part of the compose file is shown in; https://pastebin.com/46vRq5ft
Elasticsearch logs https://pastebin.com/raw/4PQQ9LKu
Snowstorm logs https://pastebin.com/raw/z9X18EPU

Running any query against snowstorm results in;
`{
  "error": "INTERNAL_SERVER_ERROR",
  "message": "Index [branch] not found.; nested exception is [branch] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [branch]]]"
}`

As I said, this can happen after a week, 1 day, a few hours, etc. The only way I have found to remedy this is rebuilding the entire stack, which results in outages in my services. I have tried returning to 4.7, but unfortunately this results in the same issue.

Any chance you can make sense of these logs? Thanks in advance!

Best regards,
Sander

**Comment by rorydavidson** [comment]
Hi @mertenssander , doesn't sound good! Which version of elastic search are you using?

**Comment by mertenssander** [comment]
Hi @rorydavidson ,

I'm using the prebuilt docker image docker.elastic.co/elasticsearch/elasticsearch:7.7.0

**Comment by CoderMChu** [comment]
@mertenssander,

Can you please confirm the elasticsearch data in "/usr/share/elasticsearch/data" is migrated to ES7 or newly imported using Snowstorm 5.0.2? If you are using data from ES6 it will not work with 5.0.2.

**Comment by mertenssander** [comment]
Hi @CoderMChu ,

I have created everything from scratch, using ES7 and snowstorm 5.0.2.
To be clear; everything works perfectly and as expected, right up until the moment that the indices are lost. After it fails, I kill the stack, remove all volumes and cached data, and restart the import process.

**Comment by apeteri** [comment]
Hi @mertenssander,

This seems to be the result of an automated attack on open Elasticsearch instances. In your ES log a single index named "meow" is created, while all other content is removed.

https://www.elastic.co/blog/protect-your-elasticsearch-deployments-against-meow-bot-attacks-for-free
https://discuss.elastic.co/t/some-indexes-have-been-deleted-now-i-see-indexes-called-meow/242731

**Comment by mertenssander** [comment]
> Hi @mertenssander,
> 
> This seems to be the result of an automated attack on open Elasticsearch instances. In your ES log a single index named "meow" is created, while all other content is removed.
> 
> https://www.elastic.co/blog/protect-your-elasticsearch-deployments-against-meow-bot-attacks-for-free
> https://discuss.elastic.co/t/some-indexes-have-been-deleted-now-i-see-indexes-called-meow/242731

That is an interesting observation! My elasticsearch instance _should_ not be accessible from outside the local docker network between ES and Snowstorm.. Could this happen through snowstorm?

**Comment by mertenssander** [comment]
> > Hi @mertenssander,
> > This seems to be the result of an automated attack on open Elasticsearch instances. In your ES log a single index named "meow" is created, while all other content is removed.
> > https://www.elastic.co/blog/protect-your-elasticsearch-deployments-against-meow-bot-attacks-for-free
> > https://discuss.elastic.co/t/some-indexes-have-been-deleted-now-i-see-indexes-called-meow/242731
> 
> That is an interesting observation! My elasticsearch instance _should_ not be accessible from outside the local docker network between ES and Snowstorm.. Could this happen through snowstorm?

To place the blame squarely in my court; this is not true. My elasticsearch is accessible from the public IP. I will rectify this and report back.
Thank you for pointing me in this direction!

**Comment by rorydavidson** [comment]
Thanks @apeteri. That's a new one...

**Comment by mertenssander** [comment]
If I might suggest an improvement to the published compose file in this repo; 
Maybe it would be an option to create a private network betweek snowstorm and ES. ES never needs to be exposed to the public in order to use snowstorm.
https://github.com/IHTSDO/snowstorm/blob/9834e136934b359671af56ca5ccfab5a4084c9b2/docker-compose.yml#L22

**Comment by nagyo** [comment]
Hi @mertenssander,

You can close that port by modifying just the port declaration in the docker-compose file. According to the Docker Compose [reference](https://docs.docker.com/compose/compose-file/):
```
expose:
  - 9200
```
will open the port only to the docker network but neither to the host nor to the outside world

```
ports:
  - 9200:9200
```
will open the port to the docker network, to the host and to the outside world

```
ports:
  - 127.0.0.1:9200:9200
```
will open the port to the docker network and to the host, but not to the outside world. (this could come in handy in case you want to access the ES REST API from the host) 

See more here: https://stackoverflow.com/questions/40801772/what-is-the-difference-between-docker-compose-ports-vs-expose

**Comment by rorydavidson** [comment]
Thanks for the advice @nagyo. Changes made and will be pushed to the repo to stop this happening in the future.

**Comment by mertenssander** [comment]
Thanks for the quick response and advice from all involved!
