### ISSUE TITLE
Perform case-insensitive Regex description search

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [IHTSDO/snowstorm#169]
Is it possible to perform a case-insensitive Regex search in `findBrowserDescriptionsUsingGET`?

If I pass `/.*asth.*/i` as the term, I get no results, whereas if I pass `.*asth.*` the first result returned, due to the case-sensitivity of the search is "Hay asthma", whereas I'm looking to return "Asthma" first.

Passing `.*Asth.*|.*asth.*` achieves the result, but clearly it is not a viable solution to pass all possible permutations of capitalisation of all possible searches to the service. I cannot use the "STANDARD" search in my use-case, as I'm trying to replace an existing solution with Snowstorm without affecting an existing client, which currently uses case-insensitive Regex searches.

**Comment by kaicode** [comment]
Hi @evergreen-lee-campbell, 
The REGEX search mode in Snowstorm uses an [Elasticsearch regular expression](https://www.elastic.co/guide/en/elasticsearch/reference/master/regexp-syntax.html) against the original, unmodified term of descriptions.
A case insensitive regex search could be achieved by placing lower and upper case version of each letter in square brackets like this: `.*[aA][sS][tT][hH].*`.
I hope that helps.
Kai
