### ISSUE TITLE
AWS Linux docker-compose - native memory allocation (mmap) failed

### ISSUE THREAD

**Issue by FilipTNH** [IHTSDO/snowstorm#170]
Hello, 
Setting up a snowstorm environment on  an Amazon Web Services instance doesn't go as planned:

Environment is an AWS Linux instance with 2CPU, 8GB memory and 30 GB disk, java8, docker, docker-compose
Initial Docker-compose up -d exits with remark: ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]  => fixed as suggested.   

Docker-compose up -d now launches Elasticsearch and Snowstorm containers
[docker-compose.yml.txt](https://github.com/IHTSDO/snowstorm/files/5395967/docker-compose.yml.txt)

 without errors

Upload of INT RF2 goes well till almost the end of the load process (saving QueryConcepts).
Then Snowstorm exits with:
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000715580000, 1177026560, 0) failed; error='Out of memory' (errno=12)
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1177026560 bytes for committing reserved memory. 

I've tried to: adapt the .yml to give snowstorm more memory
ulimits:
      nofile: 65535
mem_reservation: 2g

and to upload with smaller batch-sizes
--elasticvc.save.batch-size=1000

without succes.  

I attach the info of the docker stats, the docker inspection of the containers, and the log files on elasticsearch and snowstorm.  I'm out of options.  What am I overlooking? 
Can anybody point me in the right direction?

Thanks and kind regards,
Filip

[AWS_error_log.txt](https://github.com/IHTSDO/snowstorm/files/5395944/AWS_error_log.txt)
[AWS_error_log_es_and_docker_stats.txt](https://github.com/IHTSDO/snowstorm/files/5395946/AWS_error_log_es_and_docker_stats.txt)
[AWS_error_log_docker_inspect.txt](https://github.com/IHTSDO/snowstorm/files/5395912/AWS_error_log_docker_inspect.txt)

**Comment by FilipTNH** [comment]
I changed back to the original vm.max_map_count of 65.530, in line with the 8 GB of the AWS linux instance.
I will now compare the original .yml with the one I'm using.

**Comment by FilipTNH** [comment]
Maybe I have to move to an instance with 16GB memory.   Launching with docker-compose up -d gives these 2 errors:
ERROR: [2] bootstrap checks failed
[1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
[2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

Full log on the container:
[ec2-user@ip-172-31-44-10 snowstorm-master]$ docker-compose up -d
Creating network "snowstorm-master_elastic" with the default driver
Pulling snowstorm (snomedinternational/snowstorm:5.0.6)...
5.0.6: Pulling from snomedinternational/snowstorm
e7c96db7181b: Already exists
f910a506b6cb: Already exists
c2274a1a0e27: Already exists
47e454a8977d: Pull complete
3322ef8eddbb: Pull complete
47e288a7486c: Pull complete
c192b56b0e5a: Pull complete
582fadba0c64: Pull complete
Digest: sha256:8b87fdce61f4b52b7ad3789f4bd01ea6dbd0c794c9e3bd4bbe73622c6766933a
Status: Downloaded newer image for snomedinternational/snowstorm:5.0.6
Creating elasticsearch ... done

ERROR: for snowstorm  Container "1121f18cb4c0" is unhealthy.
ERROR: Encountered errors while bringing up the project.
[ec2-user@ip-172-31-44-10 snowstorm-master]$ docker logs 1121f18cb4c0
{"type": "server", "timestamp": "2020-10-18T19:09:01,526Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/xvda1)]], net usable_space [8.9gb], net total_space [29.4gb], types [ext4]" }
{"type": "server", "timestamp": "2020-10-18T19:09:01,537Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "heap size [4gb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2020-10-18T19:09:01,937Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "node name [snowstorm], node ID [PXrkDpHaSxG9aLGtx-61sQ], cluster name [snowstorm-cluster]" }
{"type": "server", "timestamp": "2020-10-18T19:09:01,941Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "version[7.7.0], pid[6], build[default/docker/81a1e9eda8e6183f5237786246f6dced26a10eaf/2020-05-12T02:01:37.602180Z], OS[Linux/4.14.193-113.317.amzn1.x86_64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14/14+36]" }
{"type": "server", "timestamp": "2020-10-18T19:09:01,941Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
{"type": "server", "timestamp": "2020-10-18T19:09:01,941Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-12938716479554986305, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms4g, -Xmx4g, -XX:MaxDirectMemorySize=2147483648, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,718Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [aggs-matrix-stats]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,718Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [analysis-common]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,719Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [constant-keyword]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,719Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [flattened]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,719Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [frozen-indices]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,720Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [ingest-common]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,721Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [ingest-geoip]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,721Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [ingest-user-agent]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,721Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [lang-expression]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,722Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [lang-mustache]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,722Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [lang-painless]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,722Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [mapper-extras]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,723Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [parent-join]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,723Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [percolator]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,723Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [rank-eval]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,724Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [reindex]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,724Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [repository-url]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,725Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [search-business-rules]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,726Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [spatial]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,726Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [tasks]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,726Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [transform]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,727Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [transport-netty4]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,727Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [vectors]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,727Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-analytics]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,728Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-async-search]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,728Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-autoscaling]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,728Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-ccr]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,729Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-core]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,729Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-deprecation]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,729Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-enrich]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,729Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-eql]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,730Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-graph]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,730Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-identity-provider]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,730Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-ilm]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,731Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-logstash]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,731Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-ml]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,731Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-monitoring]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,731Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-ql]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,732Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-rollup]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,732Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-security]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,732Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-sql]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,732Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-voting-only-node]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,733Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2020-10-18T19:09:04,733Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2020-10-18T19:09:09,857Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "parsed [0] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
{"type": "server", "timestamp": "2020-10-18T19:09:10,495Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "[controller/225] [Main.cc@110] controller (64 bit): Version 7.7.0 (Build a8939d3da43f33) Copyright (c) 2020 Elasticsearch BV" }
{"type": "server", "timestamp": "2020-10-18T19:09:11,131Z", "level": "DEBUG", "component": "o.e.a.ActionModule", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "Using REST wrapper from plugin org.elasticsearch.xpack.security.Security" }
{"type": "server", "timestamp": "2020-10-18T19:09:11,351Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "using discovery type [zen] and seed hosts providers [settings]" }
{"type": "server", "timestamp": "2020-10-18T19:09:12,380Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "initialized" }
{"type": "server", "timestamp": "2020-10-18T19:09:12,381Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "starting ..." }
{"type": "server", "timestamp": "2020-10-18T19:09:12,580Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}" }
{"type": "server", "timestamp": "2020-10-18T19:09:13,015Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }
ERROR: [2] bootstrap checks failed
[1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
[2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/snowstorm-cluster.log
{"type": "server", "timestamp": "2020-10-18T19:09:13,044Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "stopping ..." }
{"type": "server", "timestamp": "2020-10-18T19:09:13,080Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "stopped" }
{"type": "server", "timestamp": "2020-10-18T19:09:13,080Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "closing ..." }
{"type": "server", "timestamp": "2020-10-18T19:09:13,110Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "closed" }
{"type": "server", "timestamp": "2020-10-18T19:09:13,112Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "snowstorm-cluster", "node.name": "snowstorm", "message": "Native controller process has stopped - no new native processes can be started" }
[ec2-user@ip-172-31-44-10 snowstorm-master]$

**Comment by kaicode** [comment]
Sounds like you have done the right thing adjusting the Snowstorm heap memory.

The issue now is that the Elasticsearch [bootstrap checks](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html) are failing.

I wonder if just increasing the max file descriptors would help?

Our Snowstorm instances are using the AWS ES service so we are not having to set the vm.max_map_count for Elasticsearch nodes. We are using Elasticsearch for other projects and where ES runs on the same machine we have it set to 262144.

**Comment by FilipTNH** [comment]
Works now.  I moved to an AWS instance with 16GB memory.  I still had to change vm.max_mapcount to 262.144 and edit snowstorm-master.yml (added ulimits:  nofile: 65535 for both the elastic and the snowstorm container).  Snowstorm is installing without problems (using docker-compose) and also the upload of INT and BE was really fast.  Maybe the AWS 8GB instance was just too small.

**Comment by rorydavidson** [comment]
Thanks, for letting us know @FilipTNH . I think that 8GB is an absolute minimum when using docker containers but 16GB will be more recommended. I'll update the Docker documentation to reflect this.

**Comment by kaicode** [comment]
Thanks for the update @FilipTNH 👍
