### ISSUE TITLE
If I upgrade snowstorm to a new version, do I need to reload all the content?

### ISSUE THREAD

**Issue by kaboyles** [IHTSDO/snowstorm#172]
If I upgrade snowstorm to a new version, do I need to reload all the content?

**Comment by rorydavidson** [comment]
@kaboyles Generally, no. 
However, now and then, there may be a major release/update to snowstorm where you might need to rebuild the indices or fol.low a particular upgrade process. When this is the case, this will always be made clear in the release notes which can be found here - https://github.com/IHTSDO/snowstorm/releases.
