### ISSUE TITLE
Local SS -> export RF2 ->SNOMED SS->AT ---- is this possible?

### ISSUE THREAD

**Issue by kaboyles** [IHTSDO/snowstorm#174]
Hello,

We have an internal tool that is working with our local snowstorm instance via API.

If I create an RF2 of the work that has been done in our local instance, 
can I somehow send it to our Managed Serviced snowstorm instance, so we can work with the concepts in the authoring tool?

Thanks,
Kim

**Comment by rorydavidson** [comment]
Hi @kaboyles, this is 'theoretically' possible. The only potential issue is that there may be conflicts with SNOMED CT component identifiers unless you are using a sequence and namespace range different from what you use in the managed service. As always, only one way to find out!

**Comment by kaboyles** [comment]
Thanks Rory, what are the steps after the RF2 is created?

**Comment by rorydavidson** [comment]
@kaboyles get in touch with us via email, and we'll see what we can do to help.
