### ISSUE TITLE
Add the spring boot actuator dependency

### ISSUE THREAD

**Issue by manuel-palacio** [IHTSDO/snowstorm#179]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html

Would make snowstorm easier to monitor by adding at least the /actuator/health endpoint

**Comment by kaicode** [comment]
Added SI Jira ticket `MAINT-1523`

**Comment by kaicode** [comment]
GitHub is not allowing my to assign @jbarcas to this ticket but he has made the change and done the testing 😄 .

**Comment by kaicode** [comment]
This is included in the [6.0.3 release](https://github.com/IHTSDO/snowstorm/releases/tag/6.0.3), thanks to @jbarcas 🙇
