### ISSUE TITLE
Posting New Concepts using Put/Post

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#180]
Does anyone have an example post of a new concept with stated relationships?

We have made several atttempts, But we some issues, most of them relating to understanding of the different elements. I have not found any specification of all import attributes.

Questions may be as simple as:
Does groupID or relationshipGroup set the attribute grouping? Or should they both be stated the same way?
There is no "targetId" in the schema, but there is a "target" - is "destionationId" the "targetId"?
What fields are required or optional?

Any input is appreciated.

Regards,
Jørn

**Comment by Tannjorn** [comment]
As background, this is my latest post - which seems to be acceptable. But there is an issue with groups, and another issue with surplus notations.

{
"active":true,
"classAxioms": [
    {
      "active": true,
      "definitionStatusId": "900000000000074008",
      "effectiveTime": "20201109",
      "moduleId": "51000202101",
      "relationships": [
         {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "170601008",
          "effectiveTime": "20201105",
          "groupId": 0,
          "grouped": false,
          "id": "10020031000202123",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 0,
          "relationshipId": "10020031000202123",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "116680003" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "464001004",
          "effectiveTime": "20200930",
          "groupId": 0,
          "grouped": false,
          "id": "10016261000202129",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 0,
          "relationshipId": "10016261000202129",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "424226004" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "52870002",
          "effectiveTime": "20201028",
          "groupId": 1,
          "grouped": true,
          "id": "10019761000202126",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 0,
          "relationshipId": "10019761000202126",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "363702006" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "464001004",
          "effectiveTime": "20201105",
          "groupId": 1,
          "grouped": true,
          "id": "10020041000202128",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 1,
          "relationshipId": "10020041000202128",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "425391005" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "2546009",
          "effectiveTime": "20201105",
          "groupId": 2,
          "grouped": true,
          "id": "10020051000202125",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 0,
          "relationshipId": "10020051000202125",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "370134009" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "321667001",
          "effectiveTime": "20201105",
          "groupId": 1,
          "grouped": true,
          "id": "10020061000202127",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 1,
          "relationshipId": "10020061000202127",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "405814001" 
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "360152008",
          "effectiveTime": "20201105",
          "groupId": 2,
          "grouped": true,
          "id": "10020071000202120",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 1,
          "relationshipId": "10020071000202120",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "260686004" 
        }

                      ],
"released":false
   }
  ],
"conceptId": "1064961000202108",
"definitionStatusId": "900000000000074008",
"descriptions": [

{
      "acceptabilityMap": {
        "900000000000509007": "PREFERRED"
      },
      "active": true,
      "caseSignificanceId": "900000000000448009",
      "conceptId": "1064961000202108",
      "descriptionId": "10914381000202116",
      "effectiveTime": "20201109",
      "languageCode": "en",
      "moduleId": "51000202101",
      "released": false,
      "term": "Polygraphic monitoring of respiratory parameters (regime/therapy)",
      "typeId": "900000000000003001"
    },

{
      "acceptabilityMap": {
        "61000202103": "PREFERRED"
      },
      "active": true,
      "caseSignificanceId": "900000000000448009",
      "conceptId": "1064961000202108",
      "descriptionId": "11630861000202111",
      "effectiveTime": "20201111",
      "languageCode": "no",
      "moduleId": "51000202101",
      "released": false,
      "term": "Polygrafisk overvÃ¥king av luftveisparametere",
      "typeId": "900000000000013009"
    },
    {
      "acceptabilityMap": {
        "61000202103": "ACCEPTABLE"
      },
      "active": true,
      "caseSignificanceId": "900000000000017005",
      "conceptId": "1064961000202108",
      "descriptionId": "11630871000202119",
      "effectiveTime": "20201112",
      "languageCode": "no",
      "moduleId": "51000202101",
      "released": false,
      "term": "Polygrafisk overvÃ¥king av parametre i det respiratoriske system",
      "typeId": "900000000000013009"
    },
    {
      "acceptabilityMap": {
        "61000202103": "ACCEPTABLE"
      },
      "active": true,
      "caseSignificanceId": "900000000000020002",
      "conceptId": "1064961000202108",
      "descriptionId": "11631021000202116",
      "effectiveTime": "20201112",
      "languageCode": "no",
      "moduleId": "51000202101",
      "released": false,
      "term": "Polygraphic monitoring of respiratory parameters",
      "typeId": "900000000000013009"
    }
  ],
"effectiveTime": "20201109"
  }
}

**Comment by rorydavidson** [comment]
@Tannjorn is there a reason you are trying to use stated relationships considering these have been deprecated in SNOMED CT and should no longer be used?

**Comment by Tannjorn** [comment]
The simple answer - I don't understand what I am doing! I am trying to find out how to use the schema to post concepts using axioms. But I am not finding sufficient documentation. As you can see this is set within the "classAxiom"-object, so I believed I now posted axioms... ???

**Comment by Tannjorn** [comment]
This schema posts and produces a RF2 with axioms that are successfully imported into authoring. (This produces the import file recieved in MSSP-769)

**Comment by kaicode** [comment]
Hi @Tannjorn,

Here is an example request body for creating a concept, using a stated axiom, in the Norwegian extension:
```
{
  "definitionStatus": "PRIMITIVE",
  "active": true,
  "moduleId": "51000202101",
  "descriptions": [
    {
      "active": true,
      "moduleId": "51000202101",
      "type": "FSN",
      "term": "Norwegian Nøkken event (event)",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "conceptId": null,
      "acceptabilityMap": {
        "900000000000509007": "PREFERRED"
      }
    },
    {
      "active": true,
      "moduleId": "51000202101",
      "type": "SYNONYM",
      "term": "Norwegian Nøkken event",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "conceptId": null,
      "acceptabilityMap": {
        "900000000000509007": "PREFERRED"
      }
    },
    {
      "active": true,
      "moduleId": "51000202101",
      "type": "SYNONYM",
      "term": "Norsk Nøkken-arrangement",
      "lang": "no",
      "caseSignificance": "CASE_INSENSITIVE",
      "conceptId": null,
      "acceptabilityMap": {
        "61000202103": "PREFERRED"
      }
    }
  ],
  "relationships": [],
  "classAxioms": [
    {
      "axiomId": "b3f6322c-97b7-4b68-a011-1499dd00a836",
      "definitionStatus": "PRIMITIVE",
      "active": true,
      "moduleId": "51000202101",
      "relationships": [
        {
          "active": true,
          "groupId": 0,
          "target": {
            "conceptId": "272379006",
            "fsn": "Event (event)",
            "definitionStatus": "PRIMITIVE",
            "effectiveTime": "20020131",
            "moduleId": "900000000000207008",
            "active": true
          },
          "type": {
            "conceptId": "116680003",
            "pt": "Is a"
          },
          "moduleId": "51000202101"
        },
        {
          "active": true,
          "groupId": 0,
          "target": {
            "conceptId": "5024000",
            "fsn": "Fresh water (substance)",
            "definitionStatus": "PRIMITIVE",
            "effectiveTime": "20020131",
            "moduleId": "900000000000207008",
            "active": true
          },
          "type": {
            "conceptId": "47429007",
            "pt": "Associated with",
            "fsn": "Associated with (attribute)"
          }
        }
      ]
    }
  ]
}
```
Within the classAxiom relationships the `target` > `conceptId` and `type` > `conceptId` are required, the other fields within `target` and `type` are redundant in this request. Alternatively setting the `destinationId` and `typeId` fields in the relationship object should also work.
The `groupId` sets the grouping of relationships which is used when serialising the model into the owlExpression within the OWL Axiom reference set.

I hope this helps. Just ask if you need anything further.

Kind regards,
Kai

**Comment by kaicode** [comment]
(Please excuse my attempt at referencing scandinavian folklore 😄 )

**Comment by Tannjorn** [comment]
@kaicode :-) thank's that helps a great deal! 
I tried to post my example continuing on you reference to folklore - but found I had to use the actual example.

The issue I now see is that of groupings.

I posted these relationships to our Snowstorm, and @rorydavidson imported the RF2 export of that branch into the MS authoring platform:

"relationships": [
{
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "464001004",
          "effectiveTime": "20201105",
          "groupId": 1,
          "grouped": true,
          "id": "10020041000202128",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 0,
          "relationshipId": "10020041000202128",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "425391005"
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "2546009",
          "effectiveTime": "20201105",
          "groupId": 0,
          "grouped": true,
          "id": "10020051000202125",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 1,
          "relationshipId": "10020051000202125",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "370134009"
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "321667001",
          "effectiveTime": "20201105",
          "groupId": 1,
          "grouped": true,
          "id": "10020061000202127",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 2,
          "relationshipId": "10020061000202127",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "405814001"
        },
        {
          "active": true,
          "characteristicType": "STATED_RELATIONSHIP",
          "characteristicTypeId": "900000000000010007",
          "destinationId": "360152008",
          "effectiveTime": "20201105",
          "groupId": 2,
          "grouped": true,
          "id": "10020071000202120",
          "modifier": "EXISTENTIAL",
          "moduleId": "51000202101",
          "relationshipGroup": 2,
          "relationshipId": "10020071000202120",
          "released": false,
          "sourceId": "1064961000202108",
          "typeId": "260686004"
        }

This actually groups the first two relationships, and the second two. My take is that both groupID and relationshipGroup will set grouping, and if either has a value other than 0, this value is used - regardless of which element is used. But, if both elements have a value the last one posted is used.

But the conclusion is of course also - our implementer has used more elements than needed...
