### ISSUE TITLE
Get all information on all members of a refset

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#182]
Have anyone looked at doing a query to retrieve all (or a series of reletionships) for all memebers of a refset or the output of an ECL?

My thought is that I could use a query that is the concept search in the browser format. And use another function inside this to create the list of concepts to be searched. A script and a backend database could of course do this, but if I could use an inserted query, it would be even better.

And there is a second twist. I would prefer to do this against the FHIR api.

Any input is appreciated.

**Comment by kaicode** [comment]
What are the selection criteria? Is it just that the concepts are members of a reference set? Could an intentional value set be used? e.g. https://snowstorm.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%5E787778008
This is currently limited to the first 10K results in our FHIR API although the whole set can be retrieved using the native Snowstorm API.

What information about each member would you like to retrieve? You mentioned relationships, I'm not sure which FHIR operation would be best suited to this.

**Comment by Tannjorn** [comment]
I'll try to explain a bit more.

The selection criteria will be a reference set, although using an ECL to define the set wouldn't actually make much difference.

But still, I would like to retrieve what I believe is called the normalForm property of all the concepts in the set. Say I have a set consisting of five concepts, I would like for a single request to return both concept ID and normalForm for all five concepts. I guess this can be achived by using a script that uses the $expand function and fhir_vs=ecl... request, then store all returned concept ID's, and request normalForm for all these using the $lookup function and the property=normalForm operator.

But could they be combined in a single request? Illustrated like this:

https://snowstorm.snomedtools.org/fhir/CodeSystem/$lookup?system=http://snomed.info/sct&code=
(ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/^787778008)
&property=normalForm

(A request that isn't correct - I know)

**Comment by danka74** [comment]
I would suggest that you would use your programming language of choice to implement what you've illustrated, e.g. (in pseudo code):

`get('snostorm/fhir/ValueSet/$expand').map(function(x) get('snowstorm/fhir/CodeSystem/$lookup?code=x'))`

**Comment by kaicode** [comment]
I agree with Daniel. I think you'll need a script for this.

There is a Snowstorm native API operation to fetch the modeling for multiple concepts at once, but only if you know the concept id and it doesn't work via FHIR.

**Comment by Tannjorn** [comment]
Thanks, both of you. I will close this issue, as we are now in process of setting this up using FHIR api's in a two step process using code.

**Comment by danka74** [comment]
@Tannjorn , I do similar things not quite but still almost every day, creating small scripts to query using the snowstorm APIs., and I know that Sander Mertens is doing similar stuff. For inspiration, look at the following repos:
https://github.com/danka74/snowstorm-client-test
https://github.com/mertenssander?tab=repositories
