### ISSUE TITLE
API-specs for refsets

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#185]
Hi,

Does anyone have API-specs for posting refset members?

I have two use-cases, currently.

1. To post a list of concepts, all referenced in a single, simple refset. I have no problems posting them one by one, but that would be a looooooooooooong process. I have tried several methods, but most result in errors. Like using "items": [ and listing objects. The only one resulting in acceptance is by simply seperating each object with a "," (comma), but then only the first object is imported. Is it at all possible to import a list of refset members? (I am thinking we might have to use either import RF2 after creating this in the tool, or another script/code to call the API multiple times).

2. To post an intensional refset definition. I assume the definition should be given under "additionalFields". But I do not get the desired reponse. I also find it strange that the referencedComponent should the the ID of the refset, but this I base on my current training in the implementation course.

So the post would be something like this:

{
  "active": true,
  "additionalFields": {
     "definition" = [write ECL here] },
  "effectiveTime": "string",
  "memberId": "string",
  "moduleId": "string",
  "referencedComponentId": "[REFSETID]",
  "refsetId": "[REFSETID]",
  "released": true,
  "releasedEffectiveTime": 0
}

Is there a list of valid additionalFields anywhere?

Regards,
Jørn

**Comment by kaicode** [comment]
Yes, we need new endpoints for bulk creation of refset members. Shouldn't be too hard, just a case of priorities. We have an RFP out to build a new Reference Set management tool. Making the Snowstorm API fit for purpose will be part of that work during next year, if this is not implemented before then.

The `additionalFields` map can only contain fields other than those in the simple refset. Reference set types are currently controlled in Snowstorm using the [Reference Set Types section of the application.properties file](https://github.com/IHTSDO/snowstorm/blob/5.0.8/src/main/resources/application.properties#L129). The fields listed after the last pipe in that configuration file can be used in the `additionalFields` map in the REST API. 

At the current time the intensional reference set is not part of the default configuration. There is also no API mechanism to automatically populate a reference set using an intensional definition, although I believe that would be the correct thing to do. This is on the medium term roadmap for some time this year but pull requests in this area are most welcome!

**Comment by Tannjorn** [comment]
Thanks, I found the  Reference Set Types section of the application.properties file, and now I understand a bit more about how to read it.

I will make requests for both functionalities, actually the support for intensional refsets would be the most urgent, as it is harder for go around.

Just a quick follow up. I tried to post the map using "mapSource" in "additionalFields", and it worked well. The reason for using "mapSource" is that logically the map is in that direction. Is there any reason this wouldn't work? Or do you have any comments on whether to use one or the other? Perhaps always use mapTarget for the external system, and give map specifics in the release notes?

**Comment by kaicode** [comment]
My understanding is that `mapTarget` should always be used for RF2 maps regardless of the direction of the map. This is one of the gotchas when using maps. Yes, the release notes and perhaps the reference set concept description should be used to specify the map direction. 

I recommend that you test as early as you can that Snowstorm can export the reference set members that you are creating and that you have all the expected columns. Only reference sets with `mapTarget` are part of the default configuration. If you are creating your own reference set you may also need to create a concept in the correct area in the hierarchy to represent the refset for export to work as expected.

**Comment by Tannjorn** [comment]
Hi @kaicode

I have continued testing, and you are quite correct - using mapSource as an additional field will not be reflected in the RF2 export. It will be a map-record but with only referenced component, and mapTarget is left empty. MapSource will however be visible in the REST-api, but not in the FHIR-api.

I have some more questions regarding code systems (target/source) for the FHIR api, but I will write this in a separate issue, to make sure others can search it.

Thanks,
Jørn

**Comment by kaicode** [comment]
@Tannjorn thank you for writing up your findings and for creating a separate issue when the discussion changes. Really appreciated. You are setting a fantastic example 😄
