### ISSUE TITLE
snowstorm in docker behind a proxy

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#188]
We are running snowstorm in docker on a server which is behind a proxy. snowstorm does not use the proxy while e.g. wget from within the container uses the proxy. snowstorm works fine except for the dailybuild service.

Docker entrypoint:
java -Xms2g -Xmx4g -jar snowstorm.jar -Dhttp.proxyHost=xxx.xxx.xxx.xxx -Dhttp.proxyPort=xxxx -Dhttps.proxyHost=xxx.xxx.xxx.xxx -Dhttps.proxyPort=xxxx -Dhttp.noProxyHosts="localhost|es" --elasticsearch.urls=http://es:9200 --spring.config.location=/config/application-local.properties

gives the following error:
Error creating bean with name 'dailyBuildService': Invocation of init method failed; nested exception is com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to snomed-dailybuild-xx.s3.amazonaws.com:443 [snomed-dailybuild-xx.s3.amazonaws.com/xxx.xxx.xxx.xxx] failed: connect timed out

From the network logs, snowstorm does not use the proxy.

When running natively (outside of docker) the above java proxy configuration works fine.

Is there some specific way that the aws client needs to/can be configured?

**Comment by danka74** [comment]
Does the aws client need specific proxy configuration? If so, can this be added to application-local.properties?
https://github.com/aws/aws-sdk-java/issues/1534

**Comment by kaicode** [comment]
Have you tried also setting this?
```
-Dhttps.proxySet=true
```
from https://stackoverflow.com/a/36014938/512223

**Comment by danka74** [comment]
Thanks @kaicode ,

I have now... and still the same. The proxy is not used.

**Comment by danka74** [comment]
Solved!

The order of arguments to java is important and the proxy settings need to come before -jar.

So, the correct entry point is:
`java -Xms2g -Xmx4g -Dhttp.proxyHost=xxx.xxx.xxx.xxx -Dhttp.proxyPort=xxxx -Dhttps.proxyHost=xxx.xxx.xxx.xxx -Dhttps.proxyPort=xxxx -Dhttp.noProxyHosts="localhost|es" -jar snowstorm.jar --elasticsearch.urls=http://es:9200 --spring.config.location=/config/application-local.properties`

**Comment by kaicode** [comment]
@danka74 thanks for posting the solution.
