### ISSUE TITLE
On posting descriptions

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#197]
Hi,

Does anyone have a simple way of posting additional descriptions for concepts? I have tried to post a JSON to the updateConcept api (PUT), and put only the addtional description. But this inactivates the concept, relationships and all other descriptions. Effectively I have to set up a request for all elements first, add the one(s) I would like to add, and post the full JSON-body again.

Is there an easier way to merely add a description without touching what is already defined?

**Comment by kaicode** [comment]
Hi @Tannjorn,

When Snowstorm started we took the design decision to always edit a concept in the context of the whole concept. The Authoring Platform UI project works in this way. A whole concept is loaded, component changes are made, then the whole concept is saved. One of the reasons for this is validation. There are validation rules which validate a description against the concept parents. If there is a warning or error to show the concept author being able to see the context of the whole concept helps.

The short answer is no API endpoint to add or edit descriptions without loading the whole concept.

If you are interested in adding descriptions in batch there is bulk import functionality in the [SNOMED Template Service](https://github.com/IHTSDO/snomed-template-service) which may interest you. Use the **POST /{branchPath}/recipes/{recipe}/jobs** function with the [description-create-tsv](https://github.com/IHTSDO/snomed-template-service/blob/master/transformation-recipes/description-create-tsv.json) recipe to perform a batch description import from TSV values, with or without [SNOMED Drools Validation](http://github.com/IHTSDO/snomed-drools).

Kind regards,
Kai Kewley

**Comment by ulsa123** [comment]
Hei Jørn Andre

I postman kan man chaine et get og et post request. Get svaret kan gemmes i en variabel. Variablen kan suppleres med de description attributter, der trenges.

Et eks kan findes på YouTube DToBC12Ztnk

Hilsen Ulrich 
Gott nytår!

Ps skal jeg lave et praktisk eks?

**Comment by Tannjorn** [comment]
Hi @kaicode and @ulsa123 

First of all, thanks for a quick clarification. Prevents me from but wasting time, and increasing frustration.

@ulsa123 , I have created a team in Postman, and will invite you. I am starting to get some ideas on how it works now, also using the FHIR-api's. We can work from there, and possibly share knowledge and experience a bit down the road. I will send you an invite so that we can explore examples together.

And @kaicode, I will be sure to take a look at the template service. But for now this had two use-cases. One to post a few descriptions into a test-environment to verify FHIR-api integration. And second to learn more about the inner workings of Snowstorm.

Thanks,
Jørn
