### ISSUE TITLE
Source and target code system in FHIR map API

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#198]
When looking up mappings in the FHIR api, both source and target systems are required fields. I can see nowhere these are referred in the actual map (produced in SNOMED CT), and there does not appear to any lookup functionality to see whether these are actual valid codes in either the source or target systems. I can tell this because I have tried using using snomed.info as target reference for a GUID-based ID used in our national medicines terminology.

The issue is - valid target systems appear to be restricted to SNOMED, ICD-10 and a few more. I am not allowed to state my own target system, referring to our national terminology - which has a valid URI.

Two questions:
- Could be disable the requirement for specific (predefined) code systems as target?
- Is there a config-file where I can set our national medicines terminology as a valid code system?

Kind regards,
Jørn

**Comment by pgwilliams** [comment]
Hi Jørn, yes that sounds like a great use case.   I'll raise a ticket to get these changes made.

Is your map loaded as an RF2 file into your Snowstorm server?   Potentially I could not worry about the target code system at all (assuming the concept representing the map exists) and just return the contents of the mapTarget column.    

No, unfortunately the list of allowed target CodeSystems is currently hard coded, see: https://github.com/IHTSDO/snowstorm/blob/master/src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptMapProvider.java#L131

I tried using the SNOMED URI as both source and target but I see the refset is detected as being related to the ICD-10 CodeSystem and an error raise.   If you use your own map SCTID, what do you see?

https://<your-server>/fhir/ConceptMap/$translate?code=<some mapped concept SCTID>&system=http://snomed.info/sct&source=http://snomed.info/sct?fhir_vs&target=http://snomed.info/sct?fhir_vs&url=http://snomed.info/sct?fhir_cm=<your map SCTID>

**Comment by Tannjorn** [comment]
Hi Peter,

Thanks.

I have not loaded my map as an RF2, I have manually posted JSONs in the swagger UI (so far). You can view it here: https://test.terminologi.ehelse.no/swagger-ui.html#!/Refset_Members/findBrowserReferenceSetMembersWithAggregationsUsingGET, searching MAIN/SNOMEDCT-NO for the refset 6021000202106.

In this wou can also see how it will look when posting a map using "mapSource". (NB! This will be overwritten by Dailybuild sometime tonight). (And I have the RF2 export if this is of interest).


Trying to query the ICD-10 complex map refset using snomed.info as target system gives me the same error as you mention. But querying my posted refset I get no error wether I use snomed.info or http://hl7.org/fhir/sid/icd-10 as target. It seems to disregard this all together. This could be because 447562003 is already hardcoded as a known Uri map? My mapset is not set in any way.


I am able to disregard the code system reference, but in the issue is that the FHIR-api returns the code system in a way that could be misleading for external users. But nothing that can't be bypassed by a good implementation guide.



Kind regards,
Jørn

**Comment by pgwilliams** [comment]
Tracking internally as MAINT-1566 - "Allow unrecognised target code system if map concept supplied"

**Comment by kaicode** [comment]
This is working in the current version of Snowstorm
https://snowstorm.ihtsdotools.org/fhir/ConceptMap/$translate?code=48661000&system=http://snomed.info/sct&targetsystem=http://hl7.org/fhir/sid/icd-10

A few known FHIR implicit maps have been added to the [default configuration](https://github.com/IHTSDO/snowstorm/blob/8.3.0/src/main/resources/application.properties#L274).
More implicit maps can be added to your Snowstorm instance by adding more `fhir.conceptmap.snomed-implicit` to your configuration. 

Any National Edition wanting to add their implicit maps to Snowstorm's default configuration are welcome to raise an issue or pull request for this. I really hope that this metadata can be moved into the SNOMED CT content using annotations in the near future. Less tooling configuration is only a good thing!
