### ISSUE TITLE
Finding concepts within Indian Refset

### ISSUE THREAD

**Issue by tacack** [IHTSDO/snowstorm#20]
Hello,

I had an issue earlier with my SNOMED API server and I just upgraded to SNOW STORM and I am using the 2017-09-01 version of the SNOMED taxonomy. 

I am trying to use the Refsets that were published by India -> https://mlds.ihtsdotools.org/#/viewReleases/viewRelease/194856 and search for concepts within the refset.

I tried using the inbuilt swagger API in snowstorm to search for refsetmembers under the Neurosurgeory refset that was published but I'm still seeing 0 results. 

<img width="1172" alt="screen shot 2019-01-04 at 7 34 20 pm" src="https://user-images.githubusercontent.com/6650162/50691815-e152a600-1057-11e9-9062-5f5d846a4f71.png">
<img width="1118" alt="screen shot 2019-01-04 at 7 34 29 pm" src="https://user-images.githubusercontent.com/6650162/50691819-e3b50000-1057-11e9-849e-0105019e33aa.png">

Am I doing something wrong? Are there any other steps that I need to do to access a refset's members? 

Regards,
Vybhav

**Comment by kaicode** [comment]
Hi @tacack, welcome to the Snowstorm community!

Snowstorm does not come with any content. You will need to import the SNOMED CT International Edition before importing the India reference set extension package.

Here are [instructions for loading the Spanish translation](https://confluence.ihtsdotools.org/display/DEV/Exercise+%231#Exercise#1-StartingSnowstorm) which should also work for loading the India extension.

Let us know if you get stuck.
Cheers, Kai

**Comment by tacack** [comment]
Ah. I did load the SNOMED CT International edition, but I didn't import the inda reference set extension package. Maybe that's the step I was missing.

I will try and revert.

THank you.

Regards,
Vybhav

**Comment by tacack** [comment]
This worked! Thank you so much @kaicode !

What's the best way to search for a concept within a refset based on description? In the old SNOMED API that I was using -> https://snomedctsnapshotapi.docs.apiary.io/#reference/concepts/search/search-descriptions , there was a field to indicate the refsetID to search within, but I don't see a similar API structure when I check the search API for SNOWSTORM

<img width="1112" alt="screen shot 2019-01-05 at 9 28 22 am" src="https://user-images.githubusercontent.com/6650162/50720079-59f34a00-10cc-11e9-856a-d1a47309174a.png">

Again, thank you for your help!
Vybhav

**Comment by tacack** [comment]
Is the only way to do this using ECL?

**Comment by kaicode** [comment]
Yes, ECL is the only way to do this in the Snowstorm API.
Using `eclFilter=^SOME-REFSET-ID` and `termFilter`.

**Comment by tacack** [comment]
Thanks @kaicode . That helps.
