### ISSUE TITLE
Badly-generated API definition

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [IHTSDO/snowstorm#204]
The JSON specification for the API makes reference to a "Set" definition, which is not present in `#/definitions` (example in excerpt, below), meaning Client SDK generators do not produce compileable TypeScript (and likely other languages in which `Set` is a primitive or otherwise common type.

```json
		"Description": {
			"type": "object",
			"properties": {
				"acceptabilityMap": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"acceptabilityMapFromLangRefsetMembers": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"active": {
					"type": "boolean"
				},
				"associationTargets": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/Set"
					}
				},
				...
```

**Comment by evergreen-lee-campbell** [comment]
I've done some digging, and this is actually a problem with Springfox. I'm currently investigating whether a simple version upgrade does the trick...

**Comment by evergreen-lee-campbell** [comment]
It does, but there are some breaking changes. I've raised the following pull request: https://github.com/IHTSDO/snowstorm/pull/205

**Comment by kaicode** [comment]
Closing as the PR was tested for some time but finally we chose not to pursue the upgrade. Further explanation on the PR.
