### ISSUE TITLE
Invalid character found in the request target

### ISSUE THREAD

**Issue by steve1973** [IHTSDO/snowstorm#207]
Since upgrading to v5.x of Snowstorm, along with ES 7.x I've started getting the above error when using the pipe character unencoded, e.g. `/MAIN/SNOMEDCT-UKC/concepts?ecl=<<250637003|Plasma alanine aminotransferase level|&limit=1000`. I appreciate encoding it will resolve the issue, but v4.x didn't require this. Also, SnowstormApplication.java still sets the property, `System.setProperty("tomcat.util.http.parser.HttpParser.requestTargetAllow", "{}|"); // Allow these unencoded characters in URL (used in ECL)` in v5.x of Snowstorm. Is the only option now to encode these characters before making the request or is there a property I can set somewhere to allow certain unencoded characters?

Many thanks

**Comment by kaicode** [comment]
Hi @steve1973 thanks for pointing this out. 

It seems in Tomcat 9 the `requestTargetAllow` option can no longer be set via system properties but it looks like it is available in the [Spring Boot configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server.tomcat.relaxed-query-chars). 

Please create an `application.properties` file and add this configuration:
```
server.tomcat.relaxed-query-chars={,},|
```
That will allow the request you quoted to complete successfully.

I will add this change in the next release.

Kind regards,
Kai Kewley

**Comment by steve1973** [comment]
Thanks Kai, that's great.
