### ISSUE TITLE
How can I get procedures from Snowstorm

### ISSUE THREAD

**Issue by kandascan** [IHTSDO/snowstorm#208]
Hi everyone,

I loaded zip date to Snowstorm and start ElasticSearch api, the question what I have is:
how can I get this data: https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-IE/2020-10-21/concepts/404684003/children?form=stated
this is the list of procedures from Snowstorm api ?
when I go to localhost:8080 I see swagger UI but cannot found correct endpoint, can you help me?

Lot of thanks.

Best regards,
Boguslaw

**Comment by kaicode** [comment]
Hi,
I wouldn't use the URL you have given. It will only return concepts with a specific requirement - these are concepts that have been modeled as direct children of the concept _404684003 | Clinical finding (finding) |_ when using the stated form so it may not match all clinical findings.

If you would like to fetch all procedure concepts I would recommend using a simple [ECL query](https://confluence.ihtsdotools.org/display/DOCECL/6.1+Simple+Expression+Constraints). These ECL queries will fetch all types of clinical finding or procedure respectively:
- `<404684003 | Clinical finding (finding) |`
- `<71388002 | Procedure (procedure) |`

I would use the find concepts endpoint for this which should be in your local swagger [here](http://localhost:8080/swagger-ui.html#!/Concepts/findConceptsUsingGET). Use the ecl parameter and increase the limit to something like 1000 to grab a good size page at a time like this: http://localhost:8080/MAIN/concepts?ecl=%3C404684003&offset=0&limit=1000

You can find the `searchAfter` token at the bottom of the page, for example `WzE1OTcyNDYxMDAwMTE5MTAxXQ==`. This is a hash of the id of the last result in the page. Use that token as the `searchAfter` parameter in the next request to load the next page. This is the only way to scroll through more than 10,000 results in Snowstorm. There are something like 115,537 descendants of Clinical Finding in the July 2020 release so you will probably need to use this technique this to fetch them all.

Kind regards,
Kai Kewley

**Comment by kandascan** [comment]
Hi Kai,

thanks for your respons, but it seems I missed something with configuration, I didn't have MAIN branch.
![image](https://user-images.githubusercontent.com/15519926/104915151-836c2f00-5990-11eb-898c-afeb537c91bf.png)

can you tell me how can I create it in proper way?

Thanks
Boguslaw Boczkowski

**Comment by kandascan** [comment]
ok I find the problem it was missed /browser/ before MAIN in url

**Comment by kaicode** [comment]
Please note that the endpoint with the format _/browser/{branch}/concepts_ completely ignores the `ecl` parameter. 
The response from this endpoint shows that a total of 34 concepts is returned which means there are only 34 concepts on the MAIN branch in your installation. This is probably why when using the correct endpoint (without the _/browser_ part) the query is not finding the Clinical finding concept.

I would recommend deleting your Elasticsearch indices and importing again starting with the International Edition RF2 snapshot which will take at least 20 minutes to import. See [Loading SNOMED documentation](https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md#command-line). If you would like to load extension content that should be loaded after the International Edition, see [Loading and Updating Extensions](https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md).

I hope that helps,
Kai Kewley

**Comment by kandascan** [comment]
Hi Kai,

thanks for youur assists but it seems like something went wrong with importing data.
![image](https://user-images.githubusercontent.com/15519926/105019112-07342300-5a46-11eb-9c04-7e2f835938e3.png)
Please take a look at the exepction I got and at the bottom the command I runned. I also runned elastic search during this import process.
![image](https://user-images.githubusercontent.com/15519926/105019329-44001a00-5a46-11eb-9c33-68f241e5b7da.png)
Any suggestion what I did wrong?

Best regards,
Boguslaw Boczkowski

**Comment by kandascan** [comment]
ok I manually deleted the indices from data folder in Elasticsearch and this command for loading indices start working, but it only took me only 3minutes insted of 20mins. 
![image](https://user-images.githubusercontent.com/15519926/105021450-d5708b80-5a48-11eb-95e3-c69efc5b7ced.png)
it is because I have wrong zip file ?

**Comment by kaicode** [comment]
Hi @kandascan,

I can see the October 2020 IE extension RF2 archive in the screenshot which is about 67Mb. This file depends on the July 2020 International Edition RF2 archive which is about 470Mb. The International Edition snapshot import must be loaded first. Please read the documentation that I previously shared: https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md

Kind regards,
Kai Kewley

**Comment by kandascan** [comment]
ok it seems like we I don't have a correct file which contains 470Mb. Can you provide me the path url where I can get this file, or I need do request to someone else?

Kind regards,
Boguslaw Boczkowski

**Comment by kaicode** [comment]
Member countries should seek advice from their SNOMED CT National Release Centre about how to get access to the RF2 archives. 

The Irish NRC is https://www.ehealthireland.ie/ , the most relevant page seems to be [this](https://www.ehealthireland.ie/Our-Team/Enterprise-Architecture/SNOMED%20CT/).

**Comment by kaicode** [comment]
Member countries should seek advice from their SNOMED CT National Release Centre about how to get access to the RF2 archives. 

The Irish NRC is https://www.ehealthireland.ie/ , the most relevant page seems to be [this](https://www.ehealthireland.ie/Our-Team/Enterprise-Architecture/SNOMED%20CT/).

**Comment by kandascan** [comment]
Thanks Kai, this resolved me issue.
