### ISSUE TITLE
GET /browser/{branch}/concepts/{conceptId} returning British descriptions

### ISSUE THREAD

**Issue by alihussein96** [IHTSDO/snowstorm#216]
Hello everyone, 

I am currently using the following endpoint: `/browser/{branch}/concepts/{conceptId}` to return descriptions for certain conceptIds. 

This is my request url call:
`http://localhost:9011/browser/MAIN/concepts/428383000`

This is the response: 
```{
  "conceptId": "428383000",
  "fsn": {
    "term": "Anemia caused by medication (disorder)",
    "lang": "en"
  },
  "pt": {
    "term": "Anemia due to medication",
    "lang": "en"
  },
  "active": true,
  "effectiveTime": "20080131",
  "released": true,
  "releasedEffectiveTime": 20080131,
  "moduleId": "900000000000207008",
  "definitionStatus": "FULLY_DEFINED",
  "descriptions": [
    {
      "active": true,
      "released": true,
      "releasedEffectiveTime": 20170731,
      "descriptionId": "3036509011",
      "term": "Drug induced anaemia",
      "conceptId": "428383000",
      "moduleId": "900000000000207008",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "900000000000508004": "ACCEPTABLE"
      },
      "type": "SYNONYM",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "effectiveTime": "20170731"
    },
    {
      "active": true,
      "released": true,
      "releasedEffectiveTime": 20170731,
      "descriptionId": "3292898016",
      "term": "Anaemia caused by medication",
      "conceptId": "428383000",
      "moduleId": "900000000000207008",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "900000000000508004": "ACCEPTABLE"
      },
      "type": "SYNONYM",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "effectiveTime": "20170731"
    },
    {
      "active": false,
      "released": true,
      "releasedEffectiveTime": 20160131,
      "descriptionId": "2690943012",
      "term": "Anemia due to medication (disorder)",
      "conceptId": "428383000",
      "moduleId": "900000000000207008",
      "typeId": "900000000000003001",
      "acceptabilityMap": {},
      "type": "FSN",
      "lang": "en",
      "caseSignificance": "INITIAL_CHARACTER_CASE_INSENSITIVE",
      "effectiveTime": "20160131"
    },
    {
      "active": true,
      "released": true,
      "releasedEffectiveTime": 20170731,
      "descriptionId": "2694501018",
      "term": "Anemia due to medication",
      "conceptId": "428383000",
      "moduleId": "900000000000207008",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "900000000000509007": "PREFERRED"
      },
      "type": "SYNONYM",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "effectiveTime": "20170731"
    },
...
   ```

Notice that i am getting results with description terms having terms such as "Drug induced anaemia". Anaemia is the British term whereas Anemia is the US term. How do i modify my call so that it returns descriptions with only US description terms, if possible. I noticed that the description endpoint has a language param but it does not accept a conceptId. (I want descriptions only for specified conceptIds so it will be great if this endpoint that I am using can work) 

Edit: I am running snowstorm version 5.1.0

**Comment by kaicode** [comment]
Hi @alihussein96, 
The International Edition includes both US and GB terms. 

The browser endpoint you are using always returns all descriptions of a concept which exist in the edition/extension which is loaded onto that branch.

Acceptability information for each description is included in the response. 
In your example the first description returned is indeed a British term, this is shown by the language reference set information in the acceptability map:
```
"descriptions": [
    {
      "active": true,
      "released": true,
      "releasedEffectiveTime": 20170731,
      "descriptionId": "3036509011",
      "term": "Drug induced anaemia",
      "conceptId": "428383000",
      "moduleId": "900000000000207008",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "900000000000508004": "ACCEPTABLE"
      },
      "type": "SYNONYM",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "effectiveTime": "20170731"
    },
```
The GB language reference (`900000000000508004 | Great Britain English language reference set (foundation metadata concept) |`) has the term as `ACCEPTABLE`, but there is no entry against that description for the US language refset (`900000000000509007 | United States of America English language reference set (foundation metadata concept) |`).

Yes the description search could be used to fetch only the descriptions which are preferred or acceptable in the US language refset. Although there is no `conceptId` field the `term` field can actually be used to filter by conceptId. For example:
[/browser/MAIN/2021-01-31/descriptions?term=428383000&preferredOrAcceptableIn=900000000000509007](https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2021-01-31/descriptions?term=428383000&preferredOrAcceptableIn=900000000000509007)

I hope that helps.
Kai Kewley

**Comment by alihussein96** [comment]
thank you. your answer was super helpful and solved my issue. I filtered all descriptions that are not within the 900000000000509007 us ref code and now i am getting the correct descriptions. THANK YOU again!
