### ISSUE TITLE
ClassNotFoundException error when trying to start the server, using self built jar

### ISSUE THREAD

**Issue by MaToFin** [IHTSDO/snowstorm#229]
Help,
I'm very new to snowstorm and I can't figure this error message:

`C:\Projects\snowstorm>java -Xms2g -Xmx4g -jar target/snowstorm-6.0.3.jar --delete-indices --import=Z:\SnomedCT_InternationalRF2_PRODUCTION_20210131T120000Z.zip
Exception in thread "main" java.lang.ClassNotFoundException: org.snomed.snowstorm.SnowstormApplication
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)`

this also happens when I'm trying to start it in read only mode.
I'm using the new 6.0.3 version, did the building with maven using your pom.xml file and started the elasticsearch.
Any help is very much appreciated.

**Comment by kaicode** [comment]
Hi @MaToFin, thanks for getting in touch.

You are running a jar in the target directory so it looks like you may have built your own jar?

The questions that spring to mind are: What command did you use to build the jar and did it complete successfully? What Java version are you running (`java -version`)?

An alternative is to download the pre-built jar from the bottom of the [latest release page](https://github.com/IHTSDO/snowstorm/releases/latest). This should just work on Java 8 or 11.

I hope that helps!

**Comment by MaToFin** [comment]
I made a directory where I downloaded the latest pre-built jar and the pom.xml file and ran "mvn clean package". The script ran without errors and ended with a big green text "BUILD SUCCESS".  After that I started the elasticsearch and ran the above command causing the mentioned error. I'm currently running:
java -version:

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode). 

Thanks for quick response.

**Comment by kaicode** [comment]
@MaToFin if you would just like to run snowstorm you can download the prebuilt jar and run that.

If you would like to build the source code you will need to clone/download the whole repository and build that. 
Building just the pom.xml file will pull in the dependant libraries but the jar file will not contain any of the snowstorm java classes. I think that it the issue you are facing.

**Comment by MaToFin** [comment]
Oh, yes. Now I got it. Cheers for your help, it was my stupidity that was on the way. Now that I just ran the pre-built jar file after starting the elasticsearch I got it to work. Sorry for wasting your time but atleast you got a happy user now :D

**Comment by kaicode** [comment]
Thanks for reporting that it's working for you now!
We love happy users 🥳
