### ISSUE TITLE
 SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing

### ISSUE THREAD

**Issue by X-Raph-X** [IHTSDO/snowstorm#244]
Good morning,
I need your help because despite that the name of my Snowstorm server is very cool, its name is Olaf, i can not load Snomed CT into Snowstorm because I have the same error that in the issue #158 . And it is not an energy saving problem and no docker have been using.

My configuration :

- Dedicated Linux/Debian Virtual Machine hosted by KVM hypervisor that use a Xeon CPU
- 4 vCPUS and 8Go of memory
- No disk full during the loading
- SnowStorm V6.0.3
- Elasticsearch V7.7.0 was installed using Debian packages
- Snomed CT releases files come from NHS (UK).

When I try to load the release file, in a tmux session to avoid connexion or energy saving problem, it crashes with an error always at the same step after 50 minutes of running : 

```
2021-03-13 15:11:26.387  INFO 12771 --- [           main] o.s.o.o.taxonomy.AxiomDeserialiser       : Deserialised  710 000 axioms...
2021-03-13 15:11:26.618  INFO 12771 --- [           main] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Update graph using axioms of concepts with changed modelling. took 36.663 seconds
2021-03-13 15:11:28.610  INFO 12771 --- [           main] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Collect existingDescendants from QueryConcept. took 1.992 seconds
2021-03-13 15:11:31.935  INFO 12771 --- [           main] i.k.elasticvc.api.ComponentService       : Saving batch of 10000 QueryConcepts
2021-03-13 15:12:04.193 ERROR 12771 --- [           main] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN. ID 44eda9d9-0e26-4966-b4c1-405061d6c386

org.springframework.dao.DataAccessResourceFailureException: 30 000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]; nested exception is java.lang.RuntimeException: 30 000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
```

It seems this error is linked with http protocol but no process was listening on the http port during the execution of the import task :

```
raphael@olaf:~$ sudo ss -lnlapute
[sudo] Mot de passe de raphael : 
Netid    State     Recv-Q     Send-Q              Local Address:Port                Peer Address:Port                                                                                                              
udp      UNCONN    0          0                         0.0.0.0:68                       0.0.0.0:*         users:(("dhclient",pid=486,fd=7)) ino:16168 sk:1 <->                                                    
tcp      LISTEN    0          128                       0.0.0.0:22                       0.0.0.0:*         users:(("sshd",pid=502,fd=3)) ino:16760 sk:4 <->                                                        
tcp      ESTAB     0          0                    192.168.1.40:22                 192.168.1.142:58304     users:(("sshd",pid=2030,fd=3),("sshd",pid=2011,fd=3)) timer:(keepalive,89min,0) ino:1762811 sk:5 <->    
tcp      LISTEN    0          100                             *:8080                           *:*         users:(("java",pid=2878,fd=30)) uid:1000 ino:2067348 sk:11 v6only:0 <->                                 
tcp      LISTEN    0          128            [::ffff:127.0.0.1]:9200                           *:*         users:(("java",pid=2466,fd=283)) uid:106 ino:2145775 sk:8 v6only:0 <->                                  
tcp      LISTEN    0          128                         [::1]:9200                        [::]:*         users:(("java",pid=2466,fd=281)) uid:106 ino:2145774 sk:9 v6only:1 <->                                  
tcp      LISTEN    0          128            [::ffff:127.0.0.1]:9300                           *:*         users:(("java",pid=2466,fd=255)) uid:106 ino:2145752 sk:a v6only:0 <->                                  
tcp      LISTEN    0          128                         [::1]:9300                        [::]:*         users:(("java",pid=2466,fd=254)) uid:106 ino:2145744 sk:b v6only:1 <->                                  
tcp      LISTEN    0          128                          [::]:22                          [::]:*         users:(("sshd",pid=502,fd=4)) ino:14851 sk:7 v6only:1 <->                                               
tcp      ESTAB     0          0              [::ffff:127.0.0.1]:47190         [::ffff:127.0.0.1]:9200      users:(("java",pid=2878,fd=29)) uid:1000 ino:2157416 sk:d <->                                           
tcp      ESTAB     0          0              [::ffff:127.0.0.1]:9200          [::ffff:127.0.0.1]:47190     users:(("java",pid=2466,fd=285)) timer:(keepalive,118min,0) uid:106 ino:2067346 sk:10 <-> 
```

I'am a newbie about elesticsearch, perhaps the configuration is not correct...
The complete log is attached to this message. 
[snowstorm.log](https://github.com/IHTSDO/snowstorm/files/6155006/snowstorm.log)

Thank you for your help.

_Originally posted by @X-Raph-X in https://github.com/IHTSDO/snowstorm/issues/158#issuecomment-800917993_

**Comment by kaicode** [comment]
Hi @X-Raph-X and Olaf the Snowstorm server,

Olaf's log shows that he imports all the content from the RF2 files correctly and then quickly melts when attempting to save the first batch of entries in the semantic index (used for querying) `Saving batch of 10000 QueryConcepts`. 

The Elasticsearch service takes longer than 30 seconds to persist the batch which results in the timeout. There are a few ways to address this.. I'll assume making the Elasticsearch service faster is not an option which leaves making the batches smaller or increasing the timeout. I would not recommend changing the timeout because it may mask other issues. 

The bulk document saving batch size can be adjusted using the `elasticvc.save.batch-size` configuration option. This option [defaults to 10000](https://github.com/kaicode/elasticvc/blob/master/src/main/java/io/kaicode/elasticvc/api/ComponentService.java#L31) but can be [configured in the usual way](https://github.com/IHTSDO/snowstorm/blob/master/docs/configuration-guide.md#override-the-default). Try something like: `elasticvc.save.batch-size=1000`. This batch size should allow your Elasticsearch service to consume the batch within 30 seconds so the import completes.

<img width="500" alt="Screenshot 2021-03-17 at 11 08 09" src="https://user-images.githubusercontent.com/2010517/111458192-10bdcc80-8711-11eb-817e-ff58cbdb426f.png">

I hope that helps!

Kai Kewley

**Comment by X-Raph-X** [comment]
Thank you Kai for your answer and nice picture :-) . I've already tried using `elasticvc.save.batch-size=1000` without success. This afternoon, i've tried using the curl method and it has worked.
Now my problem is that `sct-browser-frontend` is unable to join my snowstorm server. I think it is a problem with my nginx configuration. But this is not your concern, I'am going to disturb  `sct-browser-frontend` contributors if I can't find the solution by myself... 

Thanks for your help.

**Comment by X-Raph-X** [comment]
My nginx configuration is fixed ! The browser and the terminology service are working together.

**Comment by kaicode** [comment]
Congrats! 😄
