### ISSUE TITLE
ECL modifying the 'limit' number and navigation

### ISSUE THREAD

**Issue by albamoralest** [IHTSDO/snowstorm#249]
Hi!

I am using ECL to query all the concepts that have the same attribute type and value (and subtypes). Some concepts have more than 50 results and when I execute the ECL query it only returns the first 50. 
Is it possible to change the limit? Not sure how to navigate to the other 26 results.
The query: < 16114001|Fracture of ankle (disorder)|: << 116676008|Associated morphology (attribute)| = << 72704001|Fracture (morphologic abnormality)| and << 363698007|Finding site (attribute)| = << 33696004|Bone structure of ankle (body structure)|

using the api
http://localhost:8080/MAIN/concepts?ecl=%3C%2016114001%7CFracture%20of%20ankle%20(disorder)%7C%3A%20%3C%3C%20116676008%7CAssociated%20morphology%20(attribute)%7C%20%3D%20%3C%3C%2072704001%7CFracture%20(morphologic%20abnormality)%7C%20and%20%3C%3C%20363698007%7CFinding%20site%20(attribute)%7C%20%3D%20%3C%3C%2033696004%7CBone%20structure%20of%20ankle%20(body%20structure)%7C

Thank you!

**Comment by kaicode** [comment]
Hi. Yes, there is a `limit` parameter. Add `&limit=1000` to the end of your request URL to get the first thousand results.
Use the Swagger interface to see all the available parameters for each endpoint.
- Swagger on the public server (concept search function) https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/swagger-ui.html#!/Concepts/findConceptsUsingGET
- Swagger on a localhost server - http://localhost:8080

Cheers.
