### ISSUE TITLE
Moduleid question

### ISSUE THREAD

**Issue by hurtigcodes** [IHTSDO/snowstorm#260]
I'm trying to understand simple POSTs on the /browser/{branch}/concepts endpoint. 

Snowstorm will convert to OWL expression, and will use the first moduleId under classAxioms for all relationships in the OWL expression. The moduleId under target and type I understand, where Snowstorm populates the concepts with descriptions during the POST.

But what does the second moduleId refer to? 

```json
  "classAxioms" : [ {
      "axiomId" : "e20f6557-0c82-4a7e-98e0-bd5724e714c0",
      **"moduleId" : "900000000000207008",**
      "active" : true,
      "released" : true,
      "definitionStatusId" : "900000000000073002",
      "relationships" : [ {
        "active" : true,
        **"moduleId" : "900000000000207008",**
        "released" : false,
        "sourceId" : "182555002",
        "destinationId" : "360030002",
        "typeId" : "116680003",
        "type" : {
          "conceptId" : "116680003",
          "definitionStatus" : "PRIMITIVE",
          **"moduleId" : "900000000000012004",**
          "fsn" : {
            "term" : "Is a (attribute)",
            "lang" : "en"
          },
          "pt" : {
            "term" : "Is a",
            "lang" : "en"
          },
          "id" : "116680003"
        },
        "target" : {
          "conceptId" : "360030002",
          "definitionStatus" : "FULLY_DEFINED",
          **"moduleId" : "900000000000207008",**
          "fsn" : {
            "term" : "Application of device (procedure)",
            "lang" : "en"
          },
          "pt" : {
            "term" : "Application of device",
            "lang" : "en"
          },
          "id" : "360030002"
        },
        "groupId" : 0,
        "characteristicType" : "STATED_RELATIONSHIP",
        "modifier" : "EXISTENTIAL"
      },
```

**Comment by kaicode** [comment]
Hi @hurtigcodes, good question!

The `classAxioms[].relationships[]. moduleId` field is a hangover from authoring using stated relationships, before we had OWL axioms in RF2. We kept the same relationship format to minimise work in the Authoring UI project. This field is completely redundant and defaults to `900000000000207008 | SNOMED CT core module (core metadata concept) |` which may be misleading.

This field should probably be taken out to avoid confusion in the future.

**Comment by hurtigcodes** [comment]
I understand. We will put together some documentation and comments for questions like these, to pay back the community. Thanks!
