### ISSUE TITLE
Im having this issue currently on an UBUNTU 20.04 LTS. I have 16GB memory and I don't think its a memory issue. What could be wrong??

### ISSUE THREAD

**Issue by olamide226** [IHTSDO/snowstorm#268]
Im having this issue currently on an UBUNTU 20.04 LTS. I have 16GB memory and I don't think its a memory issue. What could be wrong??

_Originally posted by @olamide226 in https://github.com/IHTSDO/snowstorm/issues/93#issuecomment-842465616_

**Comment by rorydavidson** [comment]
Hi @olamide226 could you please send any startup logs so that we can have a look?

**Comment by olamide226** [comment]
$~: ```docker-compose up -d ```
Creating elasticsearch ... done

ERROR: for snowstorm  Container "b527af741cd6" is unhealthy.
ERROR: Encountered errors while bringing up the project.


All I do is run docker compose. If you have any idea where I can check for extra logs, I'd appreciate that

**Comment by rorydavidson** [comment]
Is this on an separate Ubuntu server or running under the Windows Linux Subsystem?

**Comment by olamide226** [comment]
Its on a separate Ubuntu server with 16GB of RAM

**Comment by rorydavidson** [comment]
The issue might be with Docker itself. Have you had a look in those logs (usually under /var/log)?

**Comment by olamide226** [comment]
I have checked docker logs and nothing seem to point to anything.

**Comment by rorydavidson** [comment]
I just tried and got the same error. You can look in the docker container logs by typing the following:
`docker logs b527af741cd6 `

In there, I suspect that you will see the following:
```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/snowstorm-cluster.log
```

Doing some searching around Google I found this is a common issue, but if you run the following command (in each session)
`sudo sysctl -w vm.max_map_count=262144` , it will then run.

**Comment by olamide226** [comment]
Hmmmm.... It appears to have worked now after following your steps. Do you
happen to understand the root cause of the problem? So other people can
maybe prevent it in the future.

**Comment by rorydavidson** [comment]
It is due to default virtual memory limits set by operating systems which is now too low for Elasticsearch. See - https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

We will update the documentation to reflect this.

**Comment by olamide226** [comment]
Thanks @rorydavidson . You've been of great help!!

**Comment by olamide226** [comment]
Issue resolved
