### ISSUE TITLE
Timeout when importing to a Azure AKS Cluster

### ISSUE THREAD

**Issue by Eneuman** [IHTSDO/snowstorm#277]
Hi

I'm receving a timeout when trying to import the latest Snapshoot in a clean Snowstorm installation.
I have tried to lower the batch count but it always fail in the exact same step

Is there a way to increase the 30,000 milliseconds timeout for http-outgoing connection (for debuging purpose)?

` 
│ 2021-06-04 06:53:13.184  INFO 1 --- [pool-2-thread-1] o.s.o.o.taxonomy.AxiomDeserialiser       : Deserialised  700,000 axioms...                                                                                                                                       ││ 2021-06-04 06:53:14.496  INFO 1 --- [pool-2-thread-1] o.s.o.o.taxonomy.AxiomDeserialiser       : Deserialised  710,000 axioms...                                                                                                                                       
││ 2021-06-04 06:53:14.993  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Update graph using axioms of concepts with changed modelling. took 39.565 seconds                                                              
││ 2021-06-04 06:53:17.291  INFO 1 --- [pool-2-thread-1] o.snomed.snowstorm.core.util.TimerUtil   : Timer TC index stated: Collect existingDescendants from QueryConcept. took 2.298 seconds                                                                             
││ 2021-06-04 06:53:25.657  INFO 1 --- [pool-2-thread-1] o.s.s.c.d.s.SemanticIndexUpdateService   : Semantic index change summary for stated form: 414532 concepts loaded into the graph. 414532 semantic concepts created including QueryConcept{conceptIdForm=729302008 
││ 2021-06-04 06:53:25.661  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 QueryConcepts 
2021-06-04 06:53:25.661  INFO 1 --- [pool-2-thread-1] i.k.elasticvc.api.ComponentService       : Saving batch of 5000 QueryConcepts                                                                                                                                    

││ 2021-06-04 06:53:55.885 ERROR 1 --- [pool-2-thread-1] o.s.s.core.rf2.rf2import.ImportService   : Failed RF2 SNAPSHOT import on branch MAIN. ID a958d251-1f96-4fec-afbf-d1d71fbe44ba                                                                                    
││ org.springframework.dao.DataAccessResourceFailureException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]; nested exception is java.lang.RuntimeException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]                     
││     at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:76)                                                                                                             
││     at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:398)                                                                                                                                    
││     at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:381)                                                                                                                                               
││     at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.doBulkOperationOnSingleIndex(ElasticsearchRestTemplate.java:245)                                                                                                                          
││     at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.doBulkOperation(ElasticsearchRestTemplate.java:252)                                                                                                                                       
││     at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.bulkIndex(ElasticsearchRestTemplate.java:198)                                                                                                                                             
││     at org.springframework.data.elasticsearch.core.DocumentOperations.bulkIndex(DocumentOperations.java:152)                                                                                                                                                           
││     at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.save(AbstractElasticsearchTemplate.java:175)                                                                                                                                          
││     at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.saveAll(AbstractElasticsearchRepository.java:211)                                                                                                                     
││     at jdk.internal.reflect.GeneratedMethodAccessor247.invoke(Unknown Source)`

**Comment by rorydavidson** [comment]
Could you give us a bit of context to the setup you are using, i.e. memory allocated and CPU specs? There is normally no need to change any timeout settings on a straightforward snapshot import.

**Comment by Eneuman** [comment]
Sure :)

I'm running in a Azure Kubernetes cluster and the node is a 4 Core with 32Gb memory. Elasticsearch and Snowstorm has no limit set on them (yet). Elastic uses about 5Gb mem and Snowstorm around 1.5 Gb.

The import runs for about 1 hour before it stops with the timeout above. I have a persisted volume attached (Azure files storage provider) and it's about 15Gb in size.

**Comment by Eneuman** [comment]
![image](https://user-images.githubusercontent.com/12099277/120763127-363fc280-c517-11eb-84e1-2fda895e395f.png)

**Comment by rorydavidson** [comment]
I'm far from a Kubernetes or Azure expert as we use neither at the moment, but normally an import using our docker-compose stack takes around 30 minutes.
Elasticsearch is generally given around 8GB allocated memory upfront and the snowstorm container 4GB. If you are able to do this, that might help?

**Comment by Eneuman** [comment]
I just recreated the pods with added request memory and started a new import.
I'll get back to you with the results.
Thanks for helping me out :)

**Comment by Eneuman** [comment]
Do you know why the JVM is limited to 4gb in the kubernetes deployment profile?
Doesn't this setting prevent it from using the full 8Gb i set as a request limit ?

**Comment by Eneuman** [comment]
@rorydavidson I still get the same error even after forcing JVM to run in 8 gig for elastic and 4gb for snowstorm :(
Anything else I can try?

**Comment by Eneuman** [comment]
I found the problem.
My PODs used a storage volume that was to slow. It used the storage class Azure-Files (that is backed up by HDD) when it should have used the default storage class that is backed by SSD.

Switching the storage class to one with faster IO resolved my problem.

**Comment by kaicode** [comment]
Oh, that's good news! Thank you for sharing the solution.
