### ISSUE TITLE
unhealthy snowstorm container

### ISSUE THREAD

**Issue by okongwu101** [IHTSDO/snowstorm#280]
I have been trying to launch Snowstorm with docker but after starting up the elasticsearch container, i get this error:

ERROR: for snowstorm  Container "d2c964470c18" is unhealthy.
ERROR: Encountered errors while bringing up the project.

I have tried both the 'latest' and 6.2.0 versions, but i still get the same error. Can anyone help me with this?

**Comment by rorydavidson** [comment]
Hi @okongwu101 , it sounds like you are hitting Docker virtual memory issues. Please read the documentation here - https://github.com/IHTSDO/snowstorm/blob/master/docs/using-docker.md#docker-virtual-memory-limits - which gives some tips on how to get around this.

**Comment by okongwu101** [comment]
Thank you @rorydavidson for the quick response. Am guessing you are referring to running this command 

wsl -d docker-desktop sysctl -w vm.max_map_count=262144

in powershell before running docker-compose up.

I did that earlier and still tried now. But i still get same error.

**Comment by okongwu101** [comment]
Tried it again but this time with administrative priviledges in powershell. And it worked. Thanks for your time.
