### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by alex-ha-github** [IHTSDO/snowstorm#286]
Hi,

I'm looking forward to the basic authentication function in Snowstorm.
Any planned release schedule on it?

Thanks a lot.

**Comment by kaicode** [comment]
There is no current plan to add / fix basic authentication in the Snowstorm application. 

This can be implemented easily using Nginx, see [Nginx basic-authentication documentation](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).

You can even allow GET and HEAD requests but require authentication for import / admin requests using a location block like this:
```
    location /snowstorm/snomed-ct {
        proxy_pass http://localhost:8080;
        limit_except GET HEAD {
            auth_basic 'Restricted';
            auth_basic_user_file /etc/nginx/.htpasswd;
        }
    }
```
