### ISSUE TITLE
RF2 SNAPSHOT import job failed

### ISSUE THREAD

**Issue by okongwu101** [IHTSDO/snowstorm#287]
Hi, I am trying to install snowstorm with docker. I have pretty much followed all the instructions and  it runs when I fire up the containers. However, RF2 file loading via the swagger ui keep failing. Please any suggestion to handle this will be appreciated. Thanks in advance.

**Comment by okongwu101** [comment]
If there was any confusion to above, I meant import job failure.

**Comment by okongwu101** [comment]
Hi everyone. Please i still help with this issue. Find attached a text file with shell output. Thanks.
[SNOMED UPLOAD ERROR.txt](https://github.com/IHTSDO/snowstorm/files/6790379/SNOMED.UPLOAD.ERROR.txt)

**Comment by rorydavidson** [comment]
Hi @okongwu101 ,
how much memory are you giving the docker containers as it looks like a timeout between the snowstorm and the elasticsearch containers? This is sometimes because the elastic search container does not have enough resources (either memory or cpu).

**Comment by okongwu101** [comment]
I assiged 4g to the docker containers. Here is my docker compose file.

version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 4g


  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g -jar snowstorm.jar --elasticsearch.urls=http://es:9200
    networks:
      elastic:
        aliases:
         - snowstorm
    ports:
      - 8080:8080

  browser:
    image: snomedinternational/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
    networks:
      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 80:80
    restart: always


networks:
  elastic:

volumes:
  elastic:

**Comment by rorydavidson** [comment]
In my experience, I've give Docker itself 16gb and assigned 8gb to the elasticsearch container and 4gb to snowstorm. If you can, might be worth trying that?

**Comment by okongwu101** [comment]
Will try that and get back. Thank you for the assistance.
