### ISSUE TITLE
Quotes not escaped in ECL response

### ISSUE THREAD

**Issue by iCart** [IHTSDO/snowstorm#29]
Consider this curl request for the concept "Wallace "69" side-to-end anastomosis":

`curl -X GET --header 'Accept-Language: en' 'http://localhost:8080/browser/MAIN/concepts/257751006'`

In this case, the quotes in the terms are properly escaped, eg: 
`"Wallace \"69\" side-to-end anastomosis - action (qualifier value)"`.

However, the same request expressed as an ECL query, like this:

`curl 'http://localhost:8080/MAIN/concepts?ecl=%20257751006%20&page=0&limit=1'`

will return an invalid JSON response because the quotes are not escaped, eg: 
`"Wallace "69" side-to-end anastomosis - action (qualifier value)"`

**Comment by kaicode** [comment]
Included in release 2.2.0.
