### ISSUE TITLE
Snowstorm does not work with timestamp

### ISSUE THREAD

**Issue by waydes** [IHTSDO/snowstorm#308]
I am trying to load the Veterinary Extension into Snowstorm.  Are there plans for Snowstorm to accept timestamp for effectiveTime in the future or will it always be just the date?

**Comment by rorydavidson** [comment]
Hi @waydes, currently effective dates are only accepted in SNOMED CT. 
There are no plans to change this at the moment so on a date (YYYYMMDD) will be accepted as the effectiveTime for now.
