### ISSUE TITLE
«released»: «false»

### ISSUE THREAD

**Issue by kaboyles** [IHTSDO/snowstorm#309]
Release status in Snowstorm

We are now using Snowstorm endpoint /{branch}/members (post) to import refsets from a third party system. It works very well, but all members are flagged with «released»: «false»

We need deeper understanding about why this is happening, and how to work around it.

Would it be possible to send us some documentation or get an explanation?

**Comment by kaicode** [comment]
Hi @kaboyles,

The Snowstorm POST API endpoints are intended for content maintenance. Whenever components are created or changed they are marked with `"released": false` to show that they have changed during the current authoring cycle. At the end of the authoring cycle the code system create version function can be used to version all components on the code system branch and set `"released": true`.

There are two different ways to mark reference set members as released:
- If using Snowstorm for content maintenance: when the end of the authoring cycle is reached version the content on the code system branch using the create version function
- _Or_ if using Snowstorm to host content that is maintained and versioned in another system: import the versioned content (with a date in the effectiveTime column) using an RF2 import.

I hope this helps.

**Comment by kaboyles** [comment]
Thanks...it worked for us!!

**Comment by Tannjorn** [comment]
And a further explanation. We really don't need to have a released status, but we need to utilize the history mechanisms embedded in Snowmed.

Perhaps @kaboyles also will be interested in this issue.

**Comment by kaicode** [comment]
If you would like to release the maps independently of the main extension then yes, a separate code system for the maps would be best. You can upgrade the maps code system whenever there is a new release of the extension.
