### ISSUE TITLE
CORS issue docker

### ISSUE THREAD

**Issue by dominik160** [IHTSDO/snowstorm#311]
Hey :)
I use the Snowstorm server local via docker and at the same time i want to send a request via an angle application (local). The problem is i get a cors error. Is there any way to handle this problem in the server?

**Comment by kaicode** [comment]
Snowstorm does not have any CORS configuration. You can workaround this issue by calling Snowstorm via an HTTP server like NGinx and adding the necessary allow origin header there: https://serverfault.com/a/176729/85094

**Comment by kaicode** [comment]
Using NGinx would be the simplest way. 

The Spring Boot documentation (Snowstorm is a Spring Boot app) states that the allow origin response headers can be [set via configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.cors) but I have not tried it and there are those that [claim this does not work](https://stackoverflow.com/a/46091010/512223) without hardcoding the configuration in the source code which seems very nasty.
