### ISSUE TITLE
effectiveTime in the dailybuild

### ISSUE THREAD

**Issue by hurtigcodes** [IHTSDO/snowstorm#318]
Hi,
We're configuring a fresh Snowstorm with db enabled.

We're getting the latest db package from the S3 bucket successfully. But when opening it it contains a PRODUCTION RF2 with all components marked with effectiveTime set to 20210415 (this is our NRC's last release date). During import (we've tried manually & via the DBService) Snowstorm imports all components with `released: true` and `effectiveTime:  20210415`. We import with flag createCodeSystem: false. 

I talked to Snomed International and they responded that they create this PRODUCTION file marked with 20210415 due to the way their tooling is set up. This is a bit confusing to me, since the whole point of the dailybuild is to deal with unpublished content and we should have no real effectiveTime. Nevertheless, since it hasn't been released I'm assuming that the expected behaviour in Snowstorm should not be `released: true` and `effectiveTime:  20210415` after a successful db import?

I ask here if this assumption is correct and if there's some config or import param that we might have missed?

Thanks!

**Comment by kaicode** [comment]
Hey,

If the rows in the RF2 import have an effectiveTime then the components imported will have the released flag and display an effectiveTime. There is no way to change this behaviour.

When preparing a fresh Snowstorm you will need to first import a snapshot of the International Edition and a snapshot of the latest versioned extension on the respective code system branches. These files will understandably contain an effectiveTime on all components. The delta RF2 files from the dailybuild S3 bucket should have a blank effectiveTime field.

Cheers,
Kai

**Comment by kaicode** [comment]
@hurtigcodes I've just found in the Snowstorm code that the daily build import is a special case where Snowstorm strips the effectiveTime from the components during the import. This behaviour is only available in the automatic daily build import, not the manual RF2 import.

I hope that answers your question.
Cheers, Kai

**Comment by hurtigcodes** [comment]
All right, so we need to configure the automatic daily build import properly. Closing ticket, thanks!
