### ISSUE TITLE
Docker installation issue. ERROR: for snowstorm  Container "abf9a1baecba" is unhealthy.

### ISSUE THREAD

**Issue by olamide226** [IHTSDO/snowstorm#321]
I am running docker on a raspberry Pi running Ubuntu 20.04 server aarch64 with 8GB of RAM. However when I run `docker-compose up -d` I keep getting the error "Starting elasticsearch ... done

ERROR: for snowstorm  Container "abf9a1baecba" is unhealthy.
ERROR: Encountered errors while bringing up the project.."

Here's the log from `docker logs abf9a1baecba`:
```
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by rorydavidson** [comment]
We have not tested running on a Raspberry Pi, and considering we generally use servers with 16GB RAM this might cause you an issue or at least, performance may not be great.

To your issue, have you tried the instructions detailed here - https://github.com/IHTSDO/snowstorm/blob/master/docs/using-docker.md#docker-virtual-memory-limits - to see if that gets the containers running?

**Comment by olamide226** [comment]
Yes I have tried that to no avail. Ive decided to just run it using the plain installation method without Docker. It works fine but It'd be good to know if there's any solution for the docker issue.
