### ISSUE TITLE
Question on 'new concepts' authoring stats

### ISSUE THREAD

**Issue by hurtigcodes** [IHTSDO/snowstorm#323]
Hi,
I have a question what the primitive and concrete values mean in this snippet from the 'new concepts' authoring stats endpoint? 

The clinical drug in this snippet contains concrete values, so I also wonder what might trigger this boolean?

```json
  {
    "id": "1079801000202107",
    "primitive": true,
    "term": "Product containing precisely amlodipine (as amlodipine besilate) 10 milligram and hydrochlorothiazide 25 milligram and valsartan 160 milligram/1 each conventional release oral tablet (clinical drug)",
    "concrete": false
  }
```

**Comment by kaicode** [comment]
Well spotted! This is a bug, the concrete field is not supposed to appear in these stats. 
This is already [fixed](https://github.com/IHTSDO/snowstorm/commit/5c5e5bda1c219c2e84b3c27d12eb3efbc4559df6) in the Snowstorm develop branch and will go out with the next release.

**Comment by hurtigcodes** [comment]
I see, I will close this issue since it has been resolved. Thanks @kaicode!
