### ISSUE TITLE
Release update error : MRCM range constraint not defined for attribute 1142139005

### ISSUE THREAD

**Issue by Lotili** [IHTSDO/snowstorm#325]
Hi there,
We've encountered an error while trying to import the Belgian release delta:
`java.lang.IllegalStateException: No MRCM range constraint is defined for concrete attribute 1142139005`
This attribute is from SNOMED international, not the Belgian extension. Note that in August, we updated the International version on our instance of snowstorm without any issue. We tried to manually check the RF2 files but weren't able to identify the source of this issue. 
Any idea what can be done and if there is anything we can do on our side?
Thanks in advance,

**Comment by kaicode** [comment]
Hi @Lotili,
Thanks for reaching out.

There are MRCM constraints defined for this concrete attribute, as seen in the [MRCM browser](https://browser.ihtsdotools.org/mrcm/).
<img width="1411" alt="Screenshot 2021-10-05 at 11 19 48" src="https://user-images.githubusercontent.com/2010517/136005247-1ec6b195-da23-4994-b6e4-7326b111c44e.png">

The reference set member containing the range constraint for that attribute should be available via the rest interface: `GET /MAIN/2021-07-31/members/39f5f1fc-d2e4-45b0-9643-d6ce66a871d6`. It's in the public Snowstorm instance [here](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2021-07-31/members/39f5f1fc-d2e4-45b0-9643-d6ce66a871d6).

Support for concrete domains and updates to the MRCM endpoints to work with concrete attributes was added in Snowstorm 6.2.0. If the July 2021 International release was imported into an earlier version of Snowstorm the concrete attributes will not have imported correctly. Could that be the problem?

**Comment by Lotili** [comment]
Hi Kai,
Thanks for your answer! We had updated Snowstorm right before importing the new release, so I doubt this is the issue. I tried to get `1142139005` from the MRCM attribute range international refset and I find it alright:

request URL : 
`https://snowstorm-aws.earlytracks.be/MAIN/members?referenceSet=723562003&referencedComponentId=1142139005&offset=0&limit=50`

response :
``` {
  "items": [
    {
      "active": true,
      "moduleId": "900000000000012004",
      "released": true,
      "releasedEffectiveTime": 20210731,
      "memberId": "39f5f1fc-d2e4-45b0-9643-d6ce66a871d6",
      "refsetId": "723562003",
      "referencedComponentId": "1142139005",
      "additionalFields": {
        "rangeConstraint": "int(>#0..)",
        "attributeRule": "<< 373873005 |Pharmaceutical / biologic product (product)|: [0..1] 1142139005 |Count of base of active ingredient| > #0",
        "contentTypeId": "723596005",
        "ruleStrengthId": "723597001"
      },
      "referencedComponent": {
        "conceptId": "1142139005",
        "active": true,
        "definitionStatus": "PRIMITIVE",
        "moduleId": "900000000000012004",
        "fsn": {
          "term": "Count of base of active ingredient (attribute)",
          "lang": "en"
        },
        "pt": {
          "term": "Count of base of active ingredient",
          "lang": "en"
        },
        "id": "1142139005"
      },
      "effectiveTime": "20210731"
    }
  ],
  "total": 1,
  "limit": 50,
  "offset": 0
} 
```

Is there anything I can query to give you more info ?

**Comment by CoderMChu** [comment]
@Lotili  Can you run the same request above on the branch path you tried to import please?
