### ISSUE TITLE
How do I start a brand new snowstorm installation once I started already one?

### ISSUE THREAD

**Issue by anibal2j** [IHTSDO/snowstorm#342]
I'm trying to install snowstorm and load the Canadian Extension. I did something wrong, since I loaded the Canadian Extension without loading the International first.  I just want to start from scratch. What's the procedure for starting from scratch so that I have a clean slate to begin with?

**Comment by rorydavidson** [comment]
Hi @anibal2j , to reset all the indices to have a clean instance, please follow the instructions here - https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md#command-line - using the `--delete-indices` flag.
