### ISSUE TITLE
Rollback partial commit timeout

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [IHTSDO/snowstorm#354]
An import of the UK Drug Extension failed for me (reason as yet unknown), but in trying to rollback the partial commit so I can attempt the import, I get a timeout:

```json
{
  "error": "INTERNAL_SERVER_ERROR",
  "message": "30,000 milliseconds timeout on connection http-outgoing-125 [ACTIVE]; nested exception is java.lang.RuntimeException: 30,000 milliseconds timeout on connection http-outgoing-125 [ACTIVE]"
}
````

Can you advise how I should proceed?

**Comment by kaicode** [comment]
Hi @evergreen-lee-campbell, happy new year to you.

The UK Drug Extension is a very large extension so I expect it will need much more resources than the recommended default. The import is the most resource intensive step so I would be tempted to throw in all the resources you can give it and then scale back once the import is complete. Elasticsearch with 8g and Snowstorm with 6g should work (see #271).

As Elasticsearch runs out of memory it will start becoming slower which is a likely cause of the error you are seeing.
I think after the Elasticsearch timeout error during a commit rollback your data store could be in an inconsistent state. You could try running a hard delete on the code system branch (`DELETE /admin/{branch}/actions/hard-delete`) and then recreate the branch manually. Alternatively you could delete all your Elasticsearch data and start again from fresh.

**Comment by evergreen-lee-campbell** [comment]
Hi @kaicode, same to you!

Thanks for your response. I've been adding deltas to my `MAIN/SNOMEDCT-UK`, so it has children and cannot be hard-deleted. Does this mean that I must delete the Elasticsearch data and begin again?

**Comment by kaicode** [comment]
I'm not sure what to suggest here. You could try running the partial commit rollback again; if a subsequent run completes the data should be clean.

Giving Elasticsearch more memory and making sure it's using an SSD drive will help prevent timeouts. If that doesn't work you could try changing the save batch size, as suggested in a related issue #244.

Deleting the data and starting again will guarantee clean data as a fallback strategy.

**Comment by evergreen-lee-campbell** [comment]
Thanks @kaicode. As far as importing the UK Drug Extension goes, given that I have already imported the UK Clinical, should I be setting up the import job thus:

```json
{
  "branchPath": "MAIN/SNOMEDCT-UK",
  "createCodeSystemVersion": false,
  "type": "SNAPSHOT"
}```

Or should "createCodeSystemVersion" be `true`? If I understand correctly, I already created the code system version when I created the UK Clinical branch, and there should be no overlap from this snapshot, so I just load it in on top, right?

**Comment by kaicode** [comment]
You are right. If you would like to import both the clinical extension and drug extension into a single code-system and have already imported the first one with `createCodeSystemVersion: true` then import the second one with `createCodeSystemVersion: false`. 
You should also merge to the code system version branch to update the content there. 
See recommended method from Rory here: https://github.com/IHTSDO/snowstorm/issues/271#issuecomment-847895543

**Comment by evergreen-lee-campbell** [comment]
Excellent. Thanks. You're a good egg! 

Last question: why does he perform the merge twice?

**Comment by kaicode** [comment]
@evergreen-lee-campbell I didn't understand that either.

@rorydavidson do you happen to remember why you seem to have imported the UK drug extension twice in that comment?

**Comment by kaicode** [comment]
A good basic check is to count the total number of concepts, or the total number of active concepts. These numbers could be cross-referenced with another source.

E.g. https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2021-01-31/concepts?activeFilter=true&limit=1
See the "total" field.
