### ISSUE TITLE
Add Filter semantic Tag

### ISSUE THREAD

**Issue by GokulRamasamy** [IHTSDO/snowstorm#36]
How to search term based on semantic tag.
eg: I want to search 'heart attack' term from disorder semantic tag.

**Comment by kaicode** [comment]
Hi there. There are two ways to achieve searching within a specific area of the hierarchy; using ECL or using a semantic tag filter. 

**ECL Method**
Combine an ECL structural search with a term search using the concepts endpoint:
```
GET /{branch}/concepts?ecl={ecl}&term={term}
```
For example:
```
GET /MAIN/concepts?ecl=<64572001&term=heart%20attack
```
This will return concepts which are descendants of 64572001 |Disease (disorder)| and also have a description matching the term query. Prefixes of words can be used in the term param for example `myo infar` can be used to match `Myocardial infarction`

**Semantic Tag Filter**
The semantic tag filter is only currently available on the develop branch of this project. It is scheduled to be released in Snowstorm version 3.x 
If you wanted to use the develop branch you can test it now using the following endpoint:
```
GET /browser/{branch}/descriptions?semanticTag={semanticTag}&term={term}
```
For example:
```
GET /browser/MAIN/2019-01-31/descriptions?semanticTag=disorder&term=heart%20attack
```
When reading the response scroll down through the aggregations to the `items` section to see the results.

**Comment by GokulRamasamy** [comment]
Hi,
Thanks for your support.
Exactly I expected semantic tag filter in descriptions. (GET /browser/{branch}/descriptions?semanticTag={semanticTag}&term={term})
ECl query also working fine.
When will we expect snowstorm version 3.x?

**Comment by kaicode** [comment]
The first 3.x release is currently planned for the beginning of May.
