### ISSUE TITLE
Question : New release archive without delta

### ISSUE THREAD

**Issue by Lotili** [IHTSDO/snowstorm#371]
Hi !
We've just updated our snowstorm server with the latest International release. As you know, from this release on, there is no DELTA folder anymore. We used [this](https://github.com/IHTSDO/delta-generator-tool/releases) project to create one and the import was successful. However, do you plan on adapting Snowstorm so we don't have that extra step for every release ? The delta generator project is quite easy to use, but not all of our team is comfortable running command line programs and I see it as extra room for bugs, incompatibilities and mistakes.
Thanks in advance !

**Comment by rorydavidson** [comment]
Hi @Lotili, Snowstorm can import a snapshot from the RF2 release and updates the terminology as necessary as if it was using a delta, so there is no need to use a delta anymore for imports of new releases.
Hope that helps.
