### ISSUE TITLE
"Failed to call access method: java.lang.IllegalArgumentException: Offset must be a multiplication of the limit param in order to map to Spring pages."

### ISSUE THREAD

**Issue by steve1973** [IHTSDO/snowstorm#372]
Hi there

I upgraded SS from v7.0.1 to v7.6.0, but am experiencing an error when running this query, which worked ok in v7.0.1.

/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&count=10&offset=1&filter=ASTHMA&_format=json

Is the above request now incorrect or need changing to work with v7.6.0?

Many thanks

Steve

**Comment by kaicode** [comment]
I didn't expect a count of 10 and offset of 0 to work with v7.0.1. 
The offset should start at 0. If a count of 10 is being used then the next offset should be 10. This is a restriction of the underlaying frameworks used. (Spring Boot and Spring Data Elasticsearch). An offset of 1 will miss the first result.

**Comment by steve1973** [comment]
Thanks Kai, I think it was a test from the Snowstorm FHIR 4.0 collection I downloaded sometime ago, but have refreshed it and can see it's no longer there. Thanks for the explanation.
