### ISSUE TITLE
Wrong PT is provided by browser end point

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#379]
For the concept 252616000 | Auditory brainstem electric response audiometry (procedure) | snowstorm provides the wrong PT in Swedish.

https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-SE/2021-11-30/concepts/252616000?descendantCountForm=inferred

```
{
conceptId: "252616000",
descendantCount: 8,
fsn: {
term: "Auditory brainstem electric response audiometry (procedure)",
lang: "en"
},
pt: {
term: "ABR",
lang: "sv"
},
active: true,
effectiveTime: "20020131",
released: true,
releasedEffectiveTime: 20020131,
moduleId: "900000000000207008",
definitionStatus: "PRIMITIVE",
descriptions: [
...
{
active: true,
moduleId: "45991000052106",
released: true,
releasedEffectiveTime: 20210531,
descriptionId: "4795141000052117",
term: "ABR",
conceptId: "252616000",
typeId: "900000000000013009",
acceptabilityMap: {
46011000052107: "ACCEPTABLE"
},
type: "SYNONYM",
caseSignificance: "ENTIRE_TERM_CASE_SENSITIVE",
lang: "sv",
effectiveTime: "20210531"
},
...
```

**Comment by kaicode** [comment]
Hi @danka74,

I am able to reproduce this issue when using request header `Accept-Language: sv`. This causes the term "" to be returned, which is incorrect because this term is only acceptable, not preferred.

The API seems to behave correctly when a specific language refset is requested using header `Accept-Language: sv-X-46011000052107`.

**Comment by danka74** [comment]
Hi @kaicode ,
ok, the browser does not use the language refset specification in Accept-Language it seems, so in the browser the wrong term is displayed.
/Daniel

**Comment by kaicode** [comment]
@danka74 thanks for pointing this out. We will get this bug fixed.

**Comment by kaicode** [comment]
Jira ticket - https://jira.ihtsdotools.org/browse/BROWSE-531

**Comment by danka74** [comment]
Thanks!

**Comment by danka74** [comment]
Still seems to be an issue.
http://localhost:8080/snowstorm/snomed-ct/browser/MAIN%2FSNOMEDCT-SE/concepts/122575003
(running develop branch 7.8.0-SNAPSHOT)
gives "urin" as PT with Accept-language: sv and "urinprov" with Accept-language: sv-X-46011000052107

http://localhost:8080/snowstorm/snomed-ct/MAIN%2FSNOMEDCT-SE/descriptions?conceptId=122575003&offset=0&limit=50

```
{
  "items": [
    {
      "active": true,
      "moduleId": "45991000052106",
      "released": true,
      "releasedEffectiveTime": 20121221,
      "descriptionId": "2129731000052116",
      "term": "urinprov",
      "conceptId": "122575003",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "46011000052107": "PREFERRED"
      },
      "type": "SYNONYM",
      "caseSignificance": "CASE_INSENSITIVE",
      "lang": "sv",
      "effectiveTime": "20121221"
    },
    {
      "active": true,
      "moduleId": "45991000052106",
      "released": true,
      "releasedEffectiveTime": 20210531,
      "descriptionId": "503811000057112",
      "term": "urin",
      "conceptId": "122575003",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "500191000057100": "PREFERRED"
      },
      "type": "SYNONYM",
      "caseSignificance": "CASE_INSENSITIVE",
      "lang": "sv",
      "effectiveTime": "20210531"
    },
...
  ],
  "total": 5,
  "limit": 50,
  "offset": 0
}
```

**Comment by danka74** [comment]
I have created a branch for adding a deafult language refset from the application.properties file when there is only a 2 character accept language tag and added Swedish (where norwegian dialects are).

https://github.com/danka74/snowstorm/tree/feature/defaultLangRefset

Tested in browser. Hope this does not conflict with other uses of the Accept language header.

**Comment by kaicode** [comment]
You are right that returning "urin" is a different issue caused by the fact that the terminology server does not know _which_ sv preferred term is the best in this situation. 

Thanks for the PR, looks good to me. I have requested that the tech team review and progress that.

**Comment by danka74** [comment]
I see that the second issue (not checking which language refset) shows up in the FHIR methods as well. Will look into.

https://browser.ihtsdotools.org/snowstorm/snomed-ct/fhir/CodeSystem/$lookup?system=http://snomed.info/sct&version=http://snomed.info/sct/45991000052106&code=122575003

https://github.com/IHTSDO/snowstorm/blob/3969e965224502266a0f837a13873c88f4baad3c/src/main/java/org/snomed/snowstorm/fhir/services/FHIRHelper.java#L258
