### ISSUE TITLE
IP address has been blocked

### ISSUE THREAD

**Issue by joezein** [IHTSDO/snowstorm#382]
Hey - first time I use the product and my IP has been blocked which is very weird. 
Is there an issue with the API or anything I should be aware of ?
Thanks

**Comment by kaicode** [comment]
Hi @joezein 
This is an open source project for a software product. 
There is a public instance of Snowstorm available for testing but it is not intended for production use. It has rate limiting and has no SLA. Feel free to get in touch with techsupport@snomed.org to make an enquiry about the rate limiting.
Cheers.
