### ISSUE TITLE
How do I know where the actual SNOMED CT Release is stored on disk?

### ISSUE THREAD

**Issue by anibal2j** [IHTSDO/snowstorm#386]
Hi,

I need to manage the storage on the snowstorm server and I can't find where is the actual storage of the release I loaded.

I need to upload 2 more releases and I'd like to be confident that I'm placing them in the right partition that I have available.

I'm not really talking about the application per se, but the actual SNOMED release and/or different branches.

Thanks,

-Anibal

**Comment by kaicode** [comment]
Hi!
Everything is stored in Elasticsearch. On a local deployment the data goes into a directory on disk like `elasticsearch/data/`. Data may not all be flushed to disk in this directory until Elasticsearch is shutdown. There are standard ways to backup and restore Elasticsearch data, in their documentation.
I hope that helps.

**Comment by anibal2j** [comment]
Found it!

In my installation the configuration for elasticsearch is under ```/etc/elasticsearch```, where I can find ```elasticsearch.yml``` which has the value of ```path.data: /var/lib/elasticsearch```

And if I go there I have this:

```
[root@tcn00qubc03104 /var/lib/elasticsearch]# du -sh /var/lib/elasticsearch
2.9G	/var/lib/elasticsearch
```

Which sounds about right.

**Comment by kaicode** [comment]
@anibal2j  Glad you found it! For the record which operating system are you using and which installation method did you use? Might help others later 😄

**Comment by anibal2j** [comment]
```
Red Hat Enterprise Linux release 8.5 (Ootpa)
```

And I used a combination of installation procedures - mostly helped by Rory :-)  It was done several months ago and I forgot but tried to follow what's documented in the home page of this project here in github.

I'm about to do, for the first time, an update of our SNOMED CT release as well as adding the UK release on our own snowstorm installation, let's see how that goes...

**Comment by kaicode** [comment]
Thank you. Best of luck!
