### ISSUE TITLE
Retrieving descendants - stated versus inferred

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#39]
Retrieving descendants using either the swagger ui or URL does not react to changing the requested state (inferred versus stated).
`http://localhost:8080/MAIN/concepts/125589001/descendants?stated=true&offset=0&limit=10000`
Results in the same descendants as: 
`http://localhost:8081/MAIN/concepts/125589001/descendants?stated=false&offset=0&limit=10000`
Can anyone confirm this and perhaps help with a workaround?
Best regards

**Comment by kaicode** [comment]
Hi @mertenssander. Thanks for getting in touch. 
This is a bug in the wiring of the controllers. The search is always happening against the stated form which is not the intention here.

Please use this as a workaround:
**Stated**
`http://localhost:8080/MAIN/concepts?statedEcl=<125589001`
**Inferred**
`http://localhost:8080/MAIN/concepts?ecl=<125589001`

We will get this fixed.

**Comment by kaicode** [comment]
Fixed in [Snowstorm 2.2.3](https://github.com/IHTSDO/snowstorm/releases/tag/2.2.3).

**Comment by mertenssander** [comment]
Thank you for the quick reply and workaround!
