### ISSUE TITLE
Rename variable / method

### ISSUE THREAD

**Issue by pgwilliams** [IHTSDO/snowstorm#40]
Is the "termPrefix" really a prefix?  I'm calling it to find matching text anywhere in the term.   Would a clearer name be "termMatch" or "termFilter" ?    Thanks!

https://github.com/IHTSDO/snowstorm/blob/9ec26802f91fe3e6f0c7a27b2d35f8493ccd4b7c/src/main/java/org/snomed/snowstorm/core/data/services/QueryService.java#L501

PS Just used it to implement a FHIR parameter in under 5 mins - bonus!

**Comment by kaicode** [comment]
You are right. I like `termMatch` 👍

**Comment by pgwilliams** [comment]
Addressed in STORM-206
