### ISSUE TITLE
Docker Elasticsearch data disappearing

### ISSUE THREAD

**Issue by ChantalSchiltmeijer** [IHTSDO/snowstorm#425]
Over the last few weeks we are noticing something vague on our version of Snowstorm (NL).
When everything is updated, so latest versions of SNOMED including the Dutch edition etc.. it works perfectly.
But than the next day, or a couple of days later all the content seems to have disappeared.
We are currently running on version: "7.8.0" and elasticsearch: "7.7.0".

_ERROR 1 --- [io-8080-exec-68] o.s.s.rest.config.RestControllerAdvice   : Index [branch] not found.; nested exception is [branch] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [branch]]]_

Not sure why, but in addition to this the container status of Snowstorm keeps coming back as _unhealthy_. 
In our modified docker-compose.yml we do test on the following:
    healthcheck:
      test: ["CMD", "wget", "-S", "http://snow:8080"]
      interval: 10s
      timeout: 10s
      retries: 280

Reviewing container logs, I'm finding the following:
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 31473,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-07-01T06:26:32.368442872Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "**unhealthy**",
                "FailingStreak": **27350**,
                "Log": [
                    {
                        "Start": "2022-07-04T12:58:05.360160722+02:00",
                        "End": "2022-07-04T12:58:05.425295703+02:00",
                        "ExitCode": 1,
                        "Output": "Connecting to snow:8080 (192.168.96.3:8080)\n  HTTP/1.1 302 \n  X-Content-Type-Options: nosniff\n  X-XSS-Protection: 1; mode=block\n  Cache-Control: no-cache, no-store, max-age=0, must-revalidate\n  Pragma: no-cache\n  Expires: 0\n  X-Frame-Options: DENY\n  Location: http://snow:8080/swagger-ui.html\nConnecting to snow:8080 (192.168.96.3:8080)\n  HTTP/1.1 200 \n  Vary: Origin\n  Vary: Access-Control-Request-Method\n  Vary: Access-Control-Request-Headers\n  Last-Modified: Thu, 23 Jun 2022 02:24:27 GMT\n  Accept-Ranges: bytes\n  X-Content-Type-Options: nosniff\n  X-XSS-Protection: 1; mode=block\n  Cache-Control: no-cache, no-store, max-age=0, must-revalidate\n  Pragma: no-cache\n  Expires: 0\n  X-Frame-Options: DENY\n  Content-Type: text/html\n  Content-Length: 2927\n  Date: Mon, 04 Jul 2022 10:58:05 GMT\n  Connection: close\n  **\nwget: can't open 'index.html': File exists\n"**
                    },

In an attempt to get it back on track, we tried, adding content again, which just works for a few days.
But also updating Snowstorm or reinstalling container (compose down/up) doesn't seem to be helping.
I am not sure if these two (errors) are related, but both seem like they need to be resolved. 

Because this occurs quite often, we tried to upload a Snapshot, but ran into an 'out of memory error'. Can adding heap space solve this issue? There is enough room on the server (>90GB). I am still trying to figure out how this all works, but i hope you can help me solve this issue with the information given.

**Comment by kaicode** [comment]
Hi @ChantalSchiltmeijer,
From the first error you posted it looks like your Elasticsearch instance is becoming completely blank somehow, like the whole storage is being wiped. Does that docker instance have persistent storage? I would attempt to find the location where Elasticsearch is storing its data and monitor that location. 
Regarding the out of memory error, make sure Snowstorm is started with enough heap memory using the minimum (`-Xms`) and maximum (`-Xmx`) memory parameters, something like: 
```
java -Xms2g -Xmx4g -jar snowstorm.jar
```
It doesn't look like the dockerfile does this at the moment.
