### ISSUE TITLE
Snowstorm FHIR API does not interpret ECL v2.0 query correctly (returning refset member fields)

### ISSUE THREAD

**Issue by ulsa123** [IHTSDO/snowstorm#440]
ECL:

^  [mapAdvice] 447562003 |ICD-10 complex map reference set|  {{ M mapTarget = wild:"J45*" }}

running in browser and rest API but FHIR api returns:

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Elasticsearch exception [type=x_content_parse_exception, reason=[1:1234] [bool] failed to parse field [must]]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=x_content_parse_exception, reason=[1:1234] [bool] failed to parse field [must]]]; nested: ElasticsearchException[Elasticsearch exception [type=parsing_exception, reason=No value specified for terms query]];"
        }
    ]
}
FHIR request through postman:
https://dailybuild-qa.northeurope.cloudapp.azure.com/snowstorm/snomed-ct/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%5E%20%20%5BmapAdvice%5D%20447562003%20%7CICD-10%20complex%20map%20reference%20set%7C%20%20%7B%7B%20M%20mapTarget%20%3D%20wild%3A%22J45*%22%20%7D%7D&system-version=http://snomed.info/xsct/51000202101

ref: https://jira.ihtsdotools.org/browse/MSSP-1681

**Comment by kaicode** [comment]
Hi @ulsa123,
I responded on the Jira ticket but will post again here for community visibility:

Unfortunately it is not possible for a FHIR interface to return specific fields from reference set members using ECL. It just doesn't fit in with the permitted response format.

Please remove the specific field section from the ECL to make it work:
```
^ 447562003 |ICD-10 complex map reference set|  {{ M mapTarget = wild:"J45*" }}
```

https://dailybuild-qa.northeurope.cloudapp.azure.com/snowstorm/snomed-ct/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%5E%20447562003%20%7CICD-10%20complex%20map%20reference%20set%7C%20%20%7B%7B%20M%20mapTarget%20%3D%20wild%3A%22J45*%22%20%7D%7D&system-version=http://snomed.info/xsct/51000202101

This is consistent with other FHIR servers including Ontoserver. I do think that the ECL specification could mention this to help communicate this fact and the Snowstorm error message could be improved.

Thanks for raising this.

**Comment by kaicode** [comment]
@ulsa123 you can fetch refset member fields using the native Snowstorm API:
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/SNOMEDCT-NO/concepts?ecl=%5E%20%20%5BmapAdvice%5D%20447562003%20%7CICD-10%20complex%20map%20reference%20set%7C%20%20%7B%7B%20M%20mapTarget%20%3D%20wild%3A%22J45*%22%20%7D%7D
.. it's just not supported in FHIR APIs.

**Comment by ulsa123** [comment]
Yes, and that is usefull. 
We considered The FHIR api to dynamically populate and expand a FHIR valueset with expressions.

**Comment by kaicode** [comment]
I'm not sure if this helps but the latest implementation of the FHIR API in the Snowstorm X project returns the ICD-10 map advice when translating SNOMED CT codes to ICD-10.
e.g. https://dev-is-browser.ihtsdotools.org/fhir/ConceptMap/$translate?code=254153009&system=http://snomed.info/sct&targetsystem=http://hl7.org/fhir/sid/icd-10

This version of Snowstorm is available here: https://github.com/IHTSDO/snowstorm-x/releases

**Comment by kaicode** [comment]
@ulsa123 I think your issue has already been resolved but just to let you know..

Snowstorm version 8.1.0 has just been published https://github.com/IHTSDO/snowstorm/releases
The new version of the FHIR API includes the [ICD-10 complex map advice in the response](https://snowstorm.ihtsdotools.org/fhir/ConceptMap/$translate?code=254153009&system=http://snomed.info/sct&targetsystem=http://hl7.org/fhir/sid/icd-10) `message` field when using $translate. 
_Unfortunately there is still no standard way to do this in FHIR R4. I heard that it might get introduced in the FHIR R5 specification._
