### ISSUE TITLE
Implicit ValueSets created via $expand should have a status and a timestamp

### ISSUE THREAD

**Issue by Sebge** [IHTSDO/snowstorm#441]
Hey everyone,

while using the Snowstorm to execute an ECL-Query via the $expand-Operation (e.g. http://localhost:8080/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3E%3E46621007), the returned implicit ValueSet does not contain a status field. As this is mandatory according to the FHIR specification (http://hl7.org/fhir/valueset-definitions.html#ValueSet.status), it leads to problems with some FHIR clients. My suggestion would be to set the status to "active", even if it is not permanently stored on the server.

**Comment by pgwilliams** [comment]
That's great spotting/advice there @Sebge, thank you.    I'll raise an internal ticket for that and it should get into our production system for 19 October and be merged to the master branch not long after that.   I'll mark it as a bug as we're failing to provide a mandatory field.

**Comment by Sebge** [comment]
Thank you @pgwilliams for your quick answer! 
While you are at it, you can also take a look at the timestamp field, which is required in the expansion in the ValueSet (http://hl7.org/fhir/valueset-definitions.html#ValueSet.expansion.timestamp) and is also missing at the moment... yes, my client library is very strict regarding absent values 😄

**Comment by kaicode** [comment]
@Sebge the ValueSet expand `status` and `expansion.timestamp` fields have been included in the new FHIR implementation in Snowstorm version 8.1.0 https://github.com/IHTSDO/snowstorm/releases
