### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by mathsnunes** [IHTSDO/snowstorm#465]
Hi guys,

We're trying to improve our searches on Snowstorm but we didn't find any specific guides to do this. In our current scenario, we notice that the painful part of a search is the queries made to ElasticSearch. I'm sharing below some info about our Stack and asking you please some thoughts on how we can improve it.

### Current scenario

**ElasticSearch:** Single node, 2vCPU, 8GB RAM, 50G SSD Disk
**Min query time**: `~500ms` minimum for a search request
**Max query time**: `~5s` minimum for a search request

![image](https://user-images.githubusercontent.com/407070/204569537-cb8380c9-0358-482b-bf88-4f573bd8cef3.png)

Looking at the traces I saw that we have a lot of calls to ES on a single SnowStorm request, most of these calls are very fast but others are very slow and I can't figure out why.

![2022-11-29_12-28](https://user-images.githubusercontent.com/407070/204572955-0c6ade43-3733-46ee-8018-5759e28884e2.png)

**Comment by kaicode** [comment]
Hi @mathsnunes, I'm sorry to hear that you are not getting the performance you would like. 

The first request when using ECL can be slow, if there are a lot of results from the ECL alone, but then the results get cached and subsequent searches (even with different filter terms) should be very fast.

Things you can do to ensure the fastest possible query times (in order of most expected impact)
- Make sure Elasticsearch has enough memory allocated (using `config/jvm.options`).
- Host Elasticsearch on the same machine as Snowstorm. This usually has the biggest impact on speed.
- Reduce the page size (`count` param)
- Don't `includeDesignations` unless they are needed
- Try the [Snowstorm X](https://github.com/IHTSDO/snowstorm-x) project (version 8.x) which has a rewrite of the FHIR API and seems to run this query faster compared to the current public Snowstorm (version 7.x).

Unfortunately there is no single answer here, trying a few combinations of these suggestions should get you the best possible performance with Snowstorm in your environment.

I hope that helps!

**Comment by kaicode** [comment]
FYI - the reason Snowstorm is making multiple fetches to Elasticsearch is because there are no table joins in Elasticsearch and the indies are not denormalised into one index that contains all the information. The first few fast queries are probably checking that there is not a new version of the content in the index so that the ECL cache can be used. The bigger one is probably fetching the description and language refsets that are needed for the display terms and designations.

**Comment by mathsnunes** [comment]
Hi @kaicode,

Thank you for the ideas, I'll try some of them and I circle back.
