### ISSUE TITLE
SemanticTag not working??

### ISSUE THREAD

**Issue by ConorDorrian1** [IHTSDO/snowstorm#47]
When the following command is entered 

curl http://localhost:8080/MAIN/concepts?semanticTag=disorder&term=mouth

It give a false reading?
"total":466617,"limit":50,"offset":0

**Comment by kaicode** [comment]
Hi @ConorDorrian1, the only place we have semanticTag filtering so far is the browser description search in the `develop` branch.
`curl http://localhost:8080/browser/MAIN/descriptions?conceptActive=true&semanticTag=disorder&term=mouth`

This endpoint returns some aggregation information under `buckets` and `bucketConcepts` then the results come under `items` in the response.

This will be included in the first Snowstorm `3.x.x` release which is due in the next week or so.

Generated documentation for the API endpoints and their parameters are available in your deployment here: http://localhost:8080/

Please see the comments in #36 for an alternative way to search under a single hierarchy using ECL.
