### ISSUE TITLE
Problem with language in a query via api

### ISSUE THREAD

**Issue by 25027466** [IHTSDO/snowstorm#470]
Hello.
I have the following problem:

I am using the following search in Spanish:

http://localhost:8080/MAIN/SNOMEDCT-ES/concepts?activeFilter=true&term=dolor%20abdominal&termActive=true&descriptionType=900000000000003001&descriptionType=900000000000013009&preferredOrAcceptableIn=450828004&ecl=(%3C%3C%2071388002%20OR%20%3C%3C%20243796009% 20OR%20%3C%3C%20272379006%20OR%20%3C%3C%20404684003)&offset=0&limit=300

If the execution in the browser returns the terms in the correct language (Spanish)
But if I do the same search using PHP program, it returns the terms in English.

What mistake can I be making?

Thank you!

**Comment by pgwilliams** [comment]
Hello 25026466.  Are you working in Spanish generally?  It's likely that your browser is set to request Spanish by default in the HTTP Accept-Language header.   If you look at the call being made from your browser more closely (eg using "Developer's Tools Tab") then you should see this.    Using programmatic means like PHP would not include this header unless you coded it deliberately, so the default option - English - is being returned there.

**Comment by 25027466** [comment]
Hi @pgwilliams!
thanks for answering.
I started to review the http headers from php curl, and it's as you say.
I corrected the error by setting the language to AR-es and it worked.
so thank you very much for your help.
Greetings from Argentina!
