### ISSUE TITLE
Get ICD10 Code

### ISSUE THREAD

**Issue by 25027466** [IHTSDO/snowstorm#473]
Hi!
How i get the ICD10 code fom Snowstorm across conceptID in Swagger API?

thanks heaps!!

**Comment by kaicode** [comment]
Hi there. 

The API `GET /{branch}/members` can be used for this.

**ICD-10 (International)**
The latest International Edition at this time is `2022-12-31`.  
Using this in the branch path we can fetch the refset members from the `447562003 |SNOMED CT to ICD-10 extended map|` pointing to the concept `73211009  |Diabetes mellitus (disorder)|`  
using the API call: [/MAIN/2022-12-31/members?referenceSet=447562003&active=true&referencedComponentId=73211009](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN%2F2022-12-31/members?referenceSet=447562003&active=true&referencedComponentId=73211009)

The ICD-10 code is returned in the `mapTarget` field. Depending on the SNOMED CT concept there may be multiple ICD-10 codes returned. Some also have map advice, see [ICD-10 Mapping Technical Guide](https://confluence.ihtsdotools.org/display/DOCICD10/ICD-10+Mapping+Technical+Guide).

**ICD-10-CM (US)**
Alternatively for the US version of ICD 10 the `6011000124106 |ICD-10-CM complex map reference set|` should be used. In the SNOMED International public Snowstorm instance the US Edition is loaded into the `MAIN/SNOMEDCT-US` branch, however in US setting the US Edition may be available directly on the `MAIN` branch.
Example using ICD-10-CM: [/MAIN/SNOMEDCT-US/members?referenceSet=6011000124106&active=true&referencedComponentId=73211009](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/SNOMEDCT-US/members?referenceSet=6011000124106&active=true&referencedComponentId=73211009)

Cheers

**Comment by 25027466** [comment]
Hi kaicode!!.
Perfect!. i did it!

Thks so much!

cheers
