### ISSUE TITLE
get problems according to human body system

### ISSUE THREAD

**Issue by juanidepapi** [IHTSDO/snowstorm#479]
hello.
I would like to know how to perform an ECL query to obtain, for example, the number of diagnoses registered in an EHR related to the respiratory, digestive system...
It is for surveillance and statistical purposes.

thank you so much!

**Comment by kaicode** [comment]
Hi juanidepapi,

This would be a two step process:
1. Use a terminology server to select the SNOMED CT concepts of interest
2. Use an EHR/Patient repository to select patients with a matching diagnoses

I can help with the first part!


To create the SNOMED CT query I would recommend starting in a [SNOMED CT Browser](https://browser.ihtsdotools.org/). Using the International Edition to create this sort of high level query is fine.

Find a concept that best represents the type of finding or diagnoses you are interested in. Following your example I searched for "respiratory disorder" and found `50043002 |Disorder of respiratory system (disorder)|`.
<img width="1121" alt="Screenshot 2023-02-08 at 12 50 01" src="https://user-images.githubusercontent.com/2010517/217534462-920e1b2b-3023-48f4-addc-6e86b901dae6.png">

Make sure you select a concept with a (finding) or (disorder) tag in the name when searching for diagnoses.

Using the [ECL query language](http://snomed.org/ecl) we can select all the types of `50043002 |Disorder of respiratory system (disorder)|` in SNOMED CT using a [descendants of self constraint](https://confluence.ihtsdotools.org/display/DOCECL/6.1+Simple+Expression+Constraints) like this: `<<50043002 |Disorder of respiratory system (disorder)|`.

We can run that ECL query to fetch the matched concepts by expanding an intensional ValueSet in the FHIR API: [/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/<<50043002|Disorder%20of%20respiratory%20system%20(disorder)|](https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C%3C50043002%20|Disorder%20of%20respiratory%20system%20(disorder)|)

_Please note that the public Snowstorm instance (https://snowstorm.ihtsdotools.org/fhir) is for reference and testing purposes only. Please run your own instance of Snowstorm or another SNOMED CT FHIR terminology server for scripting/application development/production purposes._


Does that answer your question?

Kai

**Comment by kaicode** [comment]
If you look at the children of concept `362965005 |Disorder of body system (disorder)|` many of those may be of interest to you. http://snomed.info/id/362965005
<img width="424" alt="Screenshot 2023-02-08 at 13 01 32" src="https://user-images.githubusercontent.com/2010517/217537011-8d5469f4-a4e4-4b17-921f-59225c17900e.png">

**Comment by juanidepapi** [comment]
Hello Kai!.
Thank you very much for your answer.

I think I understood your explanation perfectly.
I'll put it to the test and let you know how it went
