### ISSUE TITLE
Refset expansion in ECL incomplete

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#48]
Running snowstorm develop@8d0d54c with Swedish edition loaded:
I tried expanding refsets using the refset API vs. ECL:
http://localhost:8080/MAIN%2FSNOMEDCT-SE/members?referenceSet=58191000052103&active=true&offset=0&limit=50
and got 76 members (which is correct), but
http://localhost:8080/MAIN%2FSNOMEDCT-SE/concepts?activeFilter=true&ecl=%5E58191000052103&offset=0&limit=50​
gives me 41 members...

**Comment by kaicode** [comment]
The member-of ECL selection will only return concepts where both the reference set member and concept are active. Perhaps your reference set member search is returning more results because there active members referencing inactive concepts?

**Comment by kaicode** [comment]
We have the Swedish Edition loaded here using the develop branch of Snowstorm and are getting 76 results back for both member and ECL requests.

**Comment by danka74** [comment]
I'm have the MAY19 pre-release loaded. Maybe that's the issue... I'll try to load the previous release.
/Daniel

**Comment by rorydavidson** [comment]
Yep, we're using International July 2018 and Swedish November 2018 are the results match across all reference sets for both different calls.

**Comment by danka74** [comment]
I tested Int July 2018 + SE Nov 2018 (both snapshot) and I got 3 members using ECL instead of 76 using the refset operations. Something is seriously fishy, seems like on my end.

**Comment by rorydavidson** [comment]
@danka74 what is the branch and import strategy that you've used? 
The one I've followed is (from a clean server):
- international snapshot imported onto MAIN
- new code system created for SE (on branch MAIN/SNOMEDCT-SE)
- SE snapshot imported onto MAIN/SNOMEDCT-SE

Still getting the results as expected.

**Comment by danka74** [comment]
@rorydavidson I updated to elasticsearch 6.5.4, reloaded everything, and now I have 76 members using both operations!
