### ISSUE TITLE
get only generic drugs

### ISSUE THREAD

**Issue by juanidepapi** [IHTSDO/snowstorm#482]
Hello.
My question is about how to get only generic drugs through ECL. Excluding trademarks.

Thank you so much!

**Comment by alopezo** [comment]
Hello, the "Clinical Drug" class of the the Drug Model are the equivalent to the generic drugs, and there are different ways to retrieve them:

Queries based on attributes:
<< 763158003 |Medicinal product| : 732943007 |Has basis of strength substance (attribute)| = *, [0..0] 774158006 |Has product name| = *

Queries based on hierarchy + semantic tag
<< 763158003 |Medicinal product|: {{ term = "(clinical drug)", type = fsn, dialect = en-us (prefer)}}

FHIR Expansions + Filter
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/<< 763158003 |Medicinal product|&filter=(clinical drug)

You can see an interactive example here: https://ihtsdo.github.io/iig-drug-classes/

Best regards

Alejandro

**Comment by juanidepapi** [comment]
Thank you very much Alexander!
I'm from Argentina too!

I will implement what you propose and comment on how it went.

Greetings!
