### ISSUE TITLE
Detail tab doesn't work after importing translation.

### ISSUE THREAD

**Issue by tmitanitky** [IHTSDO/snowstorm#488]
Hi,

After importing IPS Terminology refset file, I imported translation file merged into [empty RF2 snapshot archive](https://github.com/IHTSDO/snowstorm/issues/274#issuecomment-853785195) following ["Loading & updating SNOMED CT with local Extensions or Editions"](https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md).
My final RF2 snapshot archive with some translation is [ips-translation-ja.zip](https://github.com/IHTSDO/snowstorm/files/10833794/ips-translation-ja.zip).

![image](https://user-images.githubusercontent.com/40882114/221415182-abeefbf5-52f5-4b1a-bd34-01d76ee4d6e6.png)
I could select the local extension I made on 2023-02-26.

Searching and summary tab worked well, but in detail tab, "reference set" section did not show up. The waiting state continued and the arrows kept turning forever. That is tha case with the other concepts without translation.
![image](https://user-images.githubusercontent.com/40882114/221413328-91088309-af55-4a97-b616-99adee4d67ea.png)

The refset tab in the left column did not work either.
![image](https://user-images.githubusercontent.com/40882114/221415402-d9a85c43-4fa3-44d1-b09d-e4d71c6aac84.png)

In addition, other descriptions disapeared from Summary tab. The screenshot was showing the same concept just before loading my translation extension. There are three English descriptions but after loading my translation, the only new translation description showed as above.
![image](https://user-images.githubusercontent.com/40882114/221416576-83b5fe4e-4452-4ecb-9eea-dc85921622f0.png)

Is it because the file is not a language refset but only translation with empty rf2 file? Is there any possible solution?

Thanks.

**Comment by kaicode** [comment]
Hi @tmitanitky. The browser has not been thoroughly tested with the IPS Terminology so it may not work as expected. The browser is usually used with complete SNOMED CT editions.

Regarding the attached extension zip, I can see that it comprises of two descriptions with a `999991001000101` module. Usually an extension would contain a concept to represent the module. It's hard to say if this is causing the problem you are seeing with the browser but it's possible. Any javascript errors may give us more clues. The browser is written in fairly old technology using JQuery and unfortunately there is very little error handling so it's not very robust in unexpected situations.

A translation extension also usually contains a concept to represent the language reference set and also some reference set members to indicate description acceptability in the language reference set. The [extensions practical guide](https://snomed.org/extensions) may help.

**Comment by tmitanitky** [comment]
Thank you @kaicode .
I understand that the browser is targeting the full set and partial sets like IPS Terminology are not the intended target. I would like to try a little more with hints such as extensions practical guide. Thank you very much.

**Comment by kaicode** [comment]
I'll close this ticket for now but feel free to open it again, or to start an issue in the [browser project](https://github.com/IHTSDO/sct-browser-frontend) if you have any specific questions.
