### ISSUE TITLE
Snowstorm 7.12.0: Can't import International Snapshot

### ISSUE THREAD

**Issue by etasodjo2** [IHTSDO/snowstorm#494]
We've upgraded to Swagger 7.12.0, but can't seem to load SNOMED CT data.

We used to be able to do it following the instructions in loading-snomed.md, but this doesn't seem to work anymore.
GET/imports/{importsId} > shows "status":"FAILED".

Branch is set to "MAIN", "type" is set to "SNAPSHOT" and we're trying to upload the full .zip RF2 file of the 20220930 SCT International edition.

I see that POST/imports now has a new parameter, "filterModuleIds". I'm wondering if this parameter needs to be filled (and how) for the upload to work.

Thanks!

**Comment by kaicode** [comment]
Hi, what version of Snowstorm are you using please? Also, what is the error message in the logs when the import fails? That should give us more information about what might be wrong with the input.

**Comment by etasodjo2** [comment]
Hi, I'm sorry, I meant we're using Snowstorm 7.12.0. 
The error message we get is:
![image_480](https://user-images.githubusercontent.com/128499480/226650070-8a7d6311-54cb-4e45-98e0-f8e5ba352e09.png)

**Comment by kaicode** [comment]
The configuration of that import job looks fine. The empty moduleIds array is normal.
I will need to see the error from the Snowstorm log file to give any more suggestions on this issue. Everything looks okay from what you have provided.

**Comment by etasodjo2** [comment]
Thanks for your reply, @kaicode. In the end, it was a problem with ElasticSearch not running out of memory, which we have now solved. Feel free to delete this issue if possible.

**Comment by kaicode** [comment]
I'm glad you worked it out! Thanks for letting us know.
