### ISSUE TITLE
How to know if a concept is a descendant of another

### ISSUE THREAD

**Issue by juanidepapi** [IHTSDO/snowstorm#499]
hi guys.
I am trying to generate a diagnostic report for an EHR, grouped by body system.
For this I need to know which ecl query I must execute to check if a concept is ancestor of another.
That is, if concept A is a descendant of concept B.

thank you so much!

**Comment by kaicode** [comment]
To check if concept A is a descendant of concept B you could use the format `< ANCESTOR_CONCEPT AND DESCENDANT_CONCEPT`. For example:
```
< 49601007 |Disorder of cardiovascular system (disorder)| AND 234081006 |Aneurysm of vein (disorder)|
```
This will return the Aneurysm of vein concept only if it is a descendant of Disorder of cardiovascular system. This is the simplest ECL to run this test but if you need to check many body systems it may take a lot of API calls.

An alternative could be to fetch all the ancestors of a concept, then in your software you could check if any of the ancestors match one of the body systems you are looking for. All the ancestors of a concept can be fetched using the `>` operator, for example:
```
> 234081006 |Aneurysm of vein (disorder)|
```
This will return `49601007 |Disorder of cardiovascular system (disorder)|` and many other ancestor concepts.

As a final suggestion: there are many body systems listed as direct children of concept `362965005 |Disorder of body system (disorder)|`. You could fetch the intersection of those direct children and the ancestors of a concept as a way to lookup which body system any concept is part of. Using our Aneurysm of vein example again:
```
<! 362965005 |Disorder of body system (disorder)| AND > 234081006 |Aneurysm of vein (disorder)|
```
This returns `49601007 |Disorder of cardiovascular system (disorder)|` or whatever body system disorder that Aneurysm of vein is.

See [ECL documentation on intersections](https://confluence.ihtsdotools.org/display/DOCECL/6.4+Conjunction+and+Disjunction).

I hope that helps!
