### ISSUE TITLE
Security configuration

### ISSUE THREAD

**Issue by ronaldcornet** [IHTSDO/snowstorm#501]
https://github.com/IHTSDO/snowstorm/blob/master/docs/security-configuration.md
This reads: "Simply load SNOMED CT data and then switch on read-only mode using configuration option snowstorm.rest-api.readonly=false. In this mode all API functions which make changes to content are disabled, they are also hiden from the Swagger API documentation page."

Shouldn't this be " ...readonly=true" ? 
Further, notice the typo in "hiden".
Then it would be in line with https://github.com/IHTSDO/snowstorm/blob/master/docs/using-docker.md which states:
entrypoint: java -Xms2g -Xmx4g -jar snowstorm.jar --elasticsearch.urls=http://es:9200 --snowstorm.rest-api.readonly=true

**Comment by kaicode** [comment]
You are correct.

**Comment by kaicode** [comment]
Thank you for spotting and raising this. The security-configuration doc has been fixed.
