### ISSUE TITLE
Loinc support in snowstrom

### ISSUE THREAD

**Issue by rajayeswanth** [IHTSDO/snowstorm#502]
I have uploaded Loinc v2.72 into Snowstorm using the hapi-fhir cli and the upload is successful with only a few valuesets not found errors while saving the valuesets during the upload process

**{{url}} :- http://localhost:8080/fhir**

when I hit the API  {{url}}/CodeSystem?url=http://loinc.org
the output is as follows
{
    "resourceType": "Bundle",
    "id": "b9b0b9bb-e1a4-4c41-8194-6e20272b131b",
    "meta": {
        "lastUpdated": "2023-04-05T16:49:20.966+05:30"
    },
    "type": "searchset",
    "total": 2,
    "link": [
        {
            "relation": "self",
            "url": "http://localhost:8080/fhir/CodeSystem?url=http%3A%2F%2Floinc.org"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://localhost:8080/fhir/CodeSystem/loinc",
            "resource": {
                "resourceType": "CodeSystem",
                "id": "loinc",
                "url": "http://loinc.org",
                "name": "LOINC",
                "title": "LOINC",
                "status": "active",
                "publisher": "Regenstrief Institute, Inc.",
                "hierarchyMeaning": "is-a",
                "compositional": false,
                "content": "complete"
            }
        },
        {
            "fullUrl": "http://localhost:8080/fhir/CodeSystem/v3-loinc",
            "resource": {
                "resourceType": "CodeSystem",
                "id": "v3-loinc",
                "url": "http://loinc.org",
                "version": "3.0.0",
                "name": "LOINC",
                "title": "Logical Observation Identifiers, Names and Codes (LOINC)",
                "status": "active",
                "date": "2020-11-03T00:00:00+05:30",
                "publisher": "LOINC and Health Data Standards, Regenstrief Institute, Inc.",
                "compositional": false,
                "content": "not-present"
            }
        }
    ]
}

but when I'm hitting the other APIs like the following I'm unable to access any data:-

API:- {{url}}/CodeSystem/$lookup?system=http://loinc.org&code=99986-2
output:- {
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "diagnostics": "Code 'LP31755-9' not found for system 'http://loinc.org'."
        }
    ]
}

API :- {{url}}/ValueSet/$expand?url=http://loinc.org/vs/LL1162-8

output:- {
    "resourceType": "ValueSet",
    "id": "LL1162-8",
    "url": "http://loinc.org/vs/LL1162-8",
    "identifier": [
        {
            "system": "urn:ietf:rfc:3986",
            "value": "urn:oid:1.3.6.1.4.1.12009.10.1.333"
        }
    ],
    "version": "Beta.1",
    "name": "Quantity (5 answers, ord)",
    "status": "active",
    "publisher": "Regenstrief Institute, Inc.",
    "contact": [
        {
            "name": "Regenstrief Institute, Inc.",
            "telecom": [
                {
                    "system": "url",
                    "value": "https://loinc.org"
                }
            ]
        }
    ],
    "copyright": "This material contains content from LOINC (http://loinc.org). LOINC is copyright ©1995-2022, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc.",
    "expansion": {
        "id": "13c2e2b4-6a74-4076-89f4-3432696251f2",
        "timestamp": "2023-04-05T10:53:43+05:30",
        "total": 0,
        "offset": 0,
        "parameter": [
            {
                "name": "version",
                "valueUri": "http://loinc.org|3.0.0"
            },
            {
                "name": "displayLanguage",
                "valueString": "en"
            }
        ]
    }
}

in the above API I'm able to get URL, id and name but not able to get the data inside the valuset

any help would be appreciated

note:- I'm currently running the project in windows11 and using java version 11, elasticsearch version 7.10.0 and Maven 3

**Comment by kaicode** [comment]
I have tested the same lookups in a test environment and I can confirm that these operations should be working.

I think the issue you are experiencing may be caused by the fact that there are multiple LOINC versions loaded. This scenario has not been tested by us. This issue may be made worse by the fact that one of the LOINC versions listed in your code system listing has a version and one does not. Perhaps there is not good separation in the store which is causing unexpected behaviour. Unfortunately we do not have functionality to recognise the version of the LOINC package when it's loaded. Updating the code system with a version after loading will not update the existing content so is not advisable.

I would advise dropping your Elasticsearch indices and loading just one version of LOINC again. We could look at picking up the LOINC version automatically during loading in the future but this is not something that we have capacity to look at yet.
