### ISSUE TITLE
Mapping branches to API-FHIR versions

### ISSUE THREAD

**Issue by xgarcinuno** [IHTSDO/snowstorm#503]
Hi,

we have loaded 3 branches in snowstorm with:

- Snomed CT international edition (MAIN)
- Snomed CT spanish edition (MAIN/SNOMEDCT-ES)
- Spain extension (MAIN/SNOMEDCT-ES/SNS)

In API fhir we can find concepts from any extension, but when use the "version" parameter we can find concepts from International Edition and Spanish Edition and can't find any from Spain Extension.

The versions for branches are:

MAIN -> http://snomed.info/sct/900000000000207008
MAIN/SNOMEDCT-ES -> http://snomed.info/sct/449081005
MAIN/SNOMEDCT-ES/SNS -> ????? This should be http://snomed.info/sct/900000001000122104, but it don't work

The concept 900000001000122104 is:

{
  "conceptId": "900000001000122104",
  "active": true,
  "definitionStatus": "PRIMITIVE",
  "moduleId": "900000001000122104",
  "effectiveTime": "20150630",
  "fsn": {
    "term": "module for components of the National Extension for Spain (core metadata concept)",
    "lang": "en"
  },
  "pt": {
    "term": "module for components of the National Extension for Spain",
    "lang": "en"
  },
  "id": "900000001000122104",
  "idAndFsnTerm": "900000001000122104 | module for components of the National Extension for Spain (core metadata concept) |"
}

we are using snowstorm 7.12.0

should we use newer snowstorm version or include properties on concept 900000001000122104?

thanks and regards

**Comment by kaicode** [comment]
We usually start code system names with "SNOMEDCT" so it could have been "SNOMEDCT-SNS" but it should work with just "SNS".

**Comment by xgarcinuno** [comment]
Hi,

we have added that line in application.properties and we have restarted snowstorm server. The log shows:

CodeSystemConfiguration{name='Spain National Edition', shortName='SNS', module='900000001000122104', countryCode='es', owner='Ministerio de Sanidad'}

When we search for version "http://snomed.info/sct/900000001000122104" in FHIR-API the result is:

 Failed to call access method: org.snomed.snowstorm.fhir.services.FHIROperationException: No code system known with default module of 900000001000122104.

Thanks.

**Comment by kaicode** [comment]
Is "SNS" the `shortName` that appears against the Spain National Edition in the /codesystems listing in the native Snowstorm API?

**Comment by xgarcinuno** [comment]
In the /codesystems, the shortname  is "SNOMEDCT-ES-SNS".
We put the line:

codesystem.config.SNOMEDCT-ES-SNS=Spain National Edition|900000001000122104|es|Ministerio de Sanidad

and restart the snowstorm server. Then, we call the API FHIR using the param "version" with value "http://snomed.info/sct/900000001000122104" and .... it works!!!!

Thanks!!

**Comment by kaicode** [comment]
Great news! 😄

**Comment by kaicode** [comment]
@xgarcinuno I've added that working configuration to the default config for the next Snowstorm release.

**Comment by FJGL** [comment]
Hi.

Sorry for the mistake. 

Just to let you know that actually is an Extension not an Edition and we are using another one:

codesystem.config.SNOMEDCT-ES-SNS=Spain National Extension|900000001000122104|es|Ministerio de Sanidad
codesystem.config.SNOMEDCT-ES-SNS-MED=Spain Drugs National Extension|90000011000140108|es|Ministerio de Sanidad
