### ISSUE TITLE
Generated Delta Files in Snowstorm & -latest-state flag (Delta Generator tool)

### ISSUE THREAD

**Issue by Khaled-El-Mansoury-EG** [IHTSDO/snowstorm#507]
Hi all,

I've just had a question please.
[`docs/loading-snomed.md`](https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md#do-not-use-generated-delta-files) talks about not using generated delta files with Snowstorm:

## Do not use Generated Delta Files
**Do not attempt to import generated delta files into Snowstorm!**
Since Janurary 2022 the International Edition no longer contains RF2 delta files. There is a tool to generate delta files if required but Snowstorm can not currently import these because they can contain multiple states of SNOMED CT components. When importing generated delta files the import will complete but the content will be inconsistent. Instead use the SNAPSHOT import type when importing a new version of any release that does not contain delta files. Using a Snapshot import is slightly slower than a delta but will result in the same outcome.

I can see that this warning was added on the 10th February 2022 and a similar warning on the [17th February 2022 added to the `delta-generator tool`](https://github.com/IHTSDO/delta-generator-tool/commit/0ba96be451998858f06ead8af772b04cbf016f00):

### Snowstorm Warning
At this time the Snowstorm terminology server is not able to process the delta files created by this tool because there can be multiple rows for the same component. To update Snowstorm with a new version of a code system please use a snapshot import.

Since then, the tool has been updated with a [`-latest-state` flag option](https://github.com/IHTSDO/delta-generator-tool/commit/1a2f5497798e619e868cf138bd8133059a80eb5e) and the warning adjusted accordingly.

The warning on the `snowstorm` repo however remains the same. Does the `-latest-state` flag not fully resolve this issue?

Thanks in advance!

Khaled

**Comment by CoderMChu** [comment]
@Khaled-El-Mansoury-EG Well spotted. Yes it does solve the issue using -latest-state flag. We will update the snowstorm documentation accordingly. Thanks.

**Comment by kaicode** [comment]
Docs updated https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md#generated-delta-file-warning
