### ISSUE TITLE
valuesets not supporting write operations

### ISSUE THREAD

**Issue by rajayeswanth** [IHTSDO/snowstorm#515]
url:-  {{baseurl}}/ValuSet     //for creating new valueset 

response:-
status:-  401 unauthorised
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "Write operation not permitted."
        }
    ]
}

are there any configurations that need to be changed to support write operations in the Snowstorm server?

Any help would be appreciated!

**Comment by kaicode** [comment]
This should work unless Snowstorm is in read-only mode.
By default read-only is set to false meaning that writing is possible https://github.com/IHTSDO/snowstorm/blob/8.1.0/src/main/resources/application.properties#L17
I'm assuming you are using the latest, 8.1.0

**Comment by rajayeswanth** [comment]
Thanks for your response @kaicode 

But, I'm using the command "java -Xms2g -Xmx4g -jar snowstorm-8.1.0.jar" for running the snowstorm and I also tried running "java -Xms2g -Xmx4g -jar snowstorm-8.1.0.jar --snowstorm.rest-api.readonly=false"  but still getting the same response for write requests.
I also verified that the elastic search is not running in read-only mode.

I'm currently using the Snowstorm version:- 8.1.0

**Comment by rajayeswanth** [comment]
Thanks for ur response @kaicode

**Comment by kaicode** [comment]
I was just writing back when you closed the issue. I'll assume you have worked out the problem. 
Just shout if there is anything else!
