### ISSUE TITLE
valueset expand operation not working

### ISSUE THREAD

**Issue by rajayeswanth** [IHTSDO/snowstorm#522]
I have been trying to expand a valueset using the following API
{{baseurl}}/ValueSet/$expand?url=http://loinc.org/vs/LL1017-4

but I'm getting the response like this:-
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Resource  is not known"
        }
    ]
}

I don't know what is really causing this error, and list of valuesets and list of codesystems APis are working fine, I'm using the latest snowstorm release

and the error in command line is as follow:-

2023-06-13 07:06:49.529  WARN 435680 --- [nio-8080-exec-6] c.u.f.r.s.i.ExceptionHandlingInterceptor : Failure during REST processing: ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: Resource  is not known

below is the part of response of list of valuesets API:-

{
    "resourceType": "Bundle",
    "id": "4d47d540-3fcb-4549-aa63-25c8ec9674d9",
    "meta": {
        "lastUpdated": "2023-06-13T06:58:42.107+00:00"
    },
    "type": "searchset",
    "total": 11131,
    "link": [
        {
            "relation": "self",
            "url": "http://dev-terminology-be-lb-1604415439.ap-south-1.elb.amazonaws.com/fhir/ValueSet"
        }
    ],
    "entry": [
        {
            "fullUrl": "http://dev-terminology-be-lb-1604415439.ap-south-1.elb.amazonaws.com/fhir/ValueSet/LL1014-1",
            "resource": {
                "resourceType": "ValueSet",
                "id": "LL1014-1",
                "url": "http://loinc.org/vs/LL1014-1",
                "identifier": [
                    {
                        "system": "urn:ietf:rfc:3986",
                        "value": "urn:oid:1.3.6.1.4.1.12009.10.1.180"
                    }
                ],
                "version": "Beta.1",
                "name": "[PROMIS] 0-no pain|1|2|3|4|5|6|7|8|9|10-worst imag",
                "status": "active",
                "publisher": "Regenstrief Institute, Inc.",
                "contact": [
                    {
                        "name": "Regenstrief Institute, Inc.",
                        "telecom": [
                            {
                                "system": "url",
                                "value": "https://loinc.org"
                            }
                        ]
                    }
                ],
                "copyright": "This material contains content from LOINC (http://loinc.org). LOINC is copyright ©1995-2022, Regenstrief Institute, Inc. and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is available at no cost under the license at http://loinc.org/license. LOINC® is a registered United States trademark of Regenstrief Institute, Inc."
            }
        },.........................................]

**Comment by kaicode** [comment]
Have you tried filtering the list of ValueSets for that value set, rather than expanding it, like: 
`{{baseurl}}/ValueSet?url=http://loinc.org/vs/LL1017-4`

If the value set doesn't come up in the list then it's not been loaded correctly, or perhaps that value set was not in the package that's been loaded.

**Comment by rajayeswanth** [comment]
Firstly, Thanks for your support @kaicode.
After a lot of debugging, I just resolved the error. In the nginx logs, the query params of the APIs are not getting logged. But the Apis are working fine when I'm hitting the Apis using the IP address of the ec2 directly. So I thought there was an error with the cloud front or the load balancer configuration. After changing the configurations they are working fine.

Sorry for wasting your time without checking the logs in the first place.

**Comment by kaicode** [comment]
No worries at all! Glad you got it sorted out.
