### ISSUE TITLE
enquiry about codesystem lookup using name or display

### ISSUE THREAD

**Issue by rajayeswanth** [IHTSDO/snowstorm#524]
I'm wondering if there is any way to lookup the code system using the display name of the code, such that it returns all the codes containing the search term in its display name.

for example,
{{baseurl}}/CodeSystem/$lookup?system=http://snomed.info/sct&display=Diabities

just like,
{{baseurl}}/CodeSystem/$lookup?system=http://snomed.info/sct&code=73211009

**Comment by kaicode** [comment]
Yes, the HL7 FHIR API can be used to search SNOMED CT to find concepts by display name. 

The ValueSet expand operation can be used, with the implicit set containing all SNOMED CT codes (`http://snomed.info/sct?fhir_vs`), like this:
[{{baseurl}}/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&filter=diabetes](https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&filter=diabetes)

However, it's more common to search within a specific hierarchy, like Clinical findings or Procedures. For example to search within all Clinical findings (that includes disorders) an implicit value set with [ECL](http://snomed.org/ecl) can be used, like this:
[{{baseurl}}/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C404684003&filter=diabetes](https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C404684003&filter=diabetes)

Note that in Snowstorm the filter parameter allows multiple prefix search, for example "dia foot ul" can be used to find "Diabetic foot ulcer". All active synonyms are used to find matching concepts and the results are sorted by the shortest matching description first. The display term in the results is always the preferred term of the concept.
