### ISSUE TITLE
Question about custom concepts

### ISSUE THREAD

**Issue by MiguelF97** [IHTSDO/snowstorm#526]
Hello, I and my team are trying to modify some concepts from a snapshot that we've imported, and when I was messing with the PUT endpoint of concepts emerged some doubts that I would appreciate it if someone could answer them.

- Is it possible to add new/custom attributes to the request body when modifying a concept?

- Is it possible to add more than 1 preferred term to a concept?

- Is there a way to search for a group of modified concepts using some new/modified attribute on the concept request body? (This one is probably related to relationships between the concepts)

- Is there any documentation related to each attribute that is in the request body of a concept? 

Thank you in advance.

**Comment by kaicode** [comment]
While the Snowstorm API supports modifying and authoring concepts this should only happen in specific circumstances, when you intend to create a new SNOMED CT extension. [More information on extending SNOMED CT](https://www.implementation.snomed.org/authoring-tools).

- When using the Snowstorm API to add attributes those attributes must exist as a concept that has `762705008 |Concept model object attribute (attribute)|` as a parent. Extensions do not usually add new attributes, they usually use the attributes already defined in the International Edition and [Editorial Guide](http://snomed.org/eg).

- The rules of SNOMED CT dictate that it is only possible to have one preferred term per language reference set. There can be multiple acceptable terms in a language reference set but only one preferred term per concept.

- It is possible to search for concepts using the attributes with the [ECL search language](http://snomed.org/ecl). The [refinement examples section](https://confluence.ihtsdotools.org/display/DOCECL/6.2+Refinements) sounds relevant.

- Regarding documentation for attributes; there is an [overview](https://confluence.ihtsdotools.org/display/DOCEG/Attributes) in the SNOMED CT Editorial Guide and then more detail on specific attributes within specific domains, for example [Clinical Finding Attributes Summary](https://confluence.ihtsdotools.org/display/DOCEG/Clinical+Finding+Attributes+Summary). You can also find the [Machine Readable Concept Model Browser](https://browser.ihtsdotools.org/mrcm/) that lists all the domains of SNOMED CT along with all the attributes that can be used in each domain and all the concepts within the range of each attribute.

I hope that helps!
