### ISSUE TITLE
Error parsing HTTP request header

### ISSUE THREAD

**Issue by abhinayk991** [IHTSDO/snowstorm#527]
While loading RF2 files in the snowstorm using AWS EC2 t2.xlarge instance.

Getting an issue/error, please check the screenshots for further details:
2023-06-28 04:43:23.234  INFO 9484 --- [nio-8080-exec-3] o.apache.coyote.http11.Http11Processor: Error parsing HTTP request header

![Error parsing HTTp header](https://github.com/IHTSDO/snowstorm/assets/34411594/d04e000e-4b0d-40dc-9e34-0e88d5192fa6)

Please help us in resolving this issue.

**Comment by kaicode** [comment]
The log shows SNOMED CT is being imported into Snowstorm. The INFO message at the end shows that an unusual HTTP request has been made to the Snowstorm API. While this looks very unusual I don't think it's anything to worry about. This will not affect the import, just keep waiting for up to an hour for it to complete.
