### ISSUE TITLE
Add attributes to the custom code system

### ISSUE THREAD

**Issue by rayssamesquita** [IHTSDO/snowstorm#528]
Hello, I'm using the FHIR API to include some custom content, I can correctly import all the attributes there are included in the example. However, I would like to know if it is possible to include attributes that are not presented there. For example, if I wanted to include an column that represent if a property is active or inactive, would it be possible? If so, is there any documentation on how this should be done?

Thanks in advance.

**Comment by rayssamesquita** [comment]
The problem is that I want to include new columns into the properties.csv. For example, I want to include  the attritubutes version and active to each of my propeties. This is possible?

**Comment by kaicode** [comment]
This format is quite basic and does not allow version or active flags on properties. Snowstorm is primarily for SNOMED CT which is much more complex but even that does not expose a version or active flag for concept attributes when using the FHIR API. In fact I'm not sure that the FHIR spec for the Terminology module supports this? There is a mention of `property.subproperty` in the [CodeSystem lookup spec](https://www.hl7.org/fhir/codesystem-operation-lookup.html) but Snowstorm does not support this.
Snowstorm does have another API that does expose the attributes version and active flags but that is only for SNOMED CT, it does not support other codesystem types.
