### ISSUE TITLE
Getting error -Importing a new International Edition 

### ISSUE THREAD

**Issue by MaryamRazavi** [IHTSDO/snowstorm#536]
I am trying to import a RF2 file in snowstorm but I got this reponse: 
{
  "status": "FAILED",
  "type": "SNAPSHOT",
  "internalRelease": false,
  "moduleIds": [],
  "createCodeSystemVersion": true,
  "branchPath": "MAIN"
}
{
  "status": "WAITING_FOR_FILE",
  "errorMessage": "string",
  "type": "DELTA",
  "internalRelease": true,
  "patchReleaseVersion": 0,
  "moduleIds": [
    "string"
  ],
  "createCodeSystemVersion": true,
  "branchPath": "string"
}

and also, 
when I tried to do it via curl:
curl -X POST --header 'Content-Type: multipart/form-data'                                                                              --header 'Accept: application/json' -F 'file=@SnomedCT_InternationalRF2_PRODUCT                                                                             ION_20230630T120000Z.zip;type=application/x-zip-compressed'  'http://nixv1te.sos                                                                             .local:8080/snowstorm/imports/9157bcd2-2dd1-4a2a-acea-55320de8dbb1/archive'
curl: (26) couldn't open file "SnomedCT_InternationalRF2_PRODUCTION_20230630T120                                                                             000Z.zip"

I followed the instruction on github but seems something is not correct. is there any way to understand what is wrong?

how can I resolve this problem?

**Comment by kaicode** [comment]
Hi @MaryamRazavi, no problem, let's work through it.
It looks like you have created the import configuration but the step to upload the file with curl is not working.
It looks like curl can not find the file that needs uploading. After the @ sign you have provided just the filename without a file path so check that the file is in the same directory/folder as where you are running the command from.

**Comment by MaryamRazavi** [comment]
Hi @kaicode, Thank for answering me. The problem is we are using Putty  and I dont know how to run that from the folder I have the file! :(

**Comment by kaicode** [comment]
Using a complete file path to the RF2 zip file should also work.

**Comment by MaryamRazavi** [comment]
I have created an import job in snowstorm and used the ID and the used this curl: curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F 'file=@C:\Users\smri01\Downloads\SnomedCT_InternationalRF2_PRODUCTION_20230630T120000Z.zip  'http://nixv1te.sos.local:8080/snowstorm/imports/05a3fa14-fbee-4f78-9bf9-84a1afedca7f/archive'
But nothing happned, I don't see any log in Putty.

**Comment by kaicode** [comment]
The file upload is quite large, around 500MB. It may take some time.
You should be able to check the status of the update using:
```
curl http://nixv1te.sos.local:8080/snowstorm/imports/05a3fa14-fbee-4f78-9bf9-84a1afedca7f
```

**Comment by MaryamRazavi** [comment]
> The file upload is quite large, around 500MB. It may take some time. You should be able to check the status of the update using:
> 
> ```
> curl http://nixv1te.sos.local:8080/snowstorm/imports/05a3fa14-fbee-4f78-9bf9-84a1afedca7f
> ```
Hi,
"status": "WAITING_FOR_FILE", is that something we are expecting to see?

**Comment by kaicode** [comment]
- When the import is created, using `POST /imports`, then the status will be `WAITING_FOR_FILE`.
- Once the file has been uploaded, using `POST /imports/{uuid}/archive`, the import will start and the status will be `RUNNING`.
- About an hour after starting the import should complete successfully, then the status will be `COMPLETED`.
- If the import fails for any reason the status will be `FAILED` and there will be additional information about the issue in the logs.

**Comment by kaicode** [comment]
Your curl statement may have an issue, I can see there is no closing quote after the file path.

**Comment by MaryamRazavi** [comment]
> Your curl statement may have an issue, I can see there is no closing quote after the file path.
It should be like this right?
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F 'file=@C:\Users\smri01\Downloads\SnomedCT_InternationalRF2_PRODUCTION_20230630T120000Z.zip'  'http://nixv1te.sos.local:8080/snowstorm/imports/81546f63-a799-4ac5-94ea-f10408468622/archive'

then this is what I can see in putty:
[developer@nixv1te ~]$ curl -X POST --header 'Content-Type: multipart/form-data'                                 --header 'Accept: application/json' -F 'file=@C:\Users\smri01\Downloads\SnomedC                                T_InternationalRF2_PRODUCTION_20230630T120000Z.zip'  'http://nixv1te.sos.local:8                                080/snowstorm/imports/0d340464-e729-476d-96f3-a44aab91922f/archive'
curl: (26) **couldn't open file** "C:\Users\smri01\Downloads\SnomedCT_InternationalR                                F2_PRODUCTION_20230630T120000Z.zip"

this what I can see in Swagger UI when I tried to upload the file in via snowstorm:
{
  "status": "RUNNING",
  "type": "SNAPSHOT",
  "internalRelease": false,
  "moduleIds": [],
  "createCodeSystemVersion": true,
  "branchPath": "MAIN"
}
I'm waitig to see if this process will be completed or failed. but I tried it yesterday and after a long time, it failed!

**Comment by MaryamRazavi** [comment]
I will just mention that I have tried to upload the same file in another server/ local host and everything was fine and I got no error. I'm wondering if this problem has something to do with this spesific server?!

**Comment by kaicode** [comment]
Shall we have a quick call to sort it out? I'm on Slack.

**Comment by MaryamRazavi** [comment]
We are not using Slack on work laptop. Is there any other possibility to have a call with skype? or teams?

**Comment by kaicode** [comment]
This import issue is now resolved.
