### ISSUE TITLE
Getting started -> Start Snowstorm: Missing and conflicting info

### ISSUE THREAD

**Issue by o-l-a-v** [IHTSDO/snowstorm#557]
On the [Getting Started -> Start Snowstorm](https://github.com/IHTSDO/snowstorm/blob/master/docs/getting-started.md#start-snowstorm) I got two comments:

1. Missing info: It does not say how to start Snowstorm the first time, without read mode.
   * Not everyone works with Linux, Elasticsearch and Snowstorm every day. :)
2. Conflicting info: You override the memory options (`-Xms2g -Xmx4g`) with different arguments than what you sid one should set in the [Install Elasticsearch](https://github.com/IHTSDO/snowstorm/blob/master/docs/getting-started.md#install-elasticsearch) step (`-Xms4g -Xmx4g`).
   * Which is it?

**Comment by kaicode** [comment]
Either will work fine. The first will allocate 2g of ram, but allows the memory usage to grow to 4g. The second version assigns 4g straight away. Both limit the memory to 4g.

**Comment by abelardy** [comment]
In case it helps anybody else labouring to get a Snowstorm server to play with up and running, here's the latest result of my own labours: a detailed guide (with scripts) for getting one up and running under VirtualBox in a couple of hours:

[Snowstorm 10.2.1 Install and Test (Ubuntu 22.04.4LTS) 20240503.zip](https://github.com/IHTSDO/snowstorm/files/15200512/Snowstorm.Install.and.Test.22.04.4LTS.20240503.zip)

**Comment by kaicode** [comment]
Thanks @abelardy!
We also now have the Snowstorm-Deploy project that aims to automate the installation and config of Elasticsearch and Snowstorm on various platforms via script. Just Ubuntu 20 is there so far.
https://github.com/IHTSDO/snowstorm-deploy
