### ISSUE TITLE
Do you all use the Terminology server to search Concepts as in the SnomedSearchDemo ? (Quick answer: Yes)

### ISSUE THREAD

**Issue by marceloabrumet** [IHTSDO/snowstorm#558]
Do you all use the Terminology server to search Concepts as in the SnomedSearchDemo ?

SnomedSearchDemo: https://ihtsdo.github.io/snomed-ui-examples/

So my real question would be: is this the intended way to use the Snowstorm server? I mean, is the server prepared to receive thousands of requests to find a term each time a doctor types or deletes a letter on the search fields of their software? Have you ever run into performance problems and how could we avoid them? What kind of machine should we use to deploy our server?

**Comment by kaicode** [comment]
Yes supporting user data entry, as shown in the UI Demo, is one of the intended use cases of the [Snowstorm FHIR API](https://github.com/IHTSDO/snowstorm/blob/8.3.0/docs/using-the-fhir-api.md). I would recommend a 16GB server with SSD running Ubuntu or another debian linux. Assign 6GB to Elasticsearch, 5GB to Snowstorm, leave the rest for OS level disk caching. It's possible to run Snowstorm on other platforms but it's deployed most often like this.

Some general advice on performance: 
- Have a minimum search string length of three and only fetch the number of concepts that you will present to the user, probably 10 or 15
- Perform load testing on your setup to help estimate the amount of traffic it can support. 
- Snowstorm and Elasticsearch are horizontally scalable so take advantage of this if it fits in your architecture. 
  - _Note: If Snowstorm is being used as a SNOMED CT Edition authoring platform there must be only one instance._
- No Terminology Server can support all users nationally. If designing a national scale service consider deploying a terminology server per region or hospital group.

**Comment by kaicode** [comment]
I am currently developing a Snowstorm Lite application that takes a fraction of the memory and is faster. The downside is that it will only host one release of SNOMED CT at a time. That will be made public on GitHub by the end of the year.
