### ISSUE TITLE
Incomplete swagger API

### ISSUE THREAD

**Issue by ChrysmOre** [IHTSDO/snowstorm#56]
Upon first running and inspecting Swagger at localhost I was confused not to find the /import endpoint mentioned in the docs. After importing snomed data via the command line a host of other endpoints were added. Where before there were only GET endpoints for retrieve etc afterwards there were many more including create, delete etc and the aforementioned imports endpoint. Upon returning today after restarting my laptop the api has reverted to the initial incomplete state. The snomed data is still present and the endpoints that are there work correctly.

**Comment by ChrysmOre** [comment]
false alarm - had accidentally left 'readonly' tag set to true

**Comment by kaicode** [comment]
Hi @ChrysmOre. Oh, glad you found it! I was about to mention the readonly flag
https://github.com/IHTSDO/snowstorm/blob/3.0.3/src/main/resources/application.properties#L14
Cheers, Kai
