### ISSUE TITLE
I would like to see the incoming HTTP requests in the snowstorm's docker container logs.

### ISSUE THREAD

**Issue by marceloabrumet** [IHTSDO/snowstorm#562]
Can I change logging level in the snowstorm docker container? 

I would like to see the incoming HTTP requests in the snowstorm's docker container logs. At this moment I can only see this:

![image](https://github.com/IHTSDO/snowstorm/assets/132668065/072a9550-704e-46e5-a15a-2faa77134c08)

Thanks ;)

**Comment by kaicode** [comment]
Update the docker-compose file adding logging configuration to the snowstorm entrypoint.
This can be added to the entrypoint:
```
--logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
```
The whole line would look like this:
```
    entrypoint: java -Xms2g -Xmx4g -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://es:9200 --logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
```
After starting the containers all http requests should be logged like this:
```
2023-10-24 12:05:18 2023-10-24 16:05:18.768 DEBUG 1 --- [io-8080-exec-10] o.s.web.servlet.DispatcherServlet        : GET "/version", parameters={}
2023-10-24 12:05:18 2023-10-24 16:05:18.774 DEBUG 1 --- [io-8080-exec-10] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
```

**Comment by marceloabrumet** [comment]
Hi Kai, thanks a lot for your answer! That's exactly what I want. 

Now my docker looks like this:
![image](https://github.com/IHTSDO/snowstorm/assets/132668065/ee64e13e-cfb6-43c5-9f2c-021ef941db45)

Unfortunately, I'm having 2 problems:

1. When I make a request to the REST API the parameters are being masked:
![image](https://github.com/IHTSDO/snowstorm/assets/132668065/7feeb2d2-3ba0-45cf-a253-5190d7815bf4)

2. When I make request to the FHIR API I get nothing on the console.

**Comment by kaicode** [comment]
Snowstorm is not designed to do this. We log HTTP traffic using nginx as a web proxy within a standard Ubuntu server. 

It looks possible to configure docker to use a proxy server: https://docs.docker.com/network/proxy/
There are docker images that can log HTTP requests, perhaps one of those can be set up as the proxy, I'm not sure - I have not tried this.
