### ISSUE TITLE
effectiveTime

### ISSUE THREAD

**Issue by kaboyles** [IHTSDO/snowstorm#566]
Hello,
We are between service providers and we have come up against a problem with effective time on our local snowstorm server.  See detailed explanation attached.  We are running snowstorm version 7.2 and they are stating this is a visual problem with snowstorm that can be fixed by upgrading.  Just wanted another opinion.  I see fix for MAINT-1743 that was released in 7.10.0.  Do you think we are hitting this or any other visual problem... or something else, likely on our side.

https://jira.ihtsdotools.org/browse/MAINT-1743

[effective time.docx](https://github.com/IHTSDO/snowstorm/files/13272463/effective.time.docx)

Thanks,
Kim

**Comment by jmidtgaa** [comment]
Hi,
Service provider tried to reproduce in version 8.3 on ubuntu 22LTS.
We've also tried in latest docker (supplied compose).

It's not present in either. So not an issue in recent releases.

//Johannes

**Comment by kaicode** [comment]
I don't think this is a visual problem. 

- The concept 367481000202103 is not included in the 2023-10-15 release in the SNOMED International Daily Build and (Authoring Platform):
  - [Concept 367481000202103 not found in the 2023-10-15 release branch on the SI daily build server](https://dailybuild.ihtsdotools.org/snowstorm/snomed-ct/MAIN/SNOMEDCT-NO/2023-10-15/concepts/367481000202103)
- but the same concept is included in that release in the ehelse daily build server:
  - [Concept 367481000202103 is found in the 2023-10-15 release branch on ehelse server](https://dailybuild.terminologi.ehelse.no/snowstorm/snomed-ct/MAIN/SNOMEDCT-NO/2023-10-15/concepts/367481000202103)

What was the procedure to get the 2023-10-15 release into the ehelse daily build server?

**Comment by kaboyles** [comment]
Thanks, Kai!  I have asked the engineer to respond directly in this ticket.

**Comment by jmidtgaa** [comment]
Thanks,

It's been an occational problem since [#318](https://github.com/IHTSDO/snowstorm/issues/318) when we configured dailybuild import downloaded from AWS Bucket. Not sure if its the rollback or branch-merge thats causing it.

The process described do follow 1-4 (using snapshot in 3). 
Question, the "1. disable dailybuild": Does that involve setting `daily-build.delta-import.enabled=false` and restart server? or is it sufficient to remove the local delta-files? (we're doing mv SNOMEDCT-NO/* archive so the folder is empty and nothing to import). And then the re-enable is when new files arrive next morning. Is this an unsafe shortcut?

//Johannes

**Comment by kaicode** [comment]
Hi @jmidtgaa 

An easy way to switch off the daily-build import is using the API at the codesystem level:
- Get the codesystem details `GET /codesystems/SNOMEDCT-NO`
- Modify the codesystem details, change the `dailyBuildAvailable` flag to `false`
- Send the codesystem details back to the API `PUT /codesystems/SNOMEDCT-NO`
This will stop the dailybuild process running for this codesystem. The flag can be set back to true to enable the scheduled process again. This may give you better control but it's up to you.

After disabling the dailybuild import and using the dailybuild rollback function it's possible to check that the content has rolled back correctly using the authoring-stats endpoint, as you suggested. 

An even more thorough way to check that the dailybuild rollback has been successful is to run a delta export of unversioned content and check that the TSV files within the exported zip only have header lines and no rows of data.

To run a delta export:
- `POST /exports` with payload: `{"branchPath": "MAIN/SNOMECT-NO", "type": "DELTA"}`
- The URL in the Location Header from the HTTP response is the newly created export configuration. Add `/archive` to this URL to download the export zip file.

**Comment by jmidtgaa** [comment]
Thanks a lot, @kaicode. 
Very clarifying (and much easier to partially script).

@kaboyles think the case is ready to close.

//J

**Comment by kaboyles** [comment]
We used this procedure and it worked.  Close case.

Thanks!!

**Comment by kaicode** [comment]
Great news. Thanks for reporting back @kaboyles.
