### ISSUE TITLE
Documentation is not up to date for version 9.2.0

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snowstorm#573]
The Getting Started documentation does not reflect the version of Elasticsearch or other changes that are required to run Snowstorm version 9.2.0.

I would recommend using Snowstorm 8.3.0 until this is resolved.

**Comment by CoderMChu** [comment]
@kaicode There is no ES version change in 9.2.0. It is still on ES 7.10.2. ES8 upgrade will be released in snowstorm 10.0.1

**Comment by kaicode** [comment]
Ah! The production version in SI environments is 10.0.1. I've made a bad assumption. I'll close this. Thanks for confirming.
