### ISSUE TITLE
Parents endpoint seems to provide ancestors in response

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#58]
Hi all,

The parents endpoint seems to provide the ancestors in its response. As far as I understand the ECL query system, these two queries should give the same response;
- /browser/MAIN/concepts/19431000/parents?form=inferred
- /MAIN/concepts?ecl=>!19431000

Am I missing something (ie. direct parents != inferred parents), or is the parents endpoint misbehaving?

Best regards,
Sander

**Comment by danka74** [comment]
Hi Sander,
I get just the (direct) parents, running 3.1.0-SNAPSHOT, develop branch pulled earlier today, and the same using any of the two calls above.
/Daniel

**Comment by mertenssander** [comment]
Hi Daniel,
Reading your comment, I realized I was calling the company test server, which runs an older version. I will repeat my test tomorrow with a fresh import of the international edition and snowstorm 3.0.3.
I will post my findings here. Sorry for the confusion.
