### ISSUE TITLE
Elasticsearch unhealthy, removing healthcheck will exit elasticsearch (Docker Compose)

### ISSUE THREAD

**Issue by StephanMeijer** [IHTSDO/snowstorm#59]
```
Attaching to snowstorm, elasticsearch
elasticsearch    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch exited with code 137
```

**Comment by mertenssander** [comment]
Hi @StephanMeijer - Have you made sure that your docker service has enough memory? I have run into this exact error message before when creating the elasticsearch container, and resolved it by allocating >6Gb memory to docker. In addition to this, I believe the health check times out after 60 seconds - this might be too short for an initial setup, but should result in an unhealthy container, not into a crashed container.

**Comment by 7opf** [comment]
The issue for me was related to Docker on WSL2: https://github.com/docker/for-win/issues/5202

**Comment by kandascan** [comment]
> The issue for me was related to Docker on WSL2: [docker/for-win#5202](https://github.com/docker/for-win/issues/5202)

I fix the same issue by:
open powershell
wsl -d docker-desktop
echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-docker-desktop.conf
Restart docker-desktop
