### ISSUE TITLE
Own extension in FHIR CodeSystem

### ISSUE THREAD

**Issue by liquid36** [IHTSDO/snowstorm#604]
Hi!
I have my own extension loaded into snowstorm.  I set the codesystem in `application.properties` like this:

```
codesystem.config.SNOMEDCT-TEST=TEST Edition|12345678899005645|ar|TEST Enterprise
```
Where _12345678899005645_ is my module conceptId. 

(I could see it in the log)

However, when i request the FHIR codesystem url (http://localhost:8080/fhir/CodeSystem?_format=json), i got this response:

```
{
    "fullUrl": "http://localhost:8080/fhir/CodeSystem/sct_null_20240601",
    "resource": {
        "resourceType": "CodeSystem",
        "id": "sct_null_20240601",
        "url": "http://snomed.info/sct",
        "version": "http://snomed.info/sct/null/version/20240601",
        "name": "SNOMED_CT",
        "title": "SNOMED CT release 2024-06-01",
        "status": "active",
        "date": "2024-06-01T00:00:00+00:00",
        "publisher": "SNOMED International",
        "hierarchyMeaning": "is-a",
        "compositional": true,
        "content": "complete"
    }get
}
```

The version dates corresponds to my extensions releases.

What i missing? Are there any other configurations to link an snowstorm codesystem to FHIR?

**Comment by kaicode** [comment]
Double check that the `shortname` of your codesystem in the Snowstorm `/codesystems` listing matches the `SNOMEDCT-TEST` name in your config.

**Comment by liquid36** [comment]
Great! I had to rename the codesystem name and it worked now.


```
codesystem.config.TEST=TEST Edition|12345678899005645|ar|TEST Enterprise
```

thanks.
