### ISSUE TITLE
No release package is set for version

### ISSUE THREAD

**Issue by Eneuman** [IHTSDO/snowstorm#607]
Hi

I got a error in the logs after doing a upgrade on a codesystem and I'm just wondering what the error message means and if I did something wrong? Any help would be greatly appriciated.

This is what I did.
1) I started with a clean elc
2) I imported the SNAPSHOT version of Snomed INT 20230131
3) I imported the SNAPSHOT version of Snomed SWE Edition 20230531 (dependent on INT 20230131)
4) I imported the SNAPSHOT version of Snomed INT 20230731
5) I upgraded the SNOMED-SE Code system to version 20230731

In the log I got this error message when I upgraded:
`ERROR 1 --- [pool-3-thread-2] o.s.s.c.d.s.CodeSystemUpgradeService     : No release package is set for version CodeSystemVersion{shortName='SNOMEDCT', effectiveDate=20230731}`

**Comment by kaicode** [comment]
You didn't do anything wrong. This message should probably be a warning, it's safe to ignore.

It's related to keeping track of what SNOMED RF2 release package was used to import the International Edition and should be used as a dependency when performing some operations on the extension. This is related to authoring and not needed when using Snowstorm as a general terminology server for read/query operations.

**Comment by Eneuman** [comment]
Thank you for the explanation!
I'll close this issue :)
