### ISSUE TITLE
Loading Release Snapshot: Via REST

### ISSUE THREAD

**Issue by StephanMeijer** [IHTSDO/snowstorm#61]
Issue: no suggested endpoint in Swagger found.

**Comment by kaicode** [comment]
Hi @StephanMeijer 
Please use this page in swagger on a local deployment:
http://localhost:8080/swagger-ui.html#!/Import/createImportJobUsingPOST

<img width="1399" alt="Screenshot 2019-08-12 at 14 22 21" src="https://user-images.githubusercontent.com/2010517/62868122-cbebdb80-bd0c-11e9-866b-8d5e3aca1148.png">

**Comment by StephanMeijer** [comment]
`Import : RF2` didn't show up first, now it magically shows up..

**Comment by kaicode** [comment]
You might have been in readOnly mode? The import stuff is hidden then.
https://github.com/IHTSDO/snowstorm/blob/4.1.0/src/main/resources/application.properties#L16
Glad it's working 😸

**Comment by StephanMeijer** [comment]
Maybe an idea to document this property?
