### ISSUE TITLE
ECL versión supported

### ISSUE THREAD

**Issue by xgarcinuno** [IHTSDO/snowstorm#610]
Hi,

In application's docs (https://github.com/IHTSDO/snowstorm) ECL v2.0 is supported.
Latest ECL version is 2.2 (https://confluence.ihtsdotools.org/display/DOCECL).
Snowstorm uses ECL Parser (https://github.com/IHTSDO/snomed-ecl-parser) and its latest version is 3.1.0.

How can we get the ECL version supported by snowstorm? Is there any service o method in API?

thanks and regards.

**Comment by kaicode** [comment]
The Snowstorm README is up to date, the currently supported ECL version is 2.0. There is no API method that returns the ECL version. The documentation is the best place to find out. 

The versioning of the ECL parser has started to drift away from the language version toward semantic versioning based on Java requirements etc. I will have a discussion with the tech team to check the intention here.

**Comment by xgarcinuno** [comment]
Thanks for your reply
