### ISSUE TITLE
Searching with some characters gives 0 results

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#62]
Dear Snowstorm,
when using the search interfaces (e.g. findConcepts, search) and including some characters in the term filter snowstorm gives 0 results even though descriptions with those characters exist in SNOMED CT. Examples of such characters are comma (,) and percent sign (%), could be more, but full stop (.) and parenthesis (() work fine.
E.g.: http://localhost:8080/MAIN/concepts?term=anemia%2C&offset=0&limit=50

**Comment by kaicode** [comment]
I just noticed a similar issue. Searching for "Spinal fusion of atlas-axis" matches nothing unless the hyphen is replaced with a space.
I'll look into this.
