### ISSUE TITLE
NullPointerException : unable to invoke io.kaicode. because latest is null

### ISSUE THREAD

**Issue by bomsiwor** [IHTSDO/snowstorm#625]
I'm trying to install and setup the Snowstorm using Docker by following the installation guide on the documentation.
But after loading the data by `import archive`, 
The Browser show nothing, no releases option in dropdown or neither the version.

When i checked on Snowstorm container logs, it gives me this error.

![image](https://github.com/user-attachments/assets/2dfa7bdb-0c7c-4971-8db8-f010d4cea7c5)

Is there any steps that i had missed?
Can you help us ?

Thanks in advance

**Comment by kaicode** [comment]
It sounds like the import may not have been successful. What does the log show around the time of the import completing?

**Comment by bomsiwor** [comment]
OK. I am captured more error arround the import, maybe it helps you to found the cause.

![image](https://github.com/user-attachments/assets/0936bf04-cbac-498a-9be9-b2730ac7b618)
![image](https://github.com/user-attachments/assets/170d5cf5-dc02-4fe1-84e1-2548402bb0d6)

**Comment by kaicode** [comment]
Good news, thanks for letting us know.
