### ISSUE TITLE
Difference between ECL query ^ and refset members endpoint

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#63]
Hi all,

During a recent testing session, we received a different number of items from an ECL query requesting refset members and the refset members endpoint.

I am running the server in docker containers (docker CE 19.03.1, hostOS CentOS). All is responsive and appears to be complete. I have just reinstalled everything with the new 4.1.0 snowstorm version to verify. In chronological order, I run:
- Elasticsearch 6.5.4
- Snowstorm built from github source, tried both 3.0.3 and 4.1.0
- Loaded Netherlands edition, task was reported as successful
- Loaded Dutch patient friendly, task was reported as successful
- Loaded GMDN, task was reported as successful

/MAIN/members?referenceSet=2581000146104&offset=0&limit=50
-> returns "total": 3459
/MAIN/concepts?ecl=%5E2581000146104&offset=0&limit=50
-> returns "total": 3414
Looking at the RF2 file, the first (3459) appears to be correct. Both 3.0.3 and 4.1.0 show the same response. Can anyone explain this discrepancy? I would of course be happy to provide further information if required.

Best regards,
Sander

**Comment by kaicode** [comment]
Hi @mertenssander,

Thanks for getting in touch. 

In Snowstorm ECL queries will only ever return active concepts and only active reference set members are included in the "^" member clause. On the other hand in the reference set member search members can be returned even if the reference set member is inactive or if the referencedComponent is inactive.

Could you check to see if you have 45 members in your member search which are either inactive or have inactive referenced component concepts?

I hope this helps.

Kind regards,
Kai

**Comment by mertenssander** [comment]
Hi @kaicode ,

Many thanks for your quick reply!
We were unaware of this difference in behavior. There are indeed 45 members in the refset with 'active: false'. I remember using the active filter in the swagger UI during testing, but cannot reproduce this in 4.0.1; might be a fixed bug or a faulty memory on my side.
Thank you for clarifying this!

Best regards,
Sander

**Comment by kaicode** [comment]
Thanks for confirming about the data Sander. Glad it's working! 😄
