### ISSUE TITLE
Pagination error for LOINC codes - IllegalStateException: Object builders can only be used once

### ISSUE THREAD

**Issue by albert-t25** [IHTSDO/snowstorm#638]
I've run into a strange problem when trying to paginate over LOINC codes. I can successfully call http://localhost:8080/fhir/ValueSet/$expand?url=http://loinc.org?fhir_vs&count=1000&offset=1000, but as soon as the offset goes to 10,000 I get an error. So http://localhost:8080/fhir/ValueSet/$expand?url=http://loinc.org?fhir_vs&count=1000&offset=10000 would give "IllegalStateException: Object builders can only be used once".

The same end-point works fine for SNOMED codes, so http://localhost:8080/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&count=100&offset=300000 is working fine.

Any idea?

Thank you

**Comment by kaicode** [comment]
It looks like this was bug was introduced during the Snowstorm Elasticsearch 8 upgrade. I'm putting a fix together.

**Comment by kaicode** [comment]
There is a LOINC pagination fix available on this branch: https://github.com/IHTSDO/snowstorm/tree/ISTO-125
I will raise a PR but that process may take some time.

**Comment by kaicode** [comment]
PR here https://github.com/IHTSDO/snowstorm/pull/639

**Comment by albert-t25** [comment]
Thank you, appreciated

**Comment by albert-t25** [comment]
Tested the fix from https://github.com/IHTSDO/snowstorm/tree/ISTO-125 and it worked perfectly
