### ISSUE TITLE
Tryng to import file 600MB

### ISSUE THREAD

**Issue by jpsalleras** [IHTSDO/snowstorm#69]
I am trying to import a 600mb file and it returns the following error

org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: snowstorm

How can configure tomcat to allow bigger files ?

thnks

**Comment by kaicode** [comment]
Hi @jpsalleras,

There is a Spring Boot setting you can update to tell Tomcat to increase the limit.
It's mentioned here: https://github.com/IHTSDO/snowstorm/blob/master/src/main/resources/application.properties#L83

You could either:
-  create an `application.properties` file in the same directory as the snowstorm jar containing:
```
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
```
- OR start the snowstorm jar with extra parameters like:
`java -jar snowstorm.jar --spring.servlet.multipart.max-file-size=1000MB --spring.servlet.multipart.max-request-size=1000MB` ... you probably have -Xmx params and other too.

I hope this helps!

Kai

**Comment by jpsalleras** [comment]
Work great!

Thanks !

Juan
