### ISSUE TITLE
Feature request; Selecting for a specific language reference set within a language

### ISSUE THREAD

**Issue by StephanMeijer** [IHTSDO/snowstorm#72]
>Selecting Preferred Terms or Fully Specified Names for a chosen language is implemented but selecting for a specific language reference set within a language is not yet implemented. Feel free to raise an issue for this. I would like to gauge the interest from others for this feature.

\- @kaicode 

Would be useful on Dutch Patient-Friendly terms and normal Dutch terms.

**Comment by danka74** [comment]
Swedish NRC seconds Stephan's request.

**Comment by kaicode** [comment]
This will be in the next RC release tomorrow using Accept-language header with a value like `en-X-0000000` where `en` is the language code the number is a language reference set. This will affect the FSN and PT returned in search results. The content matched in the search results can be controlled with the `preferredOrAcceptableIn` parameter on the concept and description searches.

**Comment by kaicode** [comment]
The RC is in master. I'll publish it as a release once our UAT testing is completed.

**Comment by kaicode** [comment]
This is implemented in [Snowstorm release 4.7.1](https://github.com/IHTSDO/snowstorm/releases) which has just been published after completing testing.

The concept search endpoint GET /{branch}/concepts now includes selection criteria parameters such as `preferredIn`, `acceptableIn` and `preferredOrAcceptableIn`. These can be used to require matched descriptions to be preferred or acceptable in a specific language reference set.

The Accept-language request header on every endpoint can be used to control which language or language reference set is used to select the Prefered Term included in the response. This has no effect on which concepts are included in the results, just which FSN/PT to return.

Kind regards,
Kai
