### ISSUE TITLE
Language filter don't work

### ISSUE THREAD

**Issue by liquid36** [IHTSDO/snowstorm#73]
Hi,
I want to make a search descriptions   by filtering spanish language. Something like this:

![image](https://user-images.githubusercontent.com/3813270/64928004-a446d200-d7e8-11e9-86f2-b2c76b20b03b.png)

However, none language filter is applied.

More over, i look what the Snomed Browser do and I can't found the difference. I navigated to the [swagger page](https://browser.ihtsdotools.org/snowstorm/snomed-ct/v2/swagger-ui.html), i tried the same request and it worked perfecly.

Is the snomed browser using another version of snowstorm? 

Thanks

**Comment by CoderMChu** [comment]
@liquid36 Yes the browser is using  a different version (4.1.3 which is not public release yet).  Are you using the master branch version (4.1.0)?

**Comment by liquid36** [comment]
I tried with _latest_ and _develop_ docker image.

**Comment by kaicode** [comment]
Hi @liquid36. Snowstorm 4.4.0 is in Docker Hub now. This version has the features you require and matches the version we are using today for the public browser. Please try again.

**Comment by liquid36** [comment]
Excellent!

**Comment by kaicode** [comment]
I will assume 4.4.0 worked for you and close this ticket. Please just reopen it if you are still having problems. Cheers.

**Comment by gllryns** [comment]
I would assume the es filter would filter out English language descriptions that are part of the Spanish Edition and referenced in the Spanish language refset, but browsing it online shows correct results (e.g. searching for Escherichia coli, an English description referenced in the Spanish Language Refset correctly shows up in the results. I agree with closing the ticket as the original request have been resolved, posting this comment just for the record as I think we have had previous exchanges about the topic with Kai, in any case I would suggest implementations test for retrieval of en descriptions that are part of the Spanish Edition (>25000)
<img width="1280" alt="Screen Shot 2019-11-08 at 12 49 05" src="https://user-images.githubusercontent.com/5036388/68490099-2a9af580-0227-11ea-9276-33dc98992de5.png">
