### ISSUE TITLE
File size RF2 too large

### ISSUE THREAD

**Issue by mertenssander** [IHTSDO/snowstorm#74]
Hi all,

We are testing the new NL Edition, and have run into an issue; trying to import the NL Edition throws the following error;

<img width="1664" alt="Schermafbeelding 2019-09-18 om 10 25 04" src="https://user-images.githubusercontent.com/49483781/65131206-1db80d80-d9ff-11e9-8c68-3240acd81764.png">

I am running 4.1.0 based on the following dockerfile; https://raw.githubusercontent.com/Nictiz/Nictiz-Snowstorm/alpha/snowstorm/Dockerfile-snowstorm
Is there a quick solution for this, or did I miss a configuration option?

Many thanks in advance!

**Comment by mertenssander** [comment]
Perusing the source code, I noticed this; https://github.com/IHTSDO/snowstorm/blob/ffd484752ffd9c3847d6818b294d15e0c5581f35/src/main/resources/application.properties#L82
Which defines the maximum file size as 500MB.
I suspect this is the issue - as the last NL Edition was 480MB, while the new one is 570MB.

**Comment by kaicode** [comment]
Hi @mertenssander,

Yes, you have found the config, see #69.
You could update the dockerfile ENTRYPOINT line to add arguments to override the default. This should work:
```
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","snowstorm.jar","spring.servlet.multipart.max-file-size=1000MB","spring.servlet.multipart.max-request-size=1000MB"]
```

**Comment by mertenssander** [comment]
Thank you for the quick answer as always! I will test this and get back to you, after I complete my tests of the NL Extension.

**Comment by mertenssander** [comment]
Thanks again @kaicode - this seems to do the trick. I am importing the latest concept NL Edition as we speak, which means the file upload at least is working as intended.
I have edited both my orchestrating docker-compose and dockerfile to reflect this, for reference: 

- https://github.com/Nictiz/Nictiz-Snowstorm/blob/e4bd1030238cb0309e4d4d2b039b29eed9c6035b/docker-compose.yml#L55
- https://github.com/Nictiz/Nictiz-Snowstorm/blob/e4bd1030238cb0309e4d4d2b039b29eed9c6035b/snowstorm/Dockerfile-snowstorm#L35

I am sure you already noted this, but I would suggest adding this increase in the next release of snowstorm, as this is something many users will encounter. Could this file-size increase perhaps be due to the new format?

**Comment by mertenssander** [comment]
The NL Edition release file has successfully been imported without errors - thanks for the help and fix for the next release!
