### ISSUE TITLE
Additional relationships not included in inferred ECL

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snowstorm#8]
Relationships with the additional characteristic type, for example "Part of" relationships, should be included in the semantic index for ECL against the inferred form.

**Comment by pgwilliams** [comment]
Ah, I was about to raise an issue to ask this question, so very happy that GitHub pointed me in this direction first!  I suspect that the FHIR API should also include these non-defining relationships when returning the Normal Form - will address.
