### ISSUE TITLE
SNOMED International Hosted Snowstorm API paths have changed - no more "/v2"

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snowstorm#90]
Please be aware that the path of the publicly hosted Snowstorm API has changed.

Please access the public API using one of these endpoints:
- https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/
- https://browser.ihtsdotools.org/snowstorm/snomed-ct/

As before access to this hosted API is subject to the "SNOMED International SNOMED CT Browser License Agreement" published here: https://browser.ihtsdotools.org/

The old path including /v2 no longer works and will be redirected using HTTP 302. This was a hangover from a previous system. We will continue to use semantic versioning of the Snowstorm application and make API changes backwards compatible where possible. If you require a stable production ready Snowstorm instance then hosting your own is the best option.

Kind regards,
Kai

**Comment by greggles** [comment]
Hello, thanks for this notice.

I believe we ran into this issue and were confused for a bit: was our IP being throttled? was there a service outage? was the API getting deprecated?. In trying to investigate and understand the issue we looked at the destination of the 302 redirect hoping it might lead us to a help page that would explain what was happening. The URL we ended up on was https://browser.ihtsdotools.org/snowstorm/snomed-ct/swagger-ui.html which is a generally helpful documentation page but didn't explain what was happening.

It might be more work to achieve this than it's worth, and I understand that. 

Thanks in general for all your work hosting this API!

**Comment by kaicode** [comment]
Hi @greggles, good to hear from you. I'm sorry for the confusion, we will make an effort to give more advanced warning of this type of change in the future. The public API is only for development and testing purposes which is why we felt we could get away with the sudden change but still it's nice not to be left scratching your head!

Please don't hesitate to raise an issue in this repo if you have any questions in the future. We are here to help and love to hear from our community.

Kind regards,
Kai

**Comment by kaicode** [comment]
It's been a year since this change. Closing.
