### ISSUE TITLE
snowstorm.rest-api.readonly.allowReadOnlyPostEndpoints doesn't work if the branch name contains a forward slash

### ISSUE THREAD

**Issue by metaruslan** [IHTSDO/snowstorm#95]
This is a new property introduced in https://github.com/IHTSDO/snowstorm/pull/85
It turned out that it doesn't work for branches that contain a "/" character, obviously the ant matcher considers it to be a path different from
/browser/{branch}/concepts/bulk-load

**Comment by kaicode** [comment]
Thanks @metaruslan , yes it looks like we both only tested this on MAIN!
I've just pushed a fix to develop. Cheers.

**Comment by metaruslan** [comment]
Thank you! When do you guys expect it to release?

**Comment by metaruslan** [comment]
@kaicode, pinging on my last question :–) When do you guys expect it to be released? If I'm not mistaken, your last release was on Dec 18 and this commit was made on Jan 8, so I assume it hasn't been released yet.

**Comment by kaicode** [comment]
Hi @metaruslan, sorry for the slow response, I've been busy building and helping test [Snowstorm Release 4.7.1](https://github.com/IHTSDO/snowstorm/releases) which contains the fix and has just been published!
Cheers.

**Comment by metaruslan** [comment]
Thank you!
